### ISSUE TITLE
When creating a PD/SSFA ToR only show DRAFT and ACTIVE PCA/SSFA

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#10]

**Comment by mpawlowski85** [comment]
In response to Adrian's query - Yes, the DRAFT and ACTIVE refers to Agreement status. 

Adrian Hangan:
DRAFT and ACTIVE PCA/SSFA is referring to agreements status and type?

**Comment by ntrncic** [comment]
@adi130987 please see above question from marcin

**Comment by mpawlowski85** [comment]
In Case more clarification is necessary:
List of SSFAs displayed in field (3.2.2) 
The Agreement field filtering should change. 
It should only display: 
- The PCA associated to a particular partner that is in draft and active status
- Active SSFA that is not associated with another SSFA TOR. 

Any active SSFAs that are associated with another SSFA TOR or ended SSFA should not be available in that field for display. 

Also - the agreements should also have the status displayed next to them (pehaps in brackets).
