### ISSUE TITLE
Unable to save and submit trip due to "Invalid pk "10" - object does not exist: section" message

### ISSUE THREAD

**Issue by marindikanovic** [unicef/etools-issues#1003]
User is unable to save and submit a trip due to an error message. 

see steps below:

C:\Users\mdikanovic\AppData\Local\Temp\wz8249\Recording_20171203_1308.mht

**Comment by marindikanovic** [comment]
Step 1: (‎12/‎3/‎2017 1:05:50 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 2: (‎12/‎3/‎2017 1:06:01 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 3: (‎12/‎3/‎2017 1:06:03 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 4: (‎12/‎3/‎2017 1:06:04 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 5: (‎12/‎3/‎2017 1:06:05 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 6: (‎12/‎3/‎2017 1:06:06 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 7: (‎12/‎3/‎2017 1:06:08 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 8: (‎12/‎3/‎2017 1:06:10 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 9: (‎12/‎3/‎2017 1:06:11 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 10: (‎12/‎3/‎2017 1:06:12 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 11: (‎12/‎3/‎2017 1:06:13 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 12: (‎12/‎3/‎2017 1:06:14 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 13: (‎12/‎3/‎2017 1:06:15 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 14: (‎12/‎3/‎2017 1:06:17 PM) User keyboard input on "Trip Management (window)" in "Trip Management - Google Chrome" [...]

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 15: (‎12/‎3/‎2017 1:06:19 PM) User mouse drag start on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 16: (‎12/‎3/‎2017 1:06:20 PM) User mouse drag end on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 17: (‎12/‎3/‎2017 1:06:22 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 18: (‎12/‎3/‎2017 1:06:23 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 19: (‎12/‎3/‎2017 1:06:26 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 20: (‎12/‎3/‎2017 1:06:28 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 21: (‎12/‎3/‎2017 1:06:30 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 22: (‎12/‎3/‎2017 1:06:32 PM) User mouse drag start on "Trip Management (window)" in "Trip Management - Google Chrome"

No screenshots were saved for this step.


--------------------------------------------------------------------------------

Previous Next 

Step 23: (‎12/‎3/‎2017 1:06:32 PM) User mouse drag end on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 23 screenshot.Step 23 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 24: (‎12/‎3/‎2017 1:06:33 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 24 screenshot.Step 24 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 25: (‎12/‎3/‎2017 1:06:34 PM) User keyboard input on "Trip Management (window)" in "Trip Management - Google Chrome" [...]

Step 25 screenshot.Step 25 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 26: (‎12/‎3/‎2017 1:06:36 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 26 screenshot.Step 26 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 27: (‎12/‎3/‎2017 1:06:37 PM) User keyboard input on "Trip Management (window)" in "Trip Management - Google Chrome" [... Ctrl-A Ctrl-C]

Step 27 screenshot.Step 27 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 28: (‎12/‎3/‎2017 1:06:42 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 28 screenshot.Step 28 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 29: (‎12/‎3/‎2017 1:06:44 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 29 screenshot.Step 29 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 30: (‎12/‎3/‎2017 1:06:44 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 30 screenshot.Step 30 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 31: (‎12/‎3/‎2017 1:06:46 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 31 screenshot.Step 31 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 32: (‎12/‎3/‎2017 1:06:48 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 32 screenshot.Step 32 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 33: (‎12/‎3/‎2017 1:06:50 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 33 screenshot.Step 33 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 34: (‎12/‎3/‎2017 1:06:51 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 34 screenshot.Step 34 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 35: (‎12/‎3/‎2017 1:06:52 PM) User keyboard input on "Trip Management (window)" in "Trip Management - Google Chrome" [... Ctrl-V]

Step 35 screenshot.Step 35 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 36: (‎12/‎3/‎2017 1:06:53 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 36 screenshot.Step 36 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 37: (‎12/‎3/‎2017 1:06:54 PM) User keyboard input on "Trip Management (window)" in "Trip Management - Google Chrome" [...]

Step 37 screenshot.Step 37 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 38: (‎12/‎3/‎2017 1:06:56 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 38 screenshot.Step 38 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 39: (‎12/‎3/‎2017 1:06:58 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 39 screenshot.Step 39 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 40: (‎12/‎3/‎2017 1:07:00 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 40 screenshot.Step 40 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 41: (‎12/‎3/‎2017 1:07:01 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 41 screenshot.Step 41 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 42: (‎12/‎3/‎2017 1:07:03 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 42 screenshot.Step 42 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 43: (‎12/‎3/‎2017 1:07:05 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 43 screenshot.Step 43 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 44: (‎12/‎3/‎2017 1:07:06 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 44 screenshot.Step 44 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 45: (‎12/‎3/‎2017 1:07:08 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 45 screenshot.Step 45 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 46: (‎12/‎3/‎2017 1:07:09 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 46 screenshot.Step 46 screenshot. 
--------------------------------------------------------------------------------

Previous Next 

Step 47: (‎12/‎3/‎2017 1:07:20 PM) User left click on "Trip Management (window)" in "Trip Management - Google Chrome"

Step 47 screenshot.Step 47 screenshot.

**Comment by janpanchalingam1** [comment]
As this was a one-off issue, and was unable to reproduce. Not prioritized.
