### ISSUE TITLE
Dropdowns should have the option to remove selection

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/etools-issues#1014]
Currently if you select an option from a dropdown there is no way to deselect it. You should be able to remove a selection and leave the input empty.

**Comment by adi130987** [comment]
Not really :) ... the functionality that allows to deselect previous selected option exists, but is not active. We'll activate it only if requested.

**Comment by ntrncic** [comment]
@adi130987 please size this

**Comment by adi130987** [comment]
@ntrncic @daniel-tabarcea this is something that should be changed only if requested. For PMP there were no specs to include `None` option in dropdowns (funcionality already in place, it can be activated any time). Maybe we can activate this functionality as we migrate to Polymer 2.

I'll move this issue in the backlog for now and size it.

**Comment by robertavram** [comment]
this is related to a bug raised... I will check the story and connect here..
