### ISSUE TITLE
IE compatability broken again

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#102]

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23756394/7e8dd0fc-04b1-11e7-87fb-9dfb172a6b59.png)

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23756408/8852fbc6-04b1-11e7-9491-089936e87ac0.png)

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23756415/8fefc8f0-04b1-11e7-82fd-4e76143339e8.png)

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23756431/9b6e6812-04b1-11e7-8853-f7fd98fa3804.png)

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23756464/b519dcba-04b1-11e7-894e-e69283220da9.png)

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23756503/d8f3185e-04b1-11e7-9470-6dc12a5a1fb0.png)

**Comment by lordfuoco** [comment]
this task is quite old, but I am moving it because with the Pr associated to it I am able to work on IE 11 (even if it slowly ) I can save a trip and proceed in the flow

**Comment by janpanchalingam1** [comment]
Pass.
