### ISSUE TITLE
IE 11 - Safari - Firefox Compatibility

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#103]

**Comment by evrimm** [comment]
@lordfuoco 
Observed issues  Firefox: I am viewing the List of Trips in Lebanon workspace, when I click on "Add New Trip" the workspace changes to UAT. 
Safari: I can not change country. I can select it from Country dropdown but the previous country I was in loads again.

**Comment by anusenan** [comment]
Moving back to On deck - currently not being worked on

**Comment by torbent** [comment]
@anusenan this was left alone. Can you provide a list of browsers should be supported. Until now we have only focused on chrome and IE11

**Comment by torbent** [comment]
@anusenan @janpanchalingam1 please give us an answer here

**Comment by anusenan** [comment]
Closing this card. During the prioritization meeting- it was agreed that there is no need for a separate card for all browsers.
