### ISSUE TITLE
New PD issue

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/etools-issues#1036]
1. Make sure the prp_mode_off flag is disabled
2. Go to a new PD
3. Fill in details fields
4. Fill in Review and signed fields: doc. submission date, signed by partner office, signed by partner date, signed by unicef officer, signed by unicef date, signed pd/ssfa
5. Save.

Expected: PD is saved
Result: 
![aici ii baiu](https://user-images.githubusercontent.com/17467562/34264502-d0a8e74e-e67b-11e7-9e4c-05685558099f.png)

**Comment by csabadenes** [comment]
Solved by #1044
