### ISSUE TITLE
449 - PD/SSFA Reports: Message "An error occurred. Please try again later."

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-issues#1045]
PD/SSFA Reports: Message "An error occurred. Please try again later." when (1) Clicking on the Reports page navigation or (2) Clicking on the Reports tab of a selected PD/SSFA
Browser: Chrome
Environment: Demo
Workspace: Philippines

1. Click on "Reports" page navigation
OR
1. Click on PD/SSFA page navigation
2. Select any PD/SSFA
3. Click on "Reports" tab

Message, "An error occurred. Please try again later", is displayed.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/34533793-c40d7816-f089-11e7-8a6d-2a276be1f120.png)

**Comment by robertavram** [comment]
Reports is not working since PRP is not up and running.

**Comment by KKaselkar** [comment]
Closing  as PRP will resolve this issue
