### ISSUE TITLE
459 -  Mandatory fields dont have asterisks

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-issues#1064]
Browser:Chrome
Env-Demo
Workspace:Afghanistan(PRP Disabled)

Mandatory fields does not appear as mandatory.Asterick sign(*) is not displayed while creating the new PD.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/34577620-c593eb18-f14f-11e7-8098-76e4f6a4a004.png)

**Comment by robertavram** [comment]
None of those fields are required in order to save as draft
