### ISSUE TITLE
472 - "Locations" field is editable in PD with Closed Status.

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-issues#1075]
"Locations" field is editable in PD with Closed Status.

Browser:Chrome
Env:Demo
workspace:Afghanistan (PRP DIsabled)

"Locations" field is editable in PD with Closed Status. (PRP is OFF)
  
  Linking this card with 1074 as they have similar issues.

**Comment by robertavram** [comment]
closing since it's tracked here: #1074
