### ISSUE TITLE
Travel Count validation not working

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#108]
On Puli staging is possible to send a travel to 'save and submit' with more than 3 travel 'pending' ( travel_count >3 ) this is a validation both for frontend and backend

**Comment by anusenan** [comment]
unicef/etools-t2f  bugfix/travel-count-check

**Comment by janpanchalingam1** [comment]
1) Error is showing 
![image](https://cloud.githubusercontent.com/assets/26144740/24964162/7c067136-1f6e-11e7-8ba9-9338f54d97a8.png)

2) Went to review trips to move to complete but only 1 trip is certification submitted, not 3
![image](https://cloud.githubusercontent.com/assets/26144740/24964140/6e4e9af0-1f6e-11e7-92d4-d86584356b1d.png)

**Comment by janpanchalingam1** [comment]
Pass.
