### ISSUE TITLE
Print TA formatting

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#111]
Noticed a few things when printing a completed trip: 1. The Dates are coming out in a very long format. 2. Travel Type is indicated as [Object Object] though specified in the trip. 3. This field is called Trip Type in T2F. 4. Mode of Travel is indicated as "undefined" in the PDF doc. It should be empty if not filled in, to be consisted with other missing info. 5. The Report comes out with a lot of HTML code. See attachment for more info.

**Comment by anusenan** [comment]
Andras
1. They should be similar now to how they look on print TA
2., Fixed, shows label
3., Fixed
4., As we don't collect this on the form any more, i took it out, along with the same in overview
5., Couldn't reproduce. What gets printed out doesn't contain HTML code added by us, it should match the exact same string, as the input field contains.
(Wasn't this CTRL-C-V'd from an e-mail or website as rich text?)

**Comment by anusenan** [comment]
[file_(1)_(1).pdf](https://github.com/unicef/etools-issues/files/831451/file_.1._.1.pdf)

**Comment by janpanchalingam1** [comment]
Passed in Chrome except for Date/Time formatting in itinerary.
