### ISSUE TITLE
Admin application button incorrectly routing

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#112]

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23757556/2b0ba0e0-04b5-11e7-99c2-9d875133afb4.png)

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23757563/3276a6d6-04b5-11e7-8132-61bdc1eb59b2.png)

**Comment by janpanchalingam1** [comment]
Unable to route from T2F to Dash from etools.unicef.org/t2f/
![image](https://cloud.githubusercontent.com/assets/26144740/24964522/88968606-1f6f-11e7-9134-a6a27819f759.png)

**Comment by janpanchalingam1** [comment]
Passed.
