### ISSUE TITLE
Unable to add Local Currency Budget to an Active PD

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#117]
When I try to enter a Local Currency Amount to an Active PD budget, I get an Error Message "Cannot change fields while intervention is active: unicef_cash_local"
 I am able to change the budget only if I add an amendment type "Change in total budget >20%". This might not be an issue - entered here for tracking purposes.

**Comment by robertavram** [comment]
Until we decide if this is an issue, moving to inbox

**Comment by mpawlowski85** [comment]
this is now obsolete - closing issue
