### ISSUE TITLE
Problems with VISION Integration in Sierra Leone

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#119]
Partner "International Rescue Committee" in Sierra Leone Workspace does not have a Vendor Number assigned. However, in the API - I can see the vendor code (please see screenshot).

**Comment by mpawlowski85** [comment]
![image](https://cloud.githubusercontent.com/assets/26120371/23858619/684fea90-07d7-11e7-8a6d-76e116ae7dc8.png)

**Comment by kasfaw** [comment]
@mpawlowski85 this is not a bug. SL manually added the Partner back before VISION sync was available in 2015/16

**Comment by mpawlowski85** [comment]
ok - I notified the RSS to liaise with the user.
