### ISSUE TITLE
UserVoice Screenshots appear blank

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#120]

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23872456/bf05bfc2-0804-11e7-8cea-adf710e92ac2.png)

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23872576/325fdf98-0805-11e7-8e8e-8a8e054d8580.png)

**Comment by kasfaw** [comment]
this is hindering us from receiving proper error messages from users.

**Comment by robertavram** [comment]
this is most likely an issue with UserVoice not working with front end applications that use ShadowDom and Web Components... We need to do some more research and most likely raise a ticket with UserVoice

If anyone has a minute to do some research on this.. this issue is up for grabs

**Comment by aldohunicef** [comment]
Hi Aldo,

Thanks for reaching out.

I'm not aware of issues with screenshots and ShadowDom and Web Components specifically,  we have thousands of clients and never received an error report about it. 

However, our screenshot feature in the widget does have some limitations.
Our screenshot feature uses html2canvas which has some limitations as explained here: LINK https://html2canvas.hertzen.com/   It seems like this could explain it, but I don't know enough about ShadowDom/Web Components to say for sure.

Let me know once your developers have taken a look to see if this could be the problem.

All the best,

Joey P
L2 Support Engineer
Our L2 Support Engineers are in the office 8AM to 5PM EST M-F.

**Comment by anusenan** [comment]
@robertavram - please check the mail above. This issue is causing problems for Aldo in addressing user concerns .

**Comment by aldohunicef** [comment]
Please see how I am unable to help users because I just simply don't see it. 
It's like driving blind

![image](https://cloud.githubusercontent.com/assets/26142645/24059164/59583ff6-0b24-11e7-8db1-0eee7589a2c1.png)

**Comment by aldohunicef** [comment]
Please include the UserVoice widget on every page of eTools

**Comment by anusenan** [comment]
@robertavram please update

**Comment by robertavram** [comment]
@aldohunicef , this seems to be a problem with html2canvas that uservoice is using for screenshots:
https://github.com/niklasvh/html2canvas/issues/430

**Comment by aldohunicef** [comment]
Hi Aldo,

Thanks for getting back to me, I talked to our team about this.

I have filed a bug, but after discussing with our team this is not something we will be addressing in the near future. To workaround this issue, you have the following available:

1) You can disable screenshots in the widget, using the code screenshots_enabled:false,
2) When screenshots are disabled, users will still be able to add attachments via the widget

When an update on this issue is available, I will reach out to you.

All the best,

Joey P
L2 Support Engineer
Our L2 Support Engineers are in the office 8AM to 5PM EST M-F.

**Comment by aldohunicef** [comment]
@robertavram Please do the following adjustment: 
Disable screenshots in the widget, using the code screenshots_enabled:false,

**Comment by aldohunicef** [comment]
- Add UserVoice Widget to the Dashboards (https://etools.unicef.org/dash/dashboard/personalized) 
- Disable the ability to snap screenshots updating the UserVoice code 
You can disable screenshots in the widget, using the code screenshots_enabled:false,

**Comment by kasfaw** [comment]
@aldohunicef did you test this?
