### ISSUE TITLE
Sierra Leone Result Structure

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#121]
In the Sierra Leone Results Structure, there are:
- Country Programme 0 (From 2016 to 2017)
- Country Programme 1 (From 2016 to 2017)
- SIERRA LEONE COUNTRY PR (2015 - 2018) 

Only the Sierra Leone Country PR is present in VISION and it is unclear where the other two CPs come from. They are causing data issues and they might have to be deleted.

**Comment by kasfaw** [comment]
@mpawlowski85 has fixed this!

**Comment by mpawlowski85** [comment]
Indeed - this is fixed in staging and production. the issue can be closed.
