### ISSUE TITLE
Complex Problems with PMP

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#126]
The issues are quite complex. Glenis from SIerra Leone gets error messages, but they are not specific and none of the fields is highlighted in red. The Messages are: 
- Field Name(0): This field may not be null.
- An Error Occured during data save.

Glenis had the PM and PME permissions

If she then navigates away from the PD page and does a hard refresh, some of the data is saved and some is not.
I am wondering if this has something to do with the error caching issues we had earlier.

A video of all of the issues is available here: 
https://etool.slack.com/files/issmail/F4GJ2USDA/glenis_taylor__issmail_nnafie_-_issue_with_saving_pd_data_friday__march_10__2017_11.42.45_am.mp4

**Comment by anusenan** [comment]
We had a call with @robertavram1 and @nikolatrncic to see what the cause of the problem is and we narrowed it down to PD agreements.
In the meantime we discovered a data issue and an inspecific error message that I will be following up on.

**Comment by robertavram** [comment]
I believe this is related to #131 @adi130987  is working on

**Comment by anusenan** [comment]
@robertavram if it is related please link the two issues. [See this](https://help.waffle.io/faq/waffle-workflow/can-i-link-two-issues-together).
