### ISSUE TITLE
PCA Not Generating (Error Message)

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#128]
When Trying to generate a PCA I get this message:

PDF could not be generated properly: Loading data from Vision Failed, no valid response returned for data: {'vendor_code': u'2500225514'}

although the vendor code is present.
I seem to get the same error in staging on a different workspace/vendor.

**Comment by ntrncic** [comment]
@anusenan can you provide the country and PCA Agreement you're looking at?

**Comment by anusenan** [comment]
@mpawlowski85

**Comment by mpawlowski85** [comment]
I can now generate the PCA - is it possible that it was a transitory issue? I tried both in staging and in prod and both seem to work now.  In any case - we can close this issue now.
