### ISSUE TITLE
Selecting "Extension of Country Programme Cycle" Amendment Type does not trigger appearance of the "End Date" Field.

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#129]
When amending a PCA and the selected amendment type is "Extension of Country Programme Cycle", the expectation is that the field "End Date" will appear (Locked Field->CP End Date). At the moment the End date field does not appear.

**Comment by anusenan** [comment]
Ok, so in the ammendments -> amendment_types for the new entry i tried to send this to the api: [ { type: "CP extension", cp_cycle_end: "2017-03-31"} ]
and a new cp extension amendment gets added, but the date is set to 2020-12-31.
@robertavram  , @ntrncic Am i doing something wrong or is this a back-end issue?

**Comment by robertavram** [comment]
understanding was that CP cycle was extended in vision before you set the amendment. We automatically sync the end date of the CP cycle and we set that date as the end date on the agreement.

**Comment by kasfaw** [comment]
@robertavram you are correct
