### ISSUE TITLE
In some vendors, once a file has been uploaded in the Field Core Values Assessment and saved, it can no longer be deleted or changed

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#13]
"Sample Vendors for which this is true are: 2500235754 (ACADEMIC UNIVERSITY COLLEGE FOR NON VIOLENCE AND HUMAN RIGHTS AUNOH)
2500230496 (ACTED)
2300045672 (ACTED AGENCE D'AIDE A LA COOP TECHNIQUE ET AU DEVELOPMENT)

**Comment by robertavram** [comment]
To change a file should be possible. Can you confirm that changing is an issue as well?

**Comment by mpawlowski85** [comment]
This issue should wait for clarification from the Business Owners. Moving back to inbox.
