### ISSUE TITLE
PMP Intervention sending wrong formatted data

### ISSUE THREAD

**Issue by robertavram** [unicef/etools-issues#131]
etools-ajax is sending wrong formatted data in the case of a file attachment and a valid FR number... FR details are sending in a wrong format.
the Indicator disaggregation is not formatted correctly.
this is in case of Multipart

**Comment by robertavram** [comment]
this is an etools-ajax issue

**Comment by adi130987** [comment]
https://github.com/unicef/etools-partnership-management/pull/187

I removed fr_numbers_details from the data that is sent to server on save. This is readonly data and we do not need to send it back server. 

There are 2 fields that are missing from this fr numbers details  when intervention data is received from server: Agreement Amount (agreement_amount) and Expenditure Amount(expenditure_amount). Do we have these fields data, do we keep these fields or just remove them for now. @robertavram, @ntrncic ?

**Comment by adi130987** [comment]
I do not understand this: "the Indicator disaggregation is not formatted correctly. this is in case of Multipart". Just checked expected results indicators, you can add them no matter the data is multipart or not. Just make sure disaggregation value is separate by ';'

**Comment by adi130987** [comment]
I have some changes for indicator but are related to issue: https://github.com/unicef/etools-issues/issues/27

**Comment by robertavram** [comment]
this issue closes #126 
@adi130987 we have an issue around how etools-ajax is formatting data when multipart... for disaggregations it should send an array of values... but it doesn;t get formatted that way

**Comment by adi130987** [comment]
I'm gonna check it today, Nick sent me a sample from backend of the data you receive.

**Comment by adi130987** [comment]
I think this is more a backend issue, we need to have a call about this.

**Comment by adi130987** [comment]
I made other tests to see If I can reproduce the issue.

![screenshot from 2017-04-19 12 49 02](https://cloud.githubusercontent.com/assets/1955740/25174156/29a9aaa2-24ff-11e7-900d-0e1d03939f09.png)

I added a new indicator with disaggregation_logic:

```javascript
{
   "type of facility": ["1", "2", "3"]
}
```
As multipart data this is sent like this:

`------WebKitFormBoundaryB6pwZS6z7Oijjx16
Content-Disposition: form-data; name="result_links[0][_obj][ll_results][0][_obj][applied_indicators][0][_obj][disaggregation_logic][_obj][type of facility][0]"

1
------WebKitFormBoundaryB6pwZS6z7Oijjx16
Content-Disposition: form-data; name="result_links[0][_obj][ll_results][0][_obj][applied_indicators][0][_obj][disaggregation_logic][_obj][type of facility][1]"

2
------WebKitFormBoundaryB6pwZS6z7Oijjx16
Content-Disposition: form-data; name="result_links[0][_obj][ll_results][0][_obj][applied_indicators][0][_obj][disaggregation_logic][_obj][type of facility][2]"

3
`

But on the backend is received/parsed like this:

`"'result_links[0][_obj][ll_results][0][_obj][applied_indicators][0][_obj][disaggregation_logic][_obj][type][of][facility][0]'"`


Is is possible that Django modifies this before backend parser cand recreate the object? I do not think Django likes the fact we are sending an object that has a property that contains spaces `type of facility`.

We can change the way we are building the disaggregation logic data and this might solve this issue. the format that I'm suggestingis this:

```javascript
disaggregation_logic: [
    {
        disaggregate_by: 'type of facility',
        disaggregation_groups: ['1', '2', '3']
    }
]
```  

@robertavram, @ntrncic what do you think?

**Comment by robertavram** [comment]
Let me get back to you after we make a decision on file uploads
