### ISSUE TITLE
Travel Administrator Does Not have ability to Complete/Cancel trip on behalf of other travellers

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-issues#132]
According to specifications in below link, a Travel Administrator should have ability to complete actions similar to a traveler https://docs.google.com/spreadsheets/d/1Xzui1VBC1aWu0MSXfTCKhkmeXbm-mL1tLMV5dNG_7Co/edit#gid=515059988

**Comment by torbent** [comment]
@anusenan @kasfaw can you verify that this is not an issue anymore?

**Comment by anusenan** [comment]
@torbent -  this can only be confirmed once we test it. Currently, as you know we are not able to complete a trip in staging - once you fix this we can address this issue.

**Comment by anusenan** [comment]
@janpanchalingam1 - can you please confirm whether this is still an issue?

**Comment by janpanchalingam1** [comment]
@anusenan @torbent yes, this is currently an issue. A travel administrator is unable to create a trip on behalf of another user. Once saved, it reverts the Traveller Name to the person setting up the trip, not the traveller they are creating a trip so this is still an issue.

**Comment by anusenan** [comment]
@paragonHex @torbent - this is failiing.

**Comment by aldohunicef** [comment]
As a Travel Admin I can't complete or cancel the trips on behalf of Traveler
![image](https://cloud.githubusercontent.com/assets/26142645/25295988/0fab956e-26b4-11e7-8331-98505f1ee60f.png)
