### ISSUE TITLE
IE 11 - saving function not working for TA required, TA not required and international trips

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#133]

**Comment by janpanchalingam1** [comment]
![saving in ie](https://cloud.githubusercontent.com/assets/26144740/23911540/87822c5c-08b3-11e7-83d3-44fe8f9e6ac5.png)

**Comment by kasfaw** [comment]
@janpanchalingam1 this is a false positive. You are in the lebanon workspace and selected Office/Section from Freetown. Do a hard refresh and retry
