### ISSUE TITLE
Allow editing of fields to Partnership Managers

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#135]
It seems that there are a lot of requests around modification of various field, where data was entered incorrectly or previously missing (In Agreements and PDs). It would be useful to open all Active Agreement and Active PD fields to editing by Partnership Managers only. This would only be for a limited time period.

**Comment by robertavram** [comment]
@ntrncic validation needs to be returning true if partnership manager on the backend
@adi130987 on the front-end we need to grant edit if partnership manager regardless of state

**Comment by robertavram** [comment]
@anusenan please split this into another of the same issue but for front-end
and label Front End... @ntrncic or @ilcsik on backend.. Nik decide.

**Comment by robertavram** [comment]
@anusenan please reference this issue from the front-end one...

**Comment by adi130987** [comment]
@anusenan, @robertavram I just made the changes for PM to be able to edit agreements and PDs fields regardless status.

@ntrncic I made sign dates and agreement dates changes to an active agreement and got this error.
Ex data sent:
```javascript
{
amendments: []
authorized_officers: [90]
signed_by_unicef_date: "2016-04-22"
start: "2016-04-22"
} 
```

```
TypeError at /api/v2/agreements/38/
Transition exception takes a list of errors not <type 'str'>

Request Method: PATCH
Request URL: http://localhost:80/api/v2/agreements/38/
```
