### ISSUE TITLE
Phone Number should not be mandatory

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#137]
The Phone number in staff list in the Partner page is currently mandatory and it does not allow saving of data. This field should not be mandatory.

**Comment by robertavram** [comment]
according to the requirement document it is:
https://docs.google.com/spreadsheets/d/13aDBavOW6BZPP3HVGHXka94SPDBuEs8c-Sh8WfkDEvs/edit#gid=1742783607&range=B34

if this is an enhancement or a change in requirement, please let us know.

**Comment by mpawlowski85** [comment]
This is a change in requirement. This was requested by the business owners.

**Comment by robertavram** [comment]
PLease update the spec and add enhancement label... also.. Per the spec there is no validation so users can theoretically enter - Not Applicable / Not Available / 555-555-5555 as a placeholder in order to be able to save the form.

**Comment by mpawlowski85** [comment]
Label added and specifications updated as requested (changes to specs are highlighted in pink).

**Comment by aldohunicef** [comment]
Since this was causing so many questions around...I verified this on my end with Business owners and should not be mandatory

**Comment by aldohunicef** [comment]
Please justify why this was put back to inbox, it is clear that a business owner said that this shouldn't be mandatory

**Comment by ewheeler** [comment]
@aldohunicef we kicked this back to inbox on 23 March bc this was contradictory to the spec. if the spec has been updated then product should move back to backlog when it is ready for re-review and action by engineering

**Comment by aldohunicef** [comment]
@ewheeler please see the comment made by Marcin, the same day- March 23 "Label added and specifications updated as requested (changes to specs are highlighted in pink). @mpawlowski85

**Comment by ewheeler** [comment]
@aldohunicef yes i know. my point is: engineering does not ever look at inbox--it is product's responsibility to move issues into backlog once product feels they are ready

**Comment by aldohunicef** [comment]
@ewheeler Thanks Ew. Yeah I agree with you... that's why my comment was open and I didn't tag engineering until you replied. I was mostly targeting product team to move it back to Backlog since the spec was already updated. @anusenan

**Comment by mpawlowski85** [comment]
Please note - this is high priority as it prevents users from saving other data on the form. The specification was updated and confirmed with the Business Owners.

**Comment by ewheeler** [comment]
@mpawlowski85 as rob mentioned above, per the spec there is no validation for phone numbers, so users can enter any placeholder text into the field in order to save the form. in other words, there is a workaround that can be communicated to users in the meantime.

**Comment by mpawlowski85** [comment]
@aldohunicef Please take note of the workaround - the users can enter a space in this field if this blocks them from proceeding.

**Comment by kasfaw** [comment]
@mpawlowski85 unsure what the resolution on this one is. Sounds like we keep in inbox?

**Comment by ntrncic** [comment]
@robertavram this is a fronted issue. the api allows phone number None or empty

**Comment by acory** [comment]
@ntrncic  It seems that there still is a backend validation for this.
 This is what I receive from backend: {"staff_members":{"phone":["This field may not be null."]}}
![bkvalidation](https://cloud.githubusercontent.com/assets/26309191/24957113/4a2eeea2-1f93-11e7-8bf1-29148f014efc.png)
