### ISSUE TITLE
Government Activity and PD Output on Trip Activity

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-issues#138]
If I select a a government partner, partnership, and result, I should also have the ability to select activities related to the result selected.

**Comment by kasfaw** [comment]
@robertavram can you provide the model from which the government activities should be pulled from?

@torbent this may require some UX design work on how we have an Activity dropdown next to the Result dropdown whenever a Government partner is selected

**Comment by robertavram** [comment]
@kasfaw https://github.com/unicef/etools/blob/master/EquiTrack/partners/models.py#L1921

**Comment by paragonHex** [comment]
We can easily add a new field, without breaking any UI "rule of thumb" we're using.
It can behave the same as partners/partnerships/results.
@kidus, @robertavram If it's okay, I'll need the static data connections from the backend before doing the bindings.
![screen shot 2017-03-20 at 14 45 11](https://cloud.githubusercontent.com/assets/10398122/24102386/147ae1f4-0d7c-11e7-92ad-46ea6cd1c534.png)

**Comment by torbent** [comment]
Optional field named:
Government partner: Programe Document output 
Other: Activities

**Comment by kasfaw** [comment]
Based on our discussion @torbent we are looking for the ability to intorduce an additional field called "Activity" if a Government Partner and "Programme Output" if NOT Government Partner

This new multiselect field should have a prefiltered list from:
- Activities if a Government Partner
- PD Outputs if NOT a Government Partner

**Comment by janpanchalingam1** [comment]
To be discussed with business owners (Silvia / Nazeef)

**Comment by torbent** [comment]
@janpanchalingam1 @anusenan this should be moved out of backlog if still to be discussed.
