### ISSUE TITLE
Airlines missing on the Trips Module

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#139]
Local airlines from ESARO are missing, and also UNHAS.

**Comment by aldohunicef** [comment]
Local Kenyan airlines like Safarilink, Fly 540, JamboJet do not appear on the list.

**Comment by kasfaw** [comment]
@aldohunicef this is now done - please note that UNHAS, Safarilink, and Fly 540 do not have IATA, ICAO codes.

**Comment by janpanchalingam1** [comment]
Fixed - all airlines showing as requested.
