### ISSUE TITLE
Ability to Add New Partner

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#142]

**Comment by adi130987** [comment]
Please add all the details we need for this one. @robertavram, @ntrncic I understand this is required until 24 March?

**Comment by robertavram** [comment]
@adi130987 look at issue #9 for comments..

**Comment by adi130987** [comment]
https://github.com/unicef/etools-partnership-management/pull/195
@robertavram, @ntrncic, @anusenan  add new partner functionality is ready to be deployed for testing.

**Comment by adi130987** [comment]
closes #9 unless @ntrncic has other changes on backend side
