### ISSUE TITLE
Unable to add sections in Country workspaces

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#144]
Section list not showing up.

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/24003519/10db337c-0a3a-11e7-9fc1-78f8737921ea.png)

**Comment by kasfaw** [comment]
this is not a bug and by design... instruction given to the product team...also make sure NOT to prioritize or assign tickets in the inbox...thanks

**Comment by anusenan** [comment]
Sure Kidus - will keep that in mind. I have labeled it as invalid as we later found out that it was not a bug.
