### ISSUE TITLE
Migration issues in production around Dates

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#148]
As seen in the screen shots, itinerary dates are migrated with final dates showing in the first line and initial dates in the second line, preventing the users from completing their trips. (Kenya, Sierra Leone, and Jordan)

**Comment by janpanchalingam1** [comment]
![migration1](https://cloud.githubusercontent.com/assets/26144740/24047383/e113e14e-0afb-11e7-8367-588435f844bc.png)
![migration2](https://cloud.githubusercontent.com/assets/26144740/24047384/e11b4b50-0afb-11e7-93ac-786e70dcac98.png)
![migration](https://cloud.githubusercontent.com/assets/26144740/24047385/e11ba9f6-0afb-11e7-8354-894b69cb63ba.png)

**Comment by aldohunicef** [comment]
This has been reported as well from Kenya and Lebanon, so the frequency is high.

**Comment by kasfaw** [comment]
@janpanchalingam1 marking this as medium priority as there is a manual way to correct this for now. @aldohunicef for those who are trying to submit trips for approval, they should manually adjust their itineraries
