### ISSUE TITLE
Government In Simple Reference Number should be unique

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#15]
We will need:

validation that ref number is unique
error message if there is a duplicate
migration script to convert duplicate to unique

**Comment by mpawlowski85** [comment]
Failed - After adding a Government in Simple with a duplicate reference number, there is no error message and the systems never stops saving data.

**Comment by adi130987** [comment]
frontend fixed here: https://github.com/unicef/etools-partnership-management/pull/260

**Comment by adi130987** [comment]
connects unicef/etools-issues#312

**Comment by adi130987** [comment]
@mpawlowski85 frontend work is just in develop branch, was not deployed on staging yet.
