### ISSUE TITLE
Broken functionality in chrome and IE (cambodia)

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#151]
Trip Activities not showing, preventing trip from being saved

**Comment by janpanchalingam1** [comment]
![broken functions](https://cloud.githubusercontent.com/assets/26144740/24049324/0697d9d8-0b02-11e7-90b3-020f4d6d98a1.png)

**Comment by kasfaw** [comment]
@janpanchalingam1 please provide console log of errors you see

**Comment by janpanchalingam1** [comment]
![image](https://cloud.githubusercontent.com/assets/26144740/24110560/234042b8-0d6a-11e7-9ee1-c1b7d076bd3a.png)

**Comment by janpanchalingam1** [comment]
Pass.
