### ISSUE TITLE
Partnerships Agreements / Attachments not working

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#153]
User tried to upload an Attachment file for Agreement Details, and it didn't work. 
User tried in Internet Explorer and Chrome. 
Community Manager reproduced the issue and it doesn't work

**Comment by aldohunicef** [comment]
![image](https://cloud.githubusercontent.com/assets/26142645/24052104/a8ad5254-0b0a-11e7-9270-373ef1695707.png)

**Comment by mpawlowski85** [comment]
@aldohunicef @anusenan  Are there any FRs added to the specific PD. Also - is this an issue with PD or Agreements (both labels are added to the issue)?

**Comment by aldohunicef** [comment]
Any kind of attachment is uploading

**Comment by ewheeler** [comment]
closing duplicate
