### ISSUE TITLE
Indicator unit is not displayed

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#158]
The unit in the indicator for PDs are not displayed. The #, % or Yes/No should be displayed.

**Comment by mpawlowski85** [comment]
![pasted image at 2017_03_20 05_48 pm](https://cloud.githubusercontent.com/assets/26120371/24110071/e32f35e0-0d68-11e7-8b96-562dcf9fcfe7.png)

This is what is looks like now - there should be an unit displayed with the indicator

**Comment by kasfaw** [comment]
@evrimm can you update wireframe?

**Comment by evrimm** [comment]
@kasfaw already in the mockups, screenshot attached
![screen_shot_2017-03-28_at_7_03_05_pm](https://cloud.githubusercontent.com/assets/1585349/24431401/ac8cf8e2-13e9-11e7-9516-f6bce8ca7768.png)

**Comment by robertavram** [comment]
I was under the impression that % or # is indicated as part of the indicator statement.. if this is not what we're saying.. and we want a separate indicator to say the type.. please let us know how to proceed.

**Comment by mpawlowski85** [comment]
This seems to have been fixed. closing issue.
