### ISSUE TITLE
PCA Ref Number Generation

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#159]
Currently the year in the PCA generation logic is: 
 year=self.created.year

However, the Year should be taken from the "UNICEF Signed Date" field.

**Comment by anusenan** [comment]
This change in date logic is high priority.

**Comment by ewheeler** [comment]
@anusenan @mpawlowski85 we need a PCA reference number to exist before the PCA is signed, so can't use `UNICEF Signed Date`

**Comment by ewheeler** [comment]
closing invalid
