### ISSUE TITLE
List of CSO Authorized Officers

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#16]
The Partner focal point field is not filtered by the authorized officer from the PCA

**Comment by adi130987** [comment]
The data shown in this dopdown is etools{1.4}(partner staff members) not found in etools{2.3}(agreement authorized officers).

**Comment by robertavram** [comment]
https://docs.google.com/spreadsheets/d/13aDBavOW6BZPP3HVGHXka94SPDBuEs8c-Sh8WfkDEvs/edit#gid=1742783607&range=A118

Partner Focal points as per specs need to be any partner staff members assigned to the the workspace
please update the specs and re-open if this is indeed a new requirement
