### ISSUE TITLE
Migration updating: all trips  have an error code for med/security clearances showing after approval (those needing to be completed)

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#166]
Farhiya is updating/completing the Kenya migration itinerary issues by manually switching the start and end dates. She has reported that she is not able to complete trips older than 6 months due to this error showing.

**Comment by janpanchalingam1** [comment]
![image](https://cloud.githubusercontent.com/assets/26144740/24196989/33d36296-0ed6-11e7-9e44-4b59019ad7fd.png)

**Comment by kasfaw** [comment]
@ewheeler this seems related to the migration script. makes sense to rerun with clearances checked as "Not Applicable" and also correct ordering of itinerary dates for this issue too https://github.com/unicef/etools-issues/issues/148 ?

**Comment by aldohunicef** [comment]
Clearance error is appearing even on planned status trips. 

![image](https://cloud.githubusercontent.com/assets/26142645/24631614/f8433752-188e-11e7-9d32-3396c77e8183.png)

**Comment by ewheeler** [comment]
@aldohunicef i'm not sure this is related to the migration problem

i suspect this has more to do with the user having left the country office

**Comment by evrimm** [comment]
@ewheeler @aldohunicef @janpanchalingam1 The screenshot tells me you were testing in production not staging. @janpanchalingam1 Please don't move anything to Inbox without proper testing, yet alone it's Kidus's role to move to Inbox.
