### ISSUE TITLE
Expense entry - mandatory

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#167]
Trying to edit a trip (correct the dates) as a finance focal point and I cannot save as eTools is saying that "expenses must have 1 valid entry". There are several trips that will not have any expenses so this field should not be required.

**Comment by janpanchalingam1** [comment]
@aldohunicef Expenses are currently not mandatory. The error message is not accurately depicting the issue. I will recreate this for you.

**Comment by aldohunicef** [comment]
so then the issue is that eTools is sending the report that the error is on that field when it is actually not. basically the issue is not really the expense but other field missing and it is confusing because eTools is telling you that is an expense issue,  @janpanchalingam1

**Comment by nlharhoff** [comment]
Any updates on this? Kenya WS it is still required to close trips
