### ISSUE TITLE
Document coding guidelines

### ISSUE THREAD

**Issue by ewheeler** [unicef/etools-issues#169]
Should include things like:
- where to put custom exceptions
- where to put mappings, choices, etc
- when to use TODO and/or XXX and/or FIXME comments
- pylint settings/editor settings
- conventions for module imports
- general organization (e.g., should views always be in a `views` directory even if theres only one `.py` file?)
- what to include in READMEs

**Comment by ewheeler** [comment]
- consistent names for things like `created` vs `created_at`

**Comment by vkurup** [comment]
@evrimm I think (almost) all of this is covered in #448. If there are any items that anyone would like addressed more explicitly, I'd be happy to update the guidelines! Otherwise I think this can be moved to 'In develop'

**Comment by vkurup** [comment]
Ooops @evrimm, sorry! Meant to ping @ewheeler on that comment ^

**Comment by ewheeler** [comment]
yup, looks like #448 has this covered
