### ISSUE TITLE
Mandatory Programmatic Visits in Partner Overview displays incorrect values.

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#177]
There are two Issues here: 
1. The dashboard and the Partner overview do not display the same numbers for the same partners (see the screenshots - the mandatory requirement is different in the two screens). 

2.  The numbers for Mandatory requirement is incorrect (in the screenshot, the partner - Jordan River Foundation is low risk and receives more than $350k, which means that 2 Programmatic visits and 1 spot check is the minimum requirement).

**Comment by mpawlowski85** [comment]
![upload_3_22_2017_at_12_24_38_pm](https://cloud.githubusercontent.com/assets/26120371/24250960/f47743c2-0fae-11e7-90af-988e02201a87.png)
![upload_3_22_2017_at_12_24_12_pm](https://cloud.githubusercontent.com/assets/26120371/24250967/f9a93f44-0fae-11e7-89c5-5879cb252436.png)

**Comment by anusenan** [comment]
closes #161

**Comment by mpawlowski85** [comment]
This might be related to issue #161

**Comment by robertavram** [comment]
This issue is due to the fact that PartnerOrg for PMP api is not returning min requirements. FE adaptation needed as well. splitting into a FE issue as well

**Comment by robertavram** [comment]
Front End counterpart #234

**Comment by mpawlowski85** [comment]
Failed - The record shows incorrect number of Audit  M.R. – as soon as 1 audit report is added, the M.R. changes to 0.

**Comment by robertavram** [comment]
notice this issue relates to Programmatic Visits. You are mentioning Audit Report.

**Comment by mpawlowski85** [comment]
@robertavram This is right - the programmatic visits were tested to be correct. The issue is now only with the audit values. 
I realize that the title of the card is for PV, but the description refers to other HACT values as well - sorry for the confusion. 
M.

**Comment by mpawlowski85** [comment]
The test failed. 
Browser: Chrome
Workspace: Jordan
Link: https://etools-staging.unicef.org/pmp/partners/57/overview
steps: 
Go to the above link
notice the Audits Column - It says Done/M.R - 1/0 
it should say 1/1.

**Comment by robertavram** [comment]
@ntrncic do we need to run script?

**Comment by mpawlowski85** [comment]
Test Passed!
