### ISSUE TITLE
Change number display in Partner Overview

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#179]
The numbers in the overview tab should be rounded to the nearest dollar - no decimals please

There should also be a 1,000 separator, which must be a comma.

**Comment by mpawlowski85** [comment]
Places without the 1,000 separator: 
![image](https://cloud.githubusercontent.com/assets/26120371/24430752/3bca7524-13e6-11e7-8aae-e6495b34165a.png)

![image](https://cloud.githubusercontent.com/assets/26120371/24430782/5d59cfc8-13e6-11e7-9f37-58957926237a.png)

**Comment by acory** [comment]
Should the numbers be rounded , with no decimals on the intervention delails page / Planned Budget area also?

**Comment by mpawlowski85** [comment]
@acory Yes please - sorry for the misleading title. 
The numbers should be without decimals:
- On the partner overview
- Details / Planned Budget
- On the Government in Simple Overview

**Comment by acory** [comment]
Should there be no decimals for input textboxes(see attached img) also? If yes , is this a rule that applies throughout the application?

![inputno](https://cloud.githubusercontent.com/assets/26309191/24700087/c0c0a5fa-19fe-11e7-8570-a1e76a5f6056.png)

**Comment by mpawlowski85** [comment]
@acory the planned budget card should have the option to enter decimals, so this is not an application wide rule.
