### ISSUE TITLE
Validation: Only 1 PCA per Partner per CP

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#181]
The system allows to add an SSFA to a partner that already has a PCA. If a partner has a PCA, then you should not be able to raise an SSFA within the same CP cycle. 
Similarily, if there is already an SSFA, then you should not be able to allow another SSFA to be added (the next document after SSFA for the same partner in the same CP cycle must be a PCA).

**Comment by mpawlowski85** [comment]
This is related to Issue number 44

**Comment by robertavram** [comment]
is this #44

**Comment by ewheeler** [comment]
@mpawlowski85 as discussed, please write up the requirements for this as this enhancement needs more info

**Comment by mpawlowski85** [comment]
@kasfaw I talked to the Business Owners. They would like to delay this until Friday to get Andrea's decision on whether they can release the new PCA template. This issue is on hold until then.
