### ISSUE TITLE
address WBS / Delegate performance - Frontend

### ISSUE THREAD

**Issue by ewheeler** [unicef/etools-issues#183]
- Fetch only WBS data if delegate option is chosen, and other business area selected.
- Block user from interacting with page until loading is done.

**Comment by kasfaw** [comment]
@ewheeler @torbent please remove the delegate and business area piece from the cost assignment card. Following up with business owners on how we proceed with having cost assignments delegated.

**Comment by robertavram** [comment]
@paragonHex @torbent what's the status on this.. I thought that the frontend was aligned for staging... WBSs are not selectable in staging.

**Comment by anusenan** [comment]
@torbent - can you please start tagging related tickets(Front end  and back end) - so that all related tickets are deployed at the same time?   Our team is not able to proceed with testing because 183 was not deployed yesterday.
