### ISSUE TITLE
Static Expense types should allow Negative Values

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-issues#189]
When entering a a static expense type (air, rail, terminal, other), I should be able to enter a negative value.

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/25138890/b25a987e-2429-11e7-806f-27c8b17632ab.png)

**Comment by aldohunicef** [comment]
On April 21 we tested again this and it doesn't work. @paragonHex

**Comment by janpanchalingam1** [comment]
Pass.
