### ISSUE TITLE
Error Msg vague: Saving a New Govt-In-Simple while leaving Ref no blank

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#19]

**Comment by anusenan** [comment]
When Saving a New Govt-In-Simple while leaving Ref no blank, the message is: 
Errors occurred: Field number(0) - This field may not be null

Please make the message more specific.

**Comment by adi130987** [comment]
This type of messages come from backend, we could add a validation with a more specific  message on frontend.

**Comment by kasfaw** [comment]
Can the error message read: "Please enter a unique reference number for your Government Work Plan"

**Comment by robertavram** [comment]
cannot replicate. Please try to replicate.. remove issue from backlog if cleared.

**Comment by daniel-tabarcea** [comment]
I've tried to replicate it and failed. It works fine.

**Comment by ewheeler** [comment]
can't reproduce, so closing
