### ISSUE TITLE
Changes to "I am a Primary Traveler"

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-issues#190]
1. "I am a Primary Traveler" should only be visible for travel type = "Programmatic Visit" and "Spot Check"
2. "I am a Primary Traveler" should be renamed to "Primary Traveler for this Monitoring Activity"

**Comment by paragonHex** [comment]
@kasfaw To make sure:
Am I right to assume that if travel type isn't "Programmatic Visit" or "Spot check", the data sent to the backend is always `Primary traveler is true`?

**Comment by janpanchalingam1** [comment]
@paragonHex if not "programmatic visit" or "spot check" the field 'I am a Primary Traveller' should not be visible and on the back end would be marked as false

**Comment by torbent** [comment]
@paragonHex 
if not Programmatic Visit or Spot Check: hide “is primary traveler” but assign current traveler as primary traveler.

else: Show “is primary traveler” checkbox, with default checked. if unchecked, show dropdown of travellers in Business Area, and only validate if someone is selected.

If “is primary traveler” gets checked again, remove dropdown, and set traveler to primary traveler.

**Comment by janpanchalingam1** [comment]
Passed.
