### ISSUE TITLE
If I'm primary traveler is false, primary traveler dropdown should be required.

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-issues#191]
![screen shot 2017-03-23 at 6 46 19 pm](https://cloud.githubusercontent.com/assets/11070629/24262311/f01736de-0ff9-11e7-96fd-95d5f0020cb1.png)
On first save, receiving an error (see screenshot) when "Im a primary traveler" is unselected. This should not happen.

**Comment by simon-the-sloth** [comment]
If I'm primary traveler is false, primary traveler dropdown should be required.

**Comment by janpanchalingam1** [comment]
![191 print screen](https://cloud.githubusercontent.com/assets/26144740/24832222/bff36320-1c78-11e7-898c-ffa705362cec.png)

**Comment by janpanchalingam1** [comment]
Primary traveller should default to being checked. Dropdown is not showing until checkbox is selected then unselected. Dropdown should show if unchecked.

**Comment by janpanchalingam1** [comment]
Upon further testing, "I am a Primary Travel" is defaults when Trip Type is selected but is inconsistent.

**Comment by ewheeler** [comment]
see related follow up discussion on unicef/etools-issues#190

**Comment by janpanchalingam1** [comment]
Agreed to proceed with logic of unicef/etools-issues#190
