### ISSUE TITLE
Status changing to Sent for Payment

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-issues#193]
When status is in Certified or Completed, and when an FFP selects "Send for Payment", the status of the trip is changing to "Sent for Payment".

The expected behaviour is to have the the invoice workflow executed with:
a) IF the change in cost is less than or equal to the threshold, the status of the trip does not change
b) IF the change in cost is greater than the threshold, the status of the trip changes to Certificate Submitted for supervisor approval

**Comment by janpanchalingam1** [comment]
Currently does not trigger supervisor approval if amount is greater than threshold.
