### ISSUE TITLE
Remove the word "Report" from the Assessment Type in the Partner detail tab.

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#195]
Scheduled Audit Report should be "Scheduled Audit"

Special Audit Report should be "Special Audit"

**Comment by acory** [comment]
The values in the Assessment Type dropdown  come from backend , so they have to be changed there.
Keep in mind that existent partners that have these assessment types selected have to be updated also , given that assessment types are saved by value (not id) on the partner .

**Comment by mpawlowski85** [comment]
This is de-prioritized. The issue is closed.
