### ISSUE TITLE
Parners Staff List - Hide Entries

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#197]
In : Partners -> Partner details ->Staff Members
Once a partner is made inactive, that staff member should become hidden from the list on that screen. There should be a button called "Show Hidden" that would show all of the hidden staff members.

In Addition:

The inactive staff members should not display on lists when a new document is created:

Signed by Partner (Agreements and PD/SSFA Tor"
Partner Authorized Officers

Migrated records should be preserved, but for any documents newly created, inactive staff members should not be displayed.

**Comment by kasfaw** [comment]
@mpawlowski85 please work with @evrimm on wireframing and modifying business requirements prior to moving to backlog

**Comment by mpawlowski85** [comment]
This is deprioritized for now. Specs to be provided later
