### ISSUE TITLE
Add new data point to the partner overview tab

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#198]
The overview tab should contain a new data point - planned programmatic visits. This should sum up all of the additional programmatic visits that are added manually by the user in PD and SSFA TORs.

**Comment by mpawlowski85** [comment]
![image](https://cloud.githubusercontent.com/assets/26120371/24297531/85ab2fbe-1079-11e7-8d7e-6ffdfc2156b1.png)

**Comment by anusenan** [comment]
Moving to In Production since this was deployed last week.
