### ISSUE TITLE
Disappearing "Signed by UNICEF" name once primary workspace is changed

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#203]
Field "Signed by UNICEF" in Agreements and PD/SSFA ToR is populated by members of the senior management group who are assigned to the particular workspace (and it must be their primary workspace). Once that user changes the primary workspace, then the name of the user disappears from all of the associated records. Nik confirmed that the data is stored in the back-end and that this is a front-end only issue.

**Comment by adi130987** [comment]
@ntrncic here is a case where we need a new endpoint to get that used by ID and include it in dropdown options. It's the same issue we have on PD details old cp outputs not showing up.

https://github.com/unicef-polymer/etools-searchable-multiselection-menu/pull/60

**Comment by mpawlowski85** [comment]
Failed - once a person leaves the workspace, the name of the person disappears from Government in Simple Focal Point field. It works as expected elsewhere.

**Comment by robertavram** [comment]
Notice that label does not show Government In Simple. The issue should be labeled with Government In Simple as well...
