### ISSUE TITLE
Add validation in Assessments

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#204]
In Partner Details->Risk Rating and Assessment ->Assessments. 
Add validation: If(Date of Report)>(Today), then ERROR (msg: "The Date of Report cannot be in the future").

**Comment by adi130987** [comment]
@mpawlowski85 what if we would disable selection of dates > Today in the datepicker? What do you think?

**Comment by mpawlowski85** [comment]
@adi130987 yup - that would work as well. If the user cannot select a future date in the date picker, then the validation does not have to be built. 

@evrimm - this is for your info.

**Comment by adi130987** [comment]
The paper-date-picker element we are using in our etools-datepicker element has several issues regarding max/min date(https://github.com/bendavis78/paper-date-picker/pull/147) and we can not use this functionality yet.

We will add a validation message.

**Comment by roxanavlad** [comment]
@adi130987 , this is fixed
- the date picker allows the user to choose date from the past until the current date (today)
- for dates in the future, a messages is displayed
