### ISSUE TITLE
Exports of  List in Partners

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#205]
All exports should only export the filtered data (if any filters are selected). 

For example:
1. When the "Show Hidden" button is in "Off" position, then the export should not contain the hidden/blocked partners. 
2. When I filter the Agreement list by status=draft and hit export, the csv only contains the agreement in draft status.

**Comment by mpawlowski85** [comment]
Hallo @ntrncic 
 
It seems that the filter issue was remediated somewhat. Now the excel should show the records as seen on the screen. Thus if: 
Show Hidden is "Off" -> export only active Partners 
Show Hidden is "On" - > export active + hidden. 
If I can order a side, then please add Hidden/Shown flag to the excel.

**Comment by ntrncic** [comment]
@acory @adi130987 @daniel-tabarcea in the fronted for partners export. If Show Hidden is Off  can you send the query param hidden="false" instead of blank as it is now.
