### ISSUE TITLE
'My profile' not showing in trips prod

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#208]

**Comment by janpanchalingam1** [comment]
![image](https://cloud.githubusercontent.com/assets/26144740/24356488/308eec22-12c8-11e7-94b0-681c31db8814.png)

**Comment by torbent** [comment]
@janpanchalingam1 this needs more feedback. Not sure it's related to trips

**Comment by kasfaw** [comment]
@torbent we would like to keep the banner shown in /dash/ to what is shown in /t2f/ 

can you please take a look at the banner elements in /dash/ and reproduce?

**Comment by torbent** [comment]
@kasfaw @anusenan I believe @marko911 is working on this?

**Comment by marko911** [comment]
I am working on this @kasfaw @anusenan @torbent ... Just needed to wait or some backend adjustments before I could finish...WIP still

**Comment by janpanchalingam1** [comment]
Pass
