### ISSUE TITLE
Trip Dash Should Filter by Year & Have an option to see all months

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#21]
We should be able to see: - filter by Year
- an option to see all months

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23678706/3b67137e-0353-11e7-91a0-4d2c183748b6.png)

**Comment by marko911** [comment]
This is implemented , just hasn't been deployed to production for whatever reason.

**Comment by anusenan** [comment]
I am moving this to Done column.

**Comment by aldohunicef** [comment]
Filtering by month is not working after we tested in production (April 12, 2017)
Once I applied the filter for months it will show the correct results only once. 
If I apply a second filter then the results from the first search will not change. 
i.e. I apply September and I will see the results from April

**Comment by aldohunicef** [comment]
![image](https://cloud.githubusercontent.com/assets/26142645/24963855/c90699e4-1f6d-11e7-9288-f1d215a8aabf.png)

**Comment by aldohunicef** [comment]
![image](https://cloud.githubusercontent.com/assets/26142645/24963893/db0db9f6-1f6d-11e7-9967-32a7f9254470.png)

**Comment by marko911** [comment]
@aldohunicef that is in the Trips app, the current issue we are commenting on was for Trips tab in the Dashboard.

**Comment by janpanchalingam1** [comment]
@aldohunicef created a new Waffle for your issue. This one has been tested and is fixed.
