### ISSUE TITLE
Missing data when logging into a different business area.

### ISSUE THREAD

**Issue by torbent** [unicef/etools-issues#217]
Enforce data validation on front-end to ensure data integrity ( eg. if keys to missing data exist, an error should be raised in a structured way. )

**Comment by kasfaw** [comment]
@ewheeler not sure how to classify/prioritize this since if recall this spans all modules?

**Comment by ewheeler** [comment]
@kasfaw go ahead and prioritize med or high as you see fit and move to backlog for attention from engineering. we'll create any duplicate issues for various frontend apps/backend as necessary once we're ready to tackle and to allocate eng resources

**Comment by kasfaw** [comment]
thanks @ewheeler done

**Comment by lordfuoco** [comment]
This task is done frontend side but blocked backend (in review) it also blocks: #218 #95

**Comment by simon-the-sloth** [comment]
Supported dropdowns/endpoints for now: currencies, dsa regions, business areas, expense types, airlines

**Comment by janpanchalingam1** [comment]
![image](https://cloud.githubusercontent.com/assets/26144740/25536841/314b915a-2c0a-11e7-8059-49ca9b24f914.png)

@simon-the-sloth As seen in the above screenshot, the Traveler shows 'Missing Label.' Is this the intended fix?

**Comment by lordfuoco** [comment]
@janpanchalingam1 as posted by Simon the working 'dropdowns' are: currencies, dsa regions, business areas, expense types, airlines. The support for the rest will be rolled out while we finish building the endpoint with the rest of the backend team ( shared endpoint with PMP and dash )

**Comment by janpanchalingam1** [comment]
As full specifications were not completed for this point, this should not have been worked on.

**Comment by janpanchalingam1** [comment]
Added comment from 334 and marked 334 as invalid to keep comments together:

From @torbent:
Items deleted will need to be fetched to fill historic data in dropdown. The missing data-values are:

    Users ( with driver specification )
    Offices
    Sections
    Partner
    Partnerships
    Results
    Locations
    Government results

**Comment by janpanchalingam1** [comment]
Failed. Pending confirmation of completion from Nik.

**Comment by kasfaw** [comment]
@torbent am i currect in understanding that the below fields are the ones you have a dependency on the UNICEF team on?

Users ( with driver specification )
Offices
Sections
Partner
Partnerships
Results
Locations
Government results

**Comment by torbent** [comment]
@kasfaw correct

**Comment by ntrncic** [comment]
this will be addressed in another waffle card. For now when changing workspaces make sure to click the refresh button.
