### ISSUE TITLE
DSA - Historical values

### ISSUE THREAD

**Issue by torbent** [unicef/etools-issues#218]
* Modify the DSA model to handle historical values. DSA model shall be divided in a fixed part containing the name ‘DSA_AREA_DETAIL’ this model is connect one to many to DSA_RATES which are  composed by the amounts, start date (finalisation date ) and end date (  ‘expiration date' if available ) 
* Stamp the DSA values to the date of submission. 
* Fetch DSA should always show latest data (order by finalisation date, ) and not “deprecated”.
* Deprecation of DSA values. It should be possible to mark DSA area for deletion in a way that it will not show up in future queries, but will still be available as historical data.
* Ability to create custom DSA areas from an Admin interface.
* Update sync'er to be able to handle the new structure.

**Comment by ewheeler** [comment]
related to https://github.com/unicef/etools-issues/issues/58

**Comment by janpanchalingam1** [comment]
Untested until upload for #58 complete
