### ISSUE TITLE
Attachment within PCA/PD records - remove change and delete buttons

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#232]
Once a record  is active, ended, suspended or terminated, it should not be possible to modify the attachment. The Change and Delete Buttons must be removed when the status of PCA,  SSFA, PD or SSFA TOR is Active, ended, suspended or terminated, 

For Draft Status, only Change option is available. No delete option is available in Draft. 

I am attaching a screenshot to show an example of which button I mean.
This change affects all attachment fields in the Agreements Page and Programme Document (Except the attachment tab). 

The change option should remain for partner attachments and the attachment tab in the PD.

**Comment by mpawlowski85** [comment]
![image](https://cloud.githubusercontent.com/assets/26120371/24473870/c5b1ff84-1498-11e7-92ba-04d22412d423.png)

**Comment by mpawlowski85** [comment]
Just a quick comment: to be very specific - the changes apply also to ended, suspended and terminated statuses. Sorry for the late addition - I hope that this won't cause problems. I edited the original card to reflect that.

**Comment by acory** [comment]
can you please elaborate a bit more on this statement : 'The change option should remain for partner attachments and the attachment tab in the PD.' Does this imply any change in these 2 sections or all is good as they are now?

**Comment by mpawlowski85** [comment]
@acory 
Sorry for the confusion. I am refering to these screens: 

![image](https://cloud.githubusercontent.com/assets/26120371/25821908/d5db9a38-3404-11e7-8983-1d1a22ea7c34.png)

![image](https://cloud.githubusercontent.com/assets/26120371/25821947/fc0d70c8-3404-11e7-877c-4d6ed57e2449.png)

In these two cases we need to remove the delete function. The change function should remain.
