### ISSUE TITLE
Invoices list view dollar amounts not showing commas

### ISSUE THREAD

**Issue by andy0202** [unicef/etools-issues#235]
amounts do not have commas

**Comment by andy0202** [comment]
#46

**Comment by andy0202** [comment]
![screen_shot_2017-03-31_at_11_41_04_am](https://cloud.githubusercontent.com/assets/26715203/24558006/b523ba3e-1607-11e7-87bd-5f69bdba00a0.png)

**Comment by janpanchalingam1** [comment]
Pass
