### ISSUE TITLE
Error - Budget Validation

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#236]
I open an active PD, which has a Planned Budget. Not all of the Planned Budget Fields are filled in. I change data (e.g. add a new Result) and hit save. I get an error message around budget fields (the error message screenshot is attached. This is the data dump from the console: 

planned_budget
:
[{id: 21, partner_contribution: "100.00", unicef_cash: "100.00", in_kind_amount: null,…}]
0
:
{id: 21, partner_contribution: "100.00", unicef_cash: "100.00", in_kind_amount: null,…}
currency
:
162
id
:
21
in_kind_amount
:
null
in_kind_amount_local
:
null
partner_contribution
:
"100.00"
partner_contribution_local
:
null
total
:
"201.00"
unicef_cash
:
"100.00"
unicef_cash_local
:
null
year
:
"2016"

**Comment by mpawlowski85** [comment]
![image](https://cloud.githubusercontent.com/assets/26120371/24566519/cb7af39a-1627-11e7-84ec-e4b67dd41105.png)

**Comment by robertavram** [comment]
Minimum 0 should be allowed. Targeting for Monday..

**Comment by adi130987** [comment]
I'll fix this today, the issue is related to currency input.
There is some weird behavior in waffle, I can not find this issue. I will make the changes directly here.

**Comment by adi130987** [comment]
I added validations on frontend too, to avoid having null values on save. On backend side all planned budget values must not be `null` so on frontend we will have this validation as well until it's decided what to do here. We need to have same validations on frontend and backend. Values like `0` or `0.00` are allowed.

**Comment by adi130987** [comment]
etools-currency-amount-input element version needs to be updated too as the issue was related to this element.
