### ISSUE TITLE
Ability to upload more than 10 attachments

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#238]
Currently the PD page can only have 10 attachments. When 11th attachment is saved, the following error appears: "An Error Occurred on Data Save".

**Comment by aldohunicef** [comment]
Syria users affected

**Comment by adi130987** [comment]
Just tested and reproduced the issue. In this case the server returns 413 Request Entity Too Large status code meaning that the total size of the uploaded files exceeded server's upload limit. The upload limit has to be increased on server, but this should be discussed with @robertavram.

**Comment by robertavram** [comment]
@adi130987 it's a problem of serialization on the backend... can we make sure we don't send previously saved records on PD attachments... (if it has an id and the file type has not changed do not send it)

**Comment by adi130987** [comment]
@robertavram, yes we could send only the changed values. I'm gonna create a new issue for this.
