### ISSUE TITLE
Error codes review

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#240]
There is confusion on what the error codes mean and what exactly are the issues/missing information prohibiting the traveler from moving forward. Requesting a review of all error codes to be more descriptive for the user.

**Comment by janpanchalingam1** [comment]
![image](https://cloud.githubusercontent.com/assets/26144740/24656037/c129756c-190e-11e7-8526-b7b033ccb620.png)

@torbent do you have a full list of these errors? I have reviewed our documentation and am wondering if this was decided outside of the specification and it was our mistake as we did not document this?

**Comment by janpanchalingam1** [comment]
![capture](https://cloud.githubusercontent.com/assets/26144740/24656171/66c9d584-190f-11e7-970c-d395543fe222.PNG)

**Comment by janpanchalingam1** [comment]
@torbent do you have a list of all errors? Or were these descriptions defined outside of the specification document and it was our error as they were not documented in the specification?

**Comment by torbent** [comment]
@janpanchalingam1 This is the one we used, but there were never changes added so we implemented that. https://docs.google.com/spreadsheets/d/1krh9mGvGk1b1yrPvEwYerBt-1QG6-X0AqzgooUITwu8/edit?ts=586fb706#gid=0
Since this doc was created and implemented, new errors have arrived with new functionality, so it is not up to date. If you would like to re-enter this issue I suggest coordinating with @ewheeler  first, since he was mentioning a internationalisation workshop. This update could fit very well into that.

**Comment by janpanchalingam1** [comment]
@torbent is there any documentation on validations against these error messages? @anusenan if not, could you help in putting together a new document with error messages against the validations with Evan because other than this document provided by Torben, such a document does not exist.

**Comment by anusenan** [comment]
@torbent can u please share the existing list of error messages in Trips module along with what action/missing data triggers them?  We can share this with business for their review.

**Comment by torbent** [comment]
@anusenan it's not trivial to share this as they are not in one place, so unless @ewheeler blocks this we will go ahead and prepare the error messages through gettext and then send you the list to update. 
This way we don't have to redo this process from scratch every time, and we can add a tool so you can manage them directly should you wish this.

**Comment by ewheeler** [comment]
@anusenan @janpanchalingam1 this is quite a bit of work as @torbent has noted and i'm not sure that we should be devoting so much engineering time to this right now 

we will be finalizing coding guidelines that will affect how we organize code for things like errors as well as internationalization.. so risky to do this now when we might need to re-do some of the same work again soon.
