### ISSUE TITLE
Intervention - attachment file name disappears

### ISSUE THREAD

**Issue by acory** [unicef/etools-issues#249]
Edit an Intervention , go to Attachments tab.
If you upload more than 1 doc at a time , after save the names of the files disappear , see pic
![noname](https://cloud.githubusercontent.com/assets/26309191/24797562/70bc429c-1b9a-11e7-918c-2ca7f9e39c79.png)

**Comment by robertavram** [comment]
@acory this could be an issue only on localhost... we're not experiencing this in staging
