### ISSUE TITLE
Update page refresh functionality

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/etools-issues#250]
Hide the current refresh button from the top right corner and add a section that allows a user to clear cached data individually for Governments, Partners, Interventions or Agreements

**Comment by evrimm** [comment]
Although we see the value in clearing cached data individually, the product team needs to be consulted for such changes as it has implications on design and user experience.  For example in dashboard module, the refresh button remains in the top right corner because there is no left nav bar. This inconsistency is major and unwanted. The implementation of this functionality requires discussion even with the business owners.

**Comment by adi130987** [comment]
This functionality was requested by Rob and Evan,  we talked about it when they visited our office. The design can be changed. If you do not like this functionality we can put back the old button. Please talk with Rob and Evan about this.

**Comment by adi130987** [comment]
@evrimm I restored the refresh button to keep design consistency with the other apps, but I kept the functionality of clearing data by category(the fix fill get on etools-dev today). Let me know what you think about this.

**Comment by roxanavlad** [comment]
@adi130987 , @evrimm , I found a possible UX issue:

the PD details page isn't displayed anymore after I try 2 types of refresh

steps to reproduce the issue:
1. go to PD/SSFA ToR and select a PD
2. select refresh from the browser
3. the detail page is refreshed and all the data is displayed, fields can be edited
4. select refresh from the application (the refresh button from the right corner, next to the sign out button)
5. select PD/SSFA ToR to be refreshed
6. select refresh data button

Expected result: the detail page is refreshed and the data is displayed

Actual result: the detail page is refreshed and the user is redirected to the intervention list, which is empty.

This flow is not good for the UX, as it can lead the user to believe that there is no data in the intervention list, or that the data that he/she was editing got lost.

**Comment by kasfaw** [comment]
@adi130987 I have failed this issue based on @roxanavlad commment
