### ISSUE TITLE
Move permission matrix generator to backend repo

### ISSUE THREAD

**Issue by simon-the-sloth** [unicef/etools-issues#254]
The permission matrix generator should be included in the backend repo.
https://github.com/unicef/etools/pull/599#issuecomment-292525713

**Comment by kasfaw** [comment]
@simon-the-sloth moving this to backlog in case this is work that still needs to be done. Do mark as invalid if this should not be done any longer

**Comment by torbent** [comment]
@kasfaw we believe this whole approach should be changed as a part of the next set of requirements. We believe that this generator is obsolete  and that permissions should simply be served from the backend, and not generated, moved to front-end, and then evaluated.... This is out opinion, but we should have at least @robertavram @ewheeler or @ntrncic to give opinion on this.
