### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#255]
-	PMP  Not loading for certain users
-	The save button seemingly has no effect (the data is actually saved, but once save is clicked nothing happens). 
-	Erratic behaviour - sometimes it is not possible to change the workspace (you must change the workspace and then hit hard refresh to continue and even then the old workspace is displayed).

**Comment by mpawlowski85** [comment]
![image](https://cloud.githubusercontent.com/assets/26120371/24866795/402d6624-1dd9-11e7-820a-46655afc9d70.png)

**Comment by robertavram** [comment]
I believe some elements are not loading in proper older

**Comment by adi130987** [comment]
The error is too generic, hard to debug. It seems to be related to planned-budget element. I'm gonna continue tomorrow on it.

**Comment by mpawlowski85** [comment]
@adi130987 Sorry for the general description.  To give you a specific instance: 
1. I go to https://etools-staging.unicef.org/pmp/  in IE11 and I am in workdspace Jordan
2. I try to change the workspace to Kazakhstan
Nothing happens - I can now see a cursor blinking next to the word Kazakhstan 
![image](https://cloud.githubusercontent.com/assets/26120371/25008188/f6c2cf38-2030-11e7-9c0c-c4b93bb23e05.png)

3. I click somewhere randomly on the screen
nothing happens - the cursor disappears, but the workspace is not loading
4. I do a hard refresh 
still nothing happens - the workspace displays as Kazakhstan, but the data are still Jordan data. 
5. I go to the Agreement Page - The Jordan data are displayed
6. I go to PD/SSFA TOR page - The Kazakhstan data are displayed
7. I go to Governments - Kazakhstan Data are displayed.  

I hope this helps somewhat.

**Comment by adi130987** [comment]
A fix was made and will be put on staging today, by Nik

**Comment by andy0202** [comment]
![capture](https://cloud.githubusercontent.com/assets/26715203/25491253/617d427e-2b3d-11e7-9cea-15fdb188ab06.PNG) Did not pass final test.
