### ISSUE TITLE
Error 400 on Government in Simple

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#256]
When trying to modify and save an Existing Governemnt-in-simple records the following appears: 

Error text appears: "Government intervention with the same reference number already exists". 

There does not seem to be any particular combination of data inputs that leads to it. The data dump from the console is available below.

**Comment by mpawlowski85** [comment]
1.	Request URL:
https://etools-staging.unicef.org/api/v2/government_interventions/9/
2.	Request Method:
PATCH
3.	Status Code:
400 Bad Request
4.	Remote Address:
23.97.169.141:443
5.	Referrer Policy:
no-referrer-when-downgrade
2.	Response Headersview source
1.	Allow:
GET, PATCH
2.	Content-Type:
application/json
3.	Date:
Mon, 10 Apr 2017 14:55:54 GMT
4.	Server:
gunicorn/19.6.0
5.	Transfer-Encoding:
chunked
6.	Vary:
Accept, Cookie
7.	X-Frame-Options:
SAMEORIGIN
3.	Request Headersview source
1.	accept:
application/json
2.	Accept-Encoding:
gzip, deflate, sdch, br
3.	Accept-Language:
en-US,en;q=0.8
4.	Connection:
keep-alive
5.	Content-Length:
1528
6.	content-type:
application/json
7.	Cookie:
__unam=1c83e6d-15b43f47fab-7386c5f2-1; _ga=GA1.2.247734162.1455904846; csrftoken=NAYSU1779uaZdh9Ppdl5wejlkdsUZakZ; sessionid=64hojm2l3po3le77u7fp5sjnm01fqpk7; uvts=4CHuCS5x3zjYfQzR
8.	Host:
etools-staging.unicef.org
9.	Origin:
https://etools-staging.unicef.org
10.	Referer:
https://etools-staging.unicef.org/pmp/governments/9/details
11.	User-Agent:
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
12.	x-csrftoken:
NAYSU1779uaZdh9Ppdl5wejlkdsUZakZ
4.	Request Payloadview source
1.	
1.	{id: 9,…}
1.	actual_total_sum:49921.03
2.	country_programme:2
3.	created_at:"2017-04-04T14:26:03.758397Z"
4.	id:9
5.	implementation_status:[{,…}, {,…}]
1.	0:{,…}
1.	actual_sum:38313.03
2.	cp_name:"1.1 POLICY - NEWBORN & CHILD HEALTH"
3.	cp_output:312
4.	fc_records:[{id: 106, fc_ref_number: "0100232424-2", line_item: "2", wbs: "2340/A0/04/881/001/003",…}]
1.	0:{id: 106, fc_ref_number: "0100232424-2", line_item: "2", wbs: "2340/A0/04/881/001/003",…}
5.	outstanding_sum:null
2.	1:{,…}
1.	actual_sum:11608
2.	cp_name:"1.2 HEALTH & NUTRITION SYSTEMS"
3.	cp_output:47
4.	fc_records:[{id: 105, fc_ref_number: "0100232424-3", line_item: "3", wbs: "2340/A0/04/881/002/001",…}]
1.	0:{id: 105, fc_ref_number: "0100232424-3", line_item: "3", wbs: "2340/A0/04/881/002/001",…}
5.	outstanding_sum:null
6.	number:"JOR//01"
7.	outstanding_total_sum:null
8.	partner:284
9.	result_structure:null
10.	results:[{id: 17, intervention: 9, result: 312, year: "2017", planned_amount: "0", result_activities: [],…},…]
1.	0:{id: 17, intervention: 9, result: 312, year: "2017", planned_amount: "0", result_activities: [],…}
1.	id:17
2.	intervention:9
3.	planned_amount:"0"
4.	planned_visits:"10"
5.	result:312
6.	result_activities:[]
7.	sections:[]
8.	sectors:[]
9.	unicef_managers:[]
10.	year:"2017"
2.	1:{id: 21, intervention: 9, result: 47, year: "2014", planned_amount: 1, result_activities: [],…}
1.	id:21
2.	intervention:9
3.	planned_amount:1
4.	planned_visits:0
5.	result:47
6.	result_activities:[]
7.	sections:[]
8.	sectors:[]
9.	unicef_managers:[]
10.	year:"2014"

**Comment by asuley** [comment]
This was found in Jordan workspace

**Comment by robertavram** [comment]
@mpawlowski85 issue is fixed, available in staging now

**Comment by mpawlowski85** [comment]
@robertavram thanks - I tried to re-create the error, but I am unable to. 
We should consider this issue closed now. In case if the error appears again, then we will have to report it again. I will communicate to Nazeef and Silvia about the cause of the issue and the solution that was implemented.
