### ISSUE TITLE
Write scrips to migrate trip activities

### ISSUE THREAD

**Issue by robertavram** [unicef/etools-issues#257]
Write scrips to migrate trip activities (Programmatic Visits and Spot Checks) to the right partners. (Marcin to provide the PO ids). Run script to re-calculate HACT based on the new values.
Migrate Staff Members as well.

**Comment by mpawlowski85** [comment]
Currently awaiting data mapping from the Country Office (needed for testing).

**Comment by mpawlowski85** [comment]
#302 
Please see issue 302 for the list of records to be migrated.

**Comment by mpawlowski85** [comment]
There were a number of partner records that were manually entered. However, now that VISION synced records are available, all of the records associated with manual partners have to be re-mapped to the VISION synced ones.

The mapping of records Manual vs. Vision synced is available here:
[Re-mapping of partners.xlsx](https://github.com/unicef/etools-issues/files/955480/Re-mapping.of.partners.xlsx)

Please remember that all records should be mapped and the HACT tables updated at the end of the mapping.

**Comment by robertavram** [comment]
@mpawlowski85 could we get this in a different format:
[(old_partner_id, new_partner_id), (old_partner_id, new_partner_id), etc...]
ex:
(12,16),(14,31) etc...

assuming this is only for Sierra Leone?
:) thanks

**Comment by mpawlowski85** [comment]
Toma: 

![image](https://cloud.githubusercontent.com/assets/26120371/25547662/7c36168c-2c36-11e7-8d3e-31c5404b9674.png)

**Comment by mpawlowski85** [comment]
Yes - this is only for Sierra Leone PRD. 
The Idea is that the all PCA and PDs and SSFAs that are with a manual entry partner (e.g. 39) will now be assigned to the correct VISION synced partner records (e.g. 61). I think we have a common understanding. 
M.

**Comment by mpawlowski85** [comment]
I checked a sample of records (PCA, staff members, travel activities) and all records in the sample were migrated correctly.
