### ISSUE TITLE
Esmm dropdown, paper-input autovalidate changes

### ISSUE THREAD

**Issue by adi130987** [unicef/etools-issues#258]
esmm dropdown, paper-input or other fields that are using autovalidate must depend on the used data. Ex: load interventions list and click add new, validations are shown by default in some cases, even save was not used. This happens because autovalidate is used and the data set on the element is `null` in case of new intervention page.

**Comment by adi130987** [comment]
![screenshot from 2017-04-11 15 53 28](https://cloud.githubusercontent.com/assets/1955740/24910098/4bb3ae08-1ecf-11e7-99a0-b4f71b0ba210.png)

**Comment by daniel-tabarcea** [comment]
I'm presuming auto-validate is needed so we don't send requests unless they're complete, right?

**Comment by adi130987** [comment]
It's just a UI thing in case the template is rendered and then empty data is initialized, auto-validate triggers the validation and it should not do that at first time form loads.

**Comment by daniel-tabarcea** [comment]
It seems to work better without auto-validate than with it. How can i reproduce the situation with empty data initialized?

**Comment by adi130987** [comment]
Reload interventions list, then click add new.
