### ISSUE TITLE
CP Outputs should be filtered by the selected Country Programme

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#26]

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23678950/18ace3e4-0354-11e7-8290-a8d23c5141a3.png)

**Comment by robertavram** [comment]
@ntrncic @adi130987 work together to get all CP outputs in the front-end... and populate these by that filter.. This ties in with "CP Outputs not showing" issue

**Comment by adi130987** [comment]
Are there endpoints we can use for this?

**Comment by ntrncic** [comment]
@adi130987 /api/v2/dropdowns/pmp/ get cp_ouptuts for current country program

**Comment by adi130987** [comment]
Thx @ntrncic, we already use this endpoint to get cp_outputs, we just need to filter them by selected country programme
