### ISSUE TITLE
Users from Kenya and Kyrgyzstan can't save new trips

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#260]
Users from Kenya and Kyrgyzstan have been trying to add new trips and the form is not being saved. All the itineraries are correct, cost assignment included and any error is reported by eTools however the trips is not being saved. This has been tested under the permissions of "Traveller" and "Travel Admin"

**Comment by aldohunicef** [comment]
Can you review this card? @janpanchalingam1

**Comment by ntrncic** [comment]
Linking to Sentry error https://sentry.io/unicef-jk/etools-prod/issues/229730348/

**Comment by janpanchalingam1** [comment]
500 error showing for Kenya and Kyrgyzstan prohibiting users from saving travel. Discussed with Nik, and found error linked to Sentry, shown in above comment and is currently being working on by Simon.

**Comment by anusenan** [comment]
@torbent - can u update me on this?

**Comment by janpanchalingam1** [comment]
@ntrncic has fixed this issue in production.

**Comment by aldohunicef** [comment]
On April 25, we have verified with users from Kyrg that any user can't save a trip (CHROME)

Same reports have been sent by Kenya and Lebanon (the other two countries trying to use the module). This needs to go back to Inbox

**Comment by lordfuoco** [comment]
@torbent @aldohunicef @janpanchalingam1 as far as we know this is a data configuration issue (probably due to old data added in the system) @simon-the-sloth already discussed this with @anusenan and explained how to fix the problem. This is not a card that will move forward with a PR or with the normal flow, how should we handle this ?

**Comment by janpanchalingam1** [comment]
@lordfuoco @ntrncic Hi Nico, Nik fixed the counters yesterday for these countries and this is now working in production so we can move this card to completed.

**Comment by torbent** [comment]
@anusenan @janpanchalingam1 please move to complete

**Comment by anusenan** [comment]
Understand from the above comments that this is fixed. Hence moving this card to In production
