### ISSUE TITLE
Erratic Behaviour - display of the Core Value (Attachment) field

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#263]
A user has reported that they had a situation where the Core Values (attachment) field in Partner Details screen were displayed and sometimes it did not. Both records has CSO Type = CSO, so the field should show. The next time user logged in, the field appeared.

**Comment by mpawlowski85** [comment]
![capture](https://cloud.githubusercontent.com/assets/26120371/24931058/c9ba465e-1ed9-11e7-921a-394041f8f6c2.PNG)
![capture2](https://cloud.githubusercontent.com/assets/26120371/24931059/c9c0e356-1ed9-11e7-87a0-ba18a9f75ff2.PNG)

**Comment by acory** [comment]
The  current requirements and implementation is that the Core Value attachment field appears when Partner type is CSO  and CSO type is one of : Academic Institution, Community Based Organization, National . 
So for CSO type  'International' , the Core Value attachment field does not show up.

**Comment by mpawlowski85** [comment]
@acory Yes - this is the correct behaviour. Sorry for the confusion - I was convinced that it was national, but clearly the screenshots prove me wrong. 
I will close this issue.

**Comment by aldohunicef** [comment]
@mpawlowski85 Since we tested this extensively... I suspect this is related to cache issues. Let's double check with the user
