### ISSUE TITLE
Dates disappearing on non-TA and international trip Save and Complete

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#265]

**Comment by janpanchalingam1** [comment]
1) Created a non-TA trip (not saved yet)
![image](https://cloud.githubusercontent.com/assets/26144740/24962033/a40ee60a-1f68-11e7-8865-d32e619c694b.png)
 
2) Clicked Save and dates disappear
![image](https://cloud.githubusercontent.com/assets/26144740/24962099/d5c50fd0-1f68-11e7-98fa-c89c88e643ff.png)

3) Reentered dates 
![image](https://cloud.githubusercontent.com/assets/26144740/24962145/08a9c832-1f69-11e7-9bf8-b495ea52deee.png)

4) Clicked completed and dates dissappear again
![image](https://cloud.githubusercontent.com/assets/26144740/24962195/37bcdda8-1f69-11e7-96e3-c7419a5aedee.png)

**Comment by janpanchalingam1** [comment]
Same issue for international trips. Dates disappear. 

![image](https://cloud.githubusercontent.com/assets/26144740/24962710/ad81b670-1f6a-11e7-90b5-52309107ac0b.png)

**Comment by paragonHex** [comment]
It will automatically get solved together with issue #270.

**Comment by janpanchalingam1** [comment]
@torbent @anusenan The fix for non-TA and international trips is performing more erratically than we expected. When entering information in the Trip Overview, the end date and trip activity fields is sometimes selectable, and other times is not. Also, when clicking on end date, supervisor name changes to one that was not selected. After 4 or 5 refreshes are we only able to save a non-TA or international trip. Any thoughts on this? Please test in staging and let me know if you are having the same issue.

**Comment by anusenan** [comment]
@robertavram @torbent -confirmed as an  issue- related to #279. Cannot proceed with testing because of this issue.

**Comment by aldohunicef** [comment]
Passed in Chrome

**Comment by nlharhoff** [comment]
When will it be in PRD?
