### ISSUE TITLE
Etool-ajax bug in IE 11

### ISSUE THREAD

**Issue by acory** [unicef/etools-issues#272]
In IE 11 requests that in other browsers return null , here return empty string .
This generates an error in etool-ajax , line 607 , when JSON.parse-ing an empty string.
Exemple request : when changing the country

**Comment by daniel-tabarcea** [comment]
A bit more info on this: 
The countries API returns 204 no-content. In ff and chrome, the response body comes as null but in IE 11 it's an empty string. The fact that it's a string makes this module think it should be decoded and when it tries, it throws an error and halts execution.
