### ISSUE TITLE
IndexedDb refresh not working in IE, Edge, Firefox

### ISSUE THREAD

**Issue by acory** [unicef/etools-issues#273]
Select country Lebanon , look at the list of partners. 
Select other country , look at the list of partners , and you will see that the partners coressponding to Lebanon are still there

**Comment by acory** [comment]
Needs more testing to be confirmed

**Comment by adi130987** [comment]
Fixed by @acory PR: https://github.com/unicef-polymer/etools-page-refresh/pull/1
