### ISSUE TITLE
Travel overlapping dates error (reject)

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#275]
1) Traveller saves and submits trip to supervisor for approval 2) Supervisor rejects trip for any reason 3) overlapping dates error shows when supervisor rejects trip, not allowing traveller to save unless dates are changed from original trip dates (1)

**Comment by janpanchalingam1** [comment]
![overlapping dates on rejection](https://cloud.githubusercontent.com/assets/26144740/25070513/8f558a3a-226e-11e7-952b-0b3eaf2e5117.png)

**Comment by simon-the-sloth** [comment]
@janpanchalingam1 Is it still happening? I experienced a similar issue, but we already sent a fix for that a few week ago.

**Comment by janpanchalingam1** [comment]
@simon-the-sloth we completed testing today and this is not an issue anymore. Thanks!
