### ISSUE TITLE
Traveller able to edit Itinerary dates after approval with no notification to FFP

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#277]
1) As a Traveler I enter a trip and send for approval.
2.) Then I open the trip again to make changes.
3.) Meanwhile, the supervisor approves based on the original submission.
4.) After approved, I still change my dates, DSA and costs and when I click on save, the trip saves as approved with my new changes 

There is no distinction between what was approved first and what the traveler change. This would allow the traveler to modify DSA after approval causing major issues.

**Comment by lordfuoco** [comment]
@janpanchalingam1 I double checked and the permission matrix do not allow the traveler to modify anything beside: activities, trip-report and action points in status: Approved in line with this: https://docs.google.com/spreadsheets/d/1aXYICeNsPEmwUeNTwfoUt_nqvXYHDe5xKNgEdBOwoF0/edit#gid=1812985620

Can you double check that the user used to do the test had no FFP or Travel-Admin or Travel Focal point roles ? in that case  the logic is to merge the permission of those roles. (in the means that if FFP can edit A he can edit A even when he is the traveler )

**Comment by kasfaw** [comment]
@lordfuoco @torbent you are correct, it is working as expected BUT only when a traveler refreshes the page after approval. When we tested the below steps, a traveler was able to make changes to a trip that has already been approved. Please test and let us know what you get:
1. traveler submits a trip for approval BUT does not leave the page
2. meanwhile, supervisor approves trip
3. traveler (still on the same screen as before) changes details in itinerary, deductions, expenses, cost assignment and hits save

Observation: the changes are shown to have saved successfully and the trip is in the sent for payment status. When the supervisor refreshes his screen, he also sees the changes the traveler has made

**Comment by simon-the-sloth** [comment]
@kasfaw Your assumption is right, I found a bug in the permission matrix checker on the backend side.

**Comment by janpanchalingam1** [comment]
Pass
