### ISSUE TITLE
Spelling errors Trips

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#278]
View all trip management spelling errors here: https://docs.google.com/document/d/1KYT71-a67LvQj330ajrJVkBZ__6B3GdQJIEvAHx2fik/edit?usp=sharing

**Comment by lordfuoco** [comment]
@janpanchalingam1 some of the requested changes were 'old' in the meaning that the actual system do not has some of those errors or the word - sentence is completely different. I applied what made sense and correct almost everywhere Travel with Trip (minus in mode of travel )

**Comment by janpanchalingam1** [comment]
Pass
