### ISSUE TITLE
Supervisor's name disappears after users inserts start date

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#279]
In Staging / Kenya
User selects Supervisor from Drop Down Menu then immediately user inserts Start Date and then Supervisor's name goes away - the field becomes blank. 

Issue discovered on a testing review on April 17, 2017

**Comment by aldohunicef** [comment]
![image](https://cloud.githubusercontent.com/assets/26142645/25098343/2948db8a-2376-11e7-8d73-85a72fbb61de.png)

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/25098552/01d70274-2377-11e7-8338-2ffa2eff1e2c.png)
 When I tried to replicate the issue - the behavior changed . Both supervisor and purpose of trips are highlighted after entering the Start date

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/25098630/4f936066-2377-11e7-97f6-078daccbcbec.png)

Tried replicating again. This time after entering Start Date the Supervisor name changed. In all scenarios mentioned the Supervisor field remained uneditable.

**Comment by aldohunicef** [comment]
The same happens to NON-TA 

![image](https://cloud.githubusercontent.com/assets/26142645/25098910/476047fa-2378-11e7-9d5c-95d342ee92b7.png)

**Comment by torbent** [comment]
@janpanchalingam1 @anusenan this was hot-fixed and in production. Please verify

**Comment by janpanchalingam1** [comment]
@torbent yes this has been fixed and the supervisors name appears correctly now
