### ISSUE TITLE
Delete Records from Sierra Leone

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#281]
Country Office requested that some Programme Documents be deleted. 
The list is available in the attachment. 
Input from the dev team is needed as to possible consequences.

**Comment by mpawlowski85** [comment]
[Sierra Leone - To Be Deleted.xlsx](https://github.com/unicef/etools-issues/files/926682/Sierra.Leone.-.To.Be.Deleted.xlsx)

**Comment by robertavram** [comment]
All the links provided in the excel are agreements. If we delete all agreements. we'll have to delete all PDs, We'll also have to look at potential impact on trips. @mpawlowski85  as this is prioritized as high.. assuming we go ahead with it? we might have to delete trips altogether.
also the script for hact will have to be re-run for initial calculation (@ntrncic fyi)

**Comment by mpawlowski85** [comment]
@robertavram I will re- confirm with the Country Office about this. But since the PCAs are in draft I do not expect any of them to have any PDs associated with it.

**Comment by robertavram** [comment]
@mpawlowski85 I mentioned it because the title of the card reads "delete Programme Documents" are we supposed to delete agreements instead?

**Comment by mpawlowski85** [comment]
@robertavram Sorry - my bad - I just changed the title of the card, so that it is not confusing any more.

**Comment by mpawlowski85** [comment]
@robertavram 
Just received confimation - the agreements on the list can be deleted. 
Actually I can now do it on the admin panel - do you want me to do it myself?

**Comment by robertavram** [comment]
have fun 👍

**Comment by mpawlowski85** [comment]
Deleted from Production. 
The user was informed. 
The issue is closed.
