### ISSUE TITLE
Action Point Header

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#282]
The field set title for Action Points displays (1) by default even though there isn't any action point assigned. (see screenshot) This creates confusion as if there is an action point added but the system fails to display. 
Expected behaviour : Field set title for action points should read only "Action Points" without the (1), if the user hadn't added any action points. Low/Medium Priority

**Comment by evrimm** [comment]
<img width="1153" alt="screen shot 2017-04-18 at 11 14 12 am" src="https://cloud.githubusercontent.com/assets/1585349/25138369/58f83896-2428-11e7-8040-de6e28786421.png">
