### ISSUE TITLE
IE - As I user I click on Save / Planned trip and I get asked to send a report

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#284]
As a UNICEF User (traveler) I plan a new trip then I click on save immediately I get asked to fill and send a report. 
It is important to clarify/mention that the trip has NOT been approved or saved/. It is only the very first time user completes the form.

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/25147390/5f090248-2445-11e7-8051-40ca5463e22a.png)

**Comment by anusenan** [comment]
So then I tried to add a trip report and save the trip w/o adding any action point and I got the following error:
![image](https://cloud.githubusercontent.com/assets/25492170/25147704/6dc871b4-2446-11e7-8bb9-86583f368d8f.png)

**Comment by janpanchalingam1** [comment]
As a FFP, workspace : Sierra Leone
trip# 2017/30, Browser: IE

**Comment by janpanchalingam1** [comment]
Pass.
