### ISSUE TITLE
Dates are not validated. Itinerary allows dates prior to Start Date

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#285]
As a UNICEF User-Traveler I insert the following dates for my trip in Overview.
April 1 to April 5. 

Then in the Itinerary Section or Trip Activities eTools will accept and save  dates prior to the established Start Date of the trip. 
For example. March 28 (remember that the trip was planned for April 1st).

We need a date validation, before we had a window of dates,  so only activities between the start and end date were accepted and saved.

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/25182568/04ceaa78-24e3-11e7-80ea-f595fb65d992.png)

Here's a screentshot from UAT workspace in staging that shows the discrepancy in dates in an approved trip. Also note that the traveller name is missing even after multiple hard refreshes.
