### ISSUE TITLE
As Finance FP I can't send for payment (IE)

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#287]
Even if invoicing is not ON, when we tested Send for Payment, FFP gets an error saying that a report must be inserted. 
Finance Focal Point shouldn't not be asked to enter a report and a report shouldn't be required at this stage.

**Comment by aldohunicef** [comment]
![image](https://cloud.githubusercontent.com/assets/26142645/25152256/6d1e7d20-2456-11e7-83e3-ae9739441644.png)

**Comment by aldohunicef** [comment]
This is a similar issue to #284

**Comment by anusenan** [comment]
workspace : Sierra Leone 
trip# 2017/30
Browser: IE
