### ISSUE TITLE
'Attachment type' missing in PD/SSFA ToR

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#289]
I am unable to save my attachment because the Attachment type dropdown is missing in Philippines workspace, 
Delete button is not working either.

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/25186836/553f3c6e-24ef-11e7-97a7-7f351de47e67.png)

**Comment by mpawlowski85** [comment]
Please note that this will be an issue in all workspaces that were not migrated from R2.

**Comment by acory** [comment]
@robertavram @ntrncic From my investigation the File Type dropdown doesn't appear when there are no File Types defined for that country and as I understand this can be fixed on backend

**Comment by robertavram** [comment]
Closing since this was fixed with a message, but mostly has to do with missing data
