### ISSUE TITLE
'Add New Partner' failing

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#290]
Clicked on Add New Partner.
Entered a vendor number from Vision. 
Tried to save. System gives the message: Object object ok
Workspace: Manila. 
Vendor Number/Name/Location: 2300084648/ASHBROOKS MERCHANDISING/Manila

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/25199749/deff3e66-2519-11e7-8052-2eb3588f8ab2.png)

**Comment by acory** [comment]
Message {partner_type: ["This field may not be null."]} is returned from backend
