### ISSUE TITLE
Special Characters in Exports

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#291]
For Burkina Faso, when trying to export files, the csv does not display all of the special characters. An example of what is coming in the file: . "THÃ‰ATRE DE L'ESPOIR ". Can we check if this is somthing to do with eTools?

**Comment by ntrncic** [comment]
@mpawlowski85 it's the way excel renders UTF-8 encoded CSV files. In excel you can go to File>Import>Then select downloaded csv>click File Format and choose UTF-8.

**Comment by mpawlowski85** [comment]
@ntrncic Thanks I will pass on the message to the user.

**Comment by mpawlowski85** [comment]
Not a system issue - closing
