### ISSUE TITLE
After rejection trip disappears

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#296]
If a Supervisor rejects the travel and doesn't include a note then the travel will disappear and traveller has no opportunity to correct or plan again. 

Two points here:
Supervisor should not be allowed to reject without a reason 
And eTools should keep record of the trip even if was rejected by Supervisor.

**Comment by janpanchalingam1** [comment]
1) Created and Submitted a Trip for Approval
![image](https://cloud.githubusercontent.com/assets/26144740/25452474/b33c6f86-2a93-11e7-9e2b-91b0ca0e0289.png)

**Comment by janpanchalingam1** [comment]
2) Supervisor rejects trip without note
![image](https://cloud.githubusercontent.com/assets/26144740/25452528/e37a217a-2a93-11e7-874a-c8ff557a8852.png)

**Comment by janpanchalingam1** [comment]
3. I open the trip and information has disappeared 
![image](https://cloud.githubusercontent.com/assets/26144740/25452577/11aea426-2a94-11e7-9e16-c312f8446546.png)

**Comment by janpanchalingam1** [comment]
Pass!
