### ISSUE TITLE
Adding a new PD after opening an existing PD

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#303]
The scenatio is: 
1. Go to PD list (e.g. Jordan)
2. Go to any existing PD (e.g. SSFA BC 3/16)
3. Go back to the list
4. Hit add a new PD/SSFA 

the result of this operation is available in the screenshot below.

**Comment by mpawlowski85** [comment]
![image](https://cloud.githubusercontent.com/assets/26120371/25361221/0b96539c-291b-11e7-84b9-12140a4098c4.png)

**Comment by adi130987** [comment]
We fixed this friday, it will be included in the next staging update.
