### ISSUE TITLE
Missing FRs from Release 2

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#304]
Users say that they added FRs in release 2, but now they are not there after migration. 

Some example from Sudan: 
https://etools.unicef.org/pmp/interventions/68/review-and-sign
Attachments got migrated, FRs – not. 0400036534, 0400040904

https://etools.unicef.org/pmp/interventions/113/review-and-sign
0400032650, 0400036525

https://etools.unicef.org/pmp/interventions/83/review-and-sign
0400032261, 0400037804, 0400037805, 0400038755, 0400038792

SBX also reported the same issue. 
Can these FRs be added as they were there in Release 2?

**Comment by robertavram** [comment]
@ntrncic can you write a script, based on the "pca" reference number.. migrate the old FR numbers for PCA if PCA has fr numbers numbers unless the new record (intervention) has Fr numbers associated with it.

**Comment by mpawlowski85** [comment]
These arejust additional examples of the same issue from Lebanon: 

https://etools.unicef.org/pmp/interventions/123/details
FR number: 0400041490

https://etools.unicef.org/pmp/interventions/142/details
FR number: 0400044188

**Comment by mpawlowski85** [comment]
Failed - the Users reported that there are several FRs per PD added and either none or only 1 was migrated. If multiple FRs were added to the PD, then only a single one was migrated, which does not solve the issue. Steps to reproduce: 
Env: Staging
Worspace: Sudan
Record: https://etools.unicef.org/pmp/interventions/68/review-and-sign
The user claims that in R2 there were 2 FRs: 0400036534, 0400040904
Currently only 1 FR appears (0400040904)

**Comment by mpawlowski85** [comment]
Ok - checked the old database and all FRs that were there are now in R3.
