### ISSUE TITLE
Remove "High Risk Assumed"

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#305]
From Partners ->Assessments -> Assessment Type, 

Remove the type "High Risk Assumed". 

For existing records that have this option selected - please show this as empty and show an error message the next time the user tries to save any other data related to the record. The error message should read: "Please review the "Assessment Type" field".

**Comment by robertavram** [comment]
@mpawlowski85 showing empty and error message means a lot of work for a one-off scenario. Can we give you a list of all records that have "high risk assumed" and somehow coordinate for these to be changed (could be changed from admin worst case scenario) and we remove the option afterwards?

**Comment by mpawlowski85** [comment]
@robertavram do you think it is possible to get the list now, so that I can see how severe the problem is?

**Comment by robertavram** [comment]
@mpawlowski85 the only records are in Ethiopia. Assessment IDs:                                                                                                                                       14, 17  for the  SAVE THE CHILDREN INTERNATIONAL organization(id 227)

**Comment by mpawlowski85** [comment]
@robertavram 
Based on Nazeef's decision both of these records were now deleted. 
Thus there is no more legacy data to handle. 
Please proceed to remove the option from the drop down. 

thanks!
