### ISSUE TITLE
Change Field Name -  UNICEF office" to "UNICEF Field Office

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#308]
In PD/SSFA TOR ->Partnership Information

Change field name: "UNICEF office" to "UNICEF Field Office"

**Comment by mpawlowski85** [comment]
@robertavram Can we please stop work on this please? 
The business requirement changed on this and it should now remain as is. 

@anusenan  Please let me know if it is ok to close the card.

**Comment by robertavram** [comment]
Closing.. @mpawlowski85 understood...
 @anusenan I'm closing it
