### ISSUE TITLE
Population Focus

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#31]
3.3.4	Population Focus
Should not be a mandatory field. Certain PDs will not have a Population Focus.

**Comment by adi130987** [comment]
https://github.com/unicef/etools-partnership-management/pull/190 merged in develop

**Comment by adi130987** [comment]
this is ready to be deployed on staging for testing

**Comment by anusenan** [comment]
@adi130987 can you try moving this to Done column based on the readme document in this repo?
