### ISSUE TITLE
Government validations

### ISSUE THREAD

**Issue by adi130987** [unicef/etools-issues#311]
- go to government details page, click save after removing some values from required fields and the field invalid state will be shown
- go to governments list, then to add new government page
- the invalid fields state is still there

**Comment by roxanavlad** [comment]
- the described issue is fixed, but i found another problem:

Description: Error message still displayed after exiting the government detail page
Steps:
1. select a government from government list (eg. blk:1 from Lebanon)
2. remove data from reference number
3. select enter
4. an error message is displayed: Field number(0) - This field may not be null.
5. go to governments page

Expected result: 
1. the error message is no longer displayed
2. the removal of the reference number is not saved, as the field can't be empty

Actual result: 
1. the error message is displayed on all pages related to governments 
2. the reference number is removed even though t
![capture](https://cloud.githubusercontent.com/assets/28560323/26066539/ecd89fa6-399f-11e7-8823-5fd8faecbdd7.PNG)
he field can't be empty

**Comment by daniel-tabarcea** [comment]
By "the removal of the reference number is not saved, as the field can't be empty" Roxana actually means that we shouldn't be making a call to the server to find out the the ref number is empty, we should validate this browser-side

**Comment by adi130987** [comment]
@daniel-tabarcea please add a frontend validation for this field.

**Comment by ntrncic** [comment]
@adi130987 @daniel-tabarcea please hold off any work on Government pages. The requirements have changed will update shortly.

**Comment by adi130987** [comment]
ok @ntrncic

**Comment by ntrncic** [comment]
closing this card as we are removing Government in Simple
