### ISSUE TITLE
404 on the app selector

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#314]
1. Go to https://etools-staging.unicef.org/ in IE - Dashboard
2. Click on the app selector
3. Click over Trips or PMP ICON
4. 404

**Comment by aldohunicef** [comment]
![tripl](https://cloud.githubusercontent.com/assets/26142645/25452693/788ed184-2a94-11e7-9fef-465b8b6a243b.jpg)

**Comment by aldohunicef** [comment]
![image](https://cloud.githubusercontent.com/assets/26142645/25452823/edc2a62e-2a94-11e7-8e36-bc0e635207a8.png)

**Comment by kasfaw** [comment]
@aldohunicef can you specify the modules and the browsers to which this is occurring from?

**Comment by marko911** [comment]
@aldohunicef @kasfaw I've tried to replicate the issue but couldn't. It behaves as intended when I tried in IE.
