### ISSUE TITLE
IE - Expected results behavious

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#316]
When trying to add an expected result, the screen freezes. The result is displayed in the sceenshot below.

**Comment by mpawlowski85** [comment]
![image](https://cloud.githubusercontent.com/assets/26120371/25453449/02d28e2e-2a97-11e7-9cff-06ef41685407.png)

**Comment by adi130987** [comment]
@mpawlowski85 I can not reproduce this on https://etools-dev.unicef.org/. I can not check it on staging, I do not have an account.

**Comment by mpawlowski85** [comment]
@adi130987 Hi Adi, I cannot reproduce the error today either. It seems like this now became an example of "erratic behaviour". @robertavram would want to know about it, but I guess there is no need to have this issue open any longer?

**Comment by robertavram** [comment]
closing until we can reproduce... if it appears again to anyone, please re-open this issue
