### ISSUE TITLE
PCA End Date

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#32]
The End date for PCA only must be the end date of a country programme. We can either capture this by displaying an error message or by selecting the country programme that the PCA relates to.

**Comment by robertavram** [comment]
@ntrncic backend validation for this one.. if start date, do a get country programme that starts before ends after PCA start date... if not end date or end date != CP end date and Agreement type PCA... return False...  add as a basic validation to agreement

**Comment by mpawlowski85** [comment]
Failed - – it is still possible to add a PCA with an end date other than the last date of CP

**Comment by robertavram** [comment]
Marcin please update the issue as we discussed. There can be issues on breaking validation on existing records... as this is changing soon.. this validation can potentially be destructive short term

**Comment by mpawlowski85** [comment]
As Discussed - this is issue 24 on the re-design list. This can be left for now. I am closing the issue.

**Comment by mpawlowski85** [comment]
@anusenan I closed this issue, as the test failed and there are more detailed specs coming along. Is there a reason why this was re-opened?
