### ISSUE TITLE
Government lists data

### ISSUE THREAD

**Issue by adi130987** [unicef/etools-issues#320]
We need a new property on the governments list data that will contain all the user full names corresponding  to `unicef_focal_points` ids. This will solve the ghost data issue we have on govermnets list details row.

**Comment by adi130987** [comment]
![gov-list-ghost-data](https://cloud.githubusercontent.com/assets/1955740/25474116/a39eccf2-2b3a-11e7-965b-aa65ca173465.png)

**Comment by adi130987** [comment]
backend work here: https://github.com/unicef/etools/pull/644

**Comment by ntrncic** [comment]
@adi130987 please hold off on this one as we are changing the entire Government process

**Comment by adi130987** [comment]
ok

**Comment by adi130987** [comment]
this should be closed as Gov in Simple is removed
