### ISSUE TITLE
Time Selector in Trips does not work

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#325]
Browser: IE
Workspace: Jordan
Steps: 
1. Go to Trips, add a new trip
2. Fill in all of the fields up to the "Departure Date" in the itineratry
3. Try to enter a departure time

At this point the time selector does not work as expected: 
- I click on 2 , but it select 4. 
- When it goes to minutes,  I click on a number and it does not select it at all.
- in minutes, when I click and drag the blue handle, although I drag it to 20 min, there time shows as 9 mins only.

**Comment by janpanchalingam1** [comment]
Unable to replicate in staging. Moving to closed in interim.
