### ISSUE TITLE
Invoices not rendering in staging

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#330]
FFP clicks invoices and all invoices not showing in Chrome and IE

**Comment by janpanchalingam1** [comment]
![image](https://cloud.githubusercontent.com/assets/26144740/25545466/fb70ffd4-2c2c-11e7-919f-ac4e286157d9.png)

**Comment by torbent** [comment]
@janpanchalingam1 we suspect a data integrity issue @simon-the-sloth will investigate this .

**Comment by janpanchalingam1** [comment]
Pass
