### ISSUE TITLE
IE - No Options available in the "Document Type" field.

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#331]
IE - No Options available in the "Document Type" field. Please see screenshot below. 

Browser: IE
Work space: Jordan
Steps: 
1. Add a Partner from another workspace
2. Add SSFA, hit hard refresh
3. Add SSFA TOR

Results: There are "No Options Available" in the Document Type Field (see screenshot).

**Comment by mpawlowski85** [comment]
![image](https://cloud.githubusercontent.com/assets/26120371/25592146/a2974e6c-2e85-11e7-87d1-96614c16f376.png)

**Comment by adi130987** [comment]
@mpawlowski85 I can not reproduce this one either.

I do not understand this "Add a Partner from another workspace". How can we use a partner from another workspace?

Page refresh data functionality has changed.

**Comment by mpawlowski85** [comment]
@adi130987 you can add a partner from another workspace on the partner screen, by clicking "Add New Partner".
