### ISSUE TITLE
IE - Screen Freezes on Save

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#332]
Browser: IE
Workspace: Jordan
Steps: 
1. Add PCA
2. Add Simplified Humanitarian PD - Fill in only Partnership Info and PD or SSFA Details
3. Hit save
The result is in the screenshot

**Comment by mpawlowski85** [comment]
![image](https://cloud.githubusercontent.com/assets/26120371/25592563/3f60036e-2e87-11e7-983e-2076dbcc550c.png)

**Comment by mpawlowski85** [comment]
The Console dump is available here: 
[new 1.txt](https://github.com/unicef/etools-issues/files/968677/new.1.txt)

**Comment by robertavram** [comment]
@mpawlowski85 does this card need updating?

**Comment by adi130987** [comment]
@mpawlowski85 I tried to reproduce this issue but I can not. In the screenshot it's more important to see the inspector console tab(where the error is flagged) and not the debuger tab. 

Let me know if you can still reproduce this issue.

**Comment by roxanavlad** [comment]
tested on dev (IE 11 and Chrome) environment for multiple workspaces - could not reproduce the issue

**Comment by mpawlowski85** [comment]
issue cannot be reproduced and thus it is closed.
