### ISSUE TITLE
Country Selector broken on staging

### ISSUE THREAD

**Issue by lordfuoco** [unicef/etools-issues#335]
Country selector fails to call the refresh of the page on the refresh-component.
Probably a function renaming.
The api call is sent so a manual refresh ( with the hard refresh button in the upper right  corner ) activate the country change.

**Comment by lordfuoco** [comment]
@anusenan @janpanchalingam1 this is a rather small frontend task if you can move it to backlog we can include this in our current sprint

**Comment by janpanchalingam1** [comment]
Pass!
