### ISSUE TITLE
Expenses showing as mandatory upon approval

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#336]
1) User is able to submit a trip for approval. 
2) Supervisor is not able to approve unless expenses are filled out but no error is shown.

**Comment by janpanchalingam1** [comment]
![image](https://cloud.githubusercontent.com/assets/26144740/25714179/25817bae-30c5-11e7-8f46-5b8fa832ddae.png)

**Comment by janpanchalingam1** [comment]
1) Traveller submits a trip for approval
2) Supervisor is unable to approve a trip unless expenses are filled out. 
Rationale: Travellers may not have expenses to claim so this should not be mandatory.
![image](https://cloud.githubusercontent.com/assets/26144740/26001431/55882e98-36fa-11e7-8480-8df3cfd430c4.png)

**Comment by ntrncic** [comment]
Simon has fixed the 500 error. Is travelers to not have expenses a new requirement?

**Comment by janpanchalingam1** [comment]
No, this is not a new requirement. Expenses were always not mandatory.

**Comment by anusenan** [comment]
I tried to recreate the issue in Dev
Workspace- Kyrgystan
TA workflow
Submitted a trip without adding expenses. The supervisor was able to approve it. 
However the FFP was not able to approve - it gave the following error - 
Travel shud have atleast one expense.

**Comment by kasfaw** [comment]
the issue here is that Expenses should NOT be required throughout the lifecycle of a trip.

**Comment by janpanchalingam1** [comment]
Pass
