### ISSUE TITLE
International trip does not allow for reject or complete by supervisor

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#337]

**Comment by janpanchalingam1** [comment]
Browser: IE
Workspace: Kyrgyzstan
Link: https://etools-staging.unicef.org/t2f/edit-travel/175
![image](https://cloud.githubusercontent.com/assets/26144740/25752920/c6d068ea-3187-11e7-8747-12ccd3425fc2.png)

**Comment by janpanchalingam1** [comment]
This may be fixed with #164

**Comment by lordfuoco** [comment]
@janpanchalingam1 I tried to reproduce this bug but I could not, can you try again ? ( also this trip 175 in Kyrgyzstan is not cancelled )

**Comment by kasfaw** [comment]
@torbent we have validated that this works in both chrome and IE and can be marked as resolved

**Comment by janpanchalingam1** [comment]
Pass.
