### ISSUE TITLE
Trip information dissappearing upon opening trip

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#338]

**Comment by janpanchalingam1** [comment]
Browser: IE and Chrome
Workspace: Kyrgyzstan
Link: https://etools.unicef.org/t2f/edit-travel/8

![image](https://cloud.githubusercontent.com/assets/26144740/25761251/3987d4e8-31a8-11e7-86a9-a3b86b20843f.png)

**Comment by janpanchalingam1** [comment]
Browser: Chrome
Workspace: UAT
![image](https://cloud.githubusercontent.com/assets/26144740/25807346/838df800-33d4-11e7-840d-f64a4e401c34.png)

**Comment by lordfuoco** [comment]
this is connected to #339, moving  since is fixed in 339

**Comment by janpanchalingam1** [comment]
Unable to recreate issue in staging. Pass.
