### ISSUE TITLE
Trip is not displaying the record and shows "undefined" date

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#339]
1. User goes in IE and Chrome to Trips Module in Kyrgyzstan (productions)
2. User tries to open a trip created one day ago and it shows an empty record. The trips is Trip 2017/94: 
3. In the list view user see "some" information of that record. However, the end dates says "UNDEFINED" see screenshot. for the empty record just click on the link as it doesn't make sense to add an empty record screenshot. 

This error is available at https://etools.unicef.org/t2f/edit-travel/10 (KYR COUNTRY WORKSPACE) 

Same case is happening in Syria

**Comment by aldohunicef** [comment]
![image](https://cloud.githubusercontent.com/assets/26142645/25761474/ec8d9758-31a8-11e7-9720-8c6c071547dd.png)

**Comment by aldohunicef** [comment]
![image](https://cloud.githubusercontent.com/assets/26142645/25814226/adeede32-33ea-11e7-89ca-99f937478119.png)

**Comment by janpanchalingam1** [comment]
@lordfuoco should the users go in to fix these trips that show 'undefined' ?

**Comment by lordfuoco** [comment]
@janpanchalingam1 I do not understand, the undefined value is not visible in the list anymore, I wrote to you on slack to clarify this!

**Comment by janpanchalingam1** [comment]
Passed in staging.
