### ISSUE TITLE
Changes to Government in Simple 

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#342]
The changes to Government in simple are as follows: 

2.5	Changes to Government in Simple and Dashboards (#69)

![image](https://cloud.githubusercontent.com/assets/26120371/26062679/898e7d62-3959-11e7-8ca4-cb68804b8736.png)

1.	Change name to Government (red box)
2.	The existing Government feature set (Government in Simple) is removed
3.	The Government on the left hand menu remains. However, when the user clicks on Government it is brought to a screen which is comprised of two parts (see below):
a.	A customized view of government partners as per below which is the same list on the Partners tab filtered to just government partners. The name of the list is changed from Partners to Government Partners.

![image](https://cloud.githubusercontent.com/assets/26120371/26062658/7d7971a8-3959-11e7-8021-0b6acc01e5bb.png)

TRIPS module
4.	The User can associated a trip with a govt partner and CP Output
a.	In the Trip Activities card, 
i.	User can select a government partner
ii.	When a government partner is selected, the Partnership field is auto-populated/greyed out/not required
	Edge case: When there is two active CP structures in a business area, user will see all of the CP outputs from both of the CP structures. In these cases, the system will display the WBS code in square brackets to differentiate between the two CP Structures. 
iii.	When a government partner is selected, the Results field is auto-populated with all CP Outputs

DASHBOARDS
Map 
7.	No impact based on our understanding that govt interventions are not showing on the map. 
Partnerships
8.	No impact as partnerships dashboard is being replaced as per PMP specification document
Trips
9.	No impact. 
Personalized
10.	Change name from Government-in-Simple to Government. 
11.	Clicking Government brings me to the workspace Government Partners (see para 3 above)
HACT
12.	All govt PRG2 vendors show in Implementing Partner column (as all have dummy intervention associated with them as per para 5. PRG2 govt vendors where there is no cash transfer in the current programme cycle would be filtered out. 

13.	All columns expect for the ones noted below have no change
a.	Planned for the current year – show “-“
b.	Programmatic Visit Planned – show “-“

**Comment by ewheeler** [comment]
see also
https://github.com/unicef/etools-issues/issues/391

**Comment by asuley** [comment]
@janpanchalingam1 @mpawlowski85 reading #391 I saw that jan stated that selecting a result (CP Output) is optional on trip type prog visit or spot check on a govt partner. That was not my understanding on the final PMP spec nor is it the right behaviour for Trips.  Are we stating result is optional due to same type of work around?

**Comment by janpanchalingam1** [comment]
@asuley we made Results optional in trips because sometimes they were not showing which rendered an error on Save. I spoke with Marcin and the times we do not have a CP output may be during the planning stage, but if this is a required field then we can make the modifications easily
