### ISSUE TITLE
Intervention details - use new version of single select dropdown

### ISSUE THREAD

**Issue by acory** [unicef/etools-issues#348]
List of replaced dropdowns: Partner Organization, Agreement, Document Type, In response to an HRP, Section/Cluster, CP Output, Local Currency, Year(Planned Budger area), Year (Planned Visits area)

Testing hints: 
- test validation 
- test navigating from one intervention to another , new to edit , edit to edit, etc . When going from one existing intervention to another pick 2 interventions that have different options in dropdowns. ex. for the Year dropdown one should have options : 2015, 2016 and one 2017 ,2018 ; different selected value in Partner Organization dropdown etc
- test selected missing options - for this use country Lebanon , go to Last page in the Interventions list and click on the last intervention. This intervention has id : 79. In the CP Output dropdown you should have the 'CP & GBV VIOLATIONS ARE MITIGATED' value selected.
- look for any errors  or warning messages in the Console related to these dropdowns
- in dropdowns that have more than 50 items, select items that are not shown on UI (that have index greated than 50)

**Comment by roxanavlad** [comment]
@acory , this is done
tested on dev
