### ISSUE TITLE
Need to hit save twice to make an Agreement active.

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#35]
When adding a new Agreement and hitting save, it gives the agreement a TempRef Number. You need to hit save again to change status to active and get the final reference number.

**Comment by mpawlowski85** [comment]
I think that this is no longer an issue - please close

**Comment by ewheeler** [comment]
@mpawlowski85 are you not able to close issues?

**Comment by mpawlowski85** [comment]
@ewheeler I cannot see a button to close.

**Comment by mpawlowski85** [comment]
closing
