### ISSUE TITLE
Trigger list update after a save action is made to reflect the saved changed without reloading the list

### ISSUE THREAD

**Issue by adi130987** [unicef/etools-issues#361]
For each page category if an item is saved reload the list to reflect the changes

**Comment by roxanavlad** [comment]
@adi130987 , this is done
tested on dev
tested on IE, Chrome, Mozilla

**Comment by mpawlowski85** [comment]
@anusenan @kasfaw This card cannot be tested during normal testing round, as no steps to reproduce are provided.

**Comment by adi130987** [comment]
@mpawlowski85 sorry for not providing the steps to test this. Before this fix if you would have changed some date on a detail page and then go back to the data list, the changed fields displayed would have the old value because the list was not reloaded. For example:

* open partners list and select a partner
* edit  shared with field and save
* go back to the list and check the details row for that edited partner, it should display the shared with field new values.

This scenario is applied to all the lists.

**Comment by mpawlowski85** [comment]
Thanks @adi130987 I tested this for Partners, Agreements and PD SSFA Lists and it passed in staging.
