### ISSUE TITLE
Display of Download/Change buttons on the Partner screen

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#362]
The Delete/Change buttons seem to be cut off (see the screenshot below). This happens in IE and Chrome.

**Comment by mpawlowski85** [comment]
Chrome:
![image](https://cloud.githubusercontent.com/assets/26120371/26004034/73bfa0dc-3702-11e7-8ec2-95f636add935.png)

IE: 
![image](https://cloud.githubusercontent.com/assets/26120371/26004063/8b7d38ce-3702-11e7-8cdd-ef84cf66ad8c.png)

**Comment by roxanavlad** [comment]
@daniel-tabarcea , @adi130987 , this issue is fixed
tested on dev
tested on IE, Chrome, Mozilla
