### ISSUE TITLE
IE - Unable to change the workspace

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#363]
in IE:
1. Go to www.etools-staging/unicef.org/pmp/
2. Land in Jordan
3. Change to Philippines
4. Do a hard refresh
5. Do a normal refresh 

Result: the workspace dropdown shows Philippoines, but the data is still for Jordan. (see screenshot) 

![image](https://cloud.githubusercontent.com/assets/26120371/26004469/01532418-3704-11e7-811c-2086ef03ff89.png)

Next step: 
6. Select any partner from the list. 

result: screenshow below: 

![image](https://cloud.githubusercontent.com/assets/26120371/26004497/174a3e32-3704-11e7-8b68-400a7fcf7fde.png)

**Comment by roxanavlad** [comment]
@mpawlowski85 , when you say:
Do a hard refresh
Do a normal refresh
what are you referring to? 

are you referring to the following?
a hard refresh = the refresh in the browser
a normal refresh = the refresh in the app

thank you

**Comment by mpawlowski85** [comment]
@roxanavlad 
exactly the opoosite :-) 
normal = Crtl+R
hard = form the app by clicking the "Refresh Data" button. 

![image](https://cloud.githubusercontent.com/assets/26120371/26110017/0d26e34c-3a1f-11e7-8473-427d6bc727f7.png)

**Comment by roxanavlad** [comment]
@mpawlowski85 , thank you for the clarification

**Comment by roxanavlad** [comment]
@adi130987 , this issue is fixed
tested on IE, Chrome, Mozilla
