### ISSUE TITLE
Input labels are missing in IE

### ISSUE THREAD

**Issue by evrimm** [unicef/etools-issues#364]
In Partners -> Staff Members, "Active" checkbox label is not showing. 

In PD/SSFA ToR -> Indicators dialog, #, %, Yes/No labels are not showing.

**Comment by evrimm** [comment]
![active_checkbox_not_showing](https://cloud.githubusercontent.com/assets/1585349/26005683/d7e182e2-3707-11e7-9b64-2e22d92eb341.jpg)
![indicators_not_showing](https://cloud.githubusercontent.com/assets/1585349/26005702/df0e0b3a-3707-11e7-8c7b-e510ac8828d3.jpg)

**Comment by roxanavlad** [comment]
@adi130987 , the issue is fixed
tested on IE 11 and Microsoft Edge 38.14393.1066.0

In Partners -> Staff Members, "Active" checkbox label is showing.
In PD/SSFA ToR -> Indicators dialog, #, %, Yes/No labels are showing.
