### ISSUE TITLE
Integration Test - Unable to activate a PD/SHPD/SSFA TOR

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#365]
Unable to activate a PD/SHPD/SSFA TOR - It is suspected that the status transition was not updated after the population focus field was removed.

**Comment by mpawlowski85** [comment]
I tested in Dev - seemed ok. 

Please push to staging for further testing.

**Comment by kasfaw** [comment]
@anusenan moved this to inbox in case you want to move this to appropriate status

**Comment by mpawlowski85** [comment]
Tested in Staging - passed
