### ISSUE TITLE
Disbursement amt in PD/SSFA TOR Overview

### ISSUE THREAD

**Issue by robertavram** [unicef/etools-issues#370]
Req 2.1

A disbursement amount based on the FRs that are added to the PD/SSFA must be added to the overview tab. This will ensure that the actual amount of the disbursement can be viewed against each of the programme documents / SSFA TORs. That amount will be displayed on the Partner Overview tab against the Total planned budget.

**Comment by robertavram** [comment]
1. Where is the Disbursement amt coming from? 
API example for the FRs: https://devapis.unicef.org/BIService/BIWebService.svc/GetFundsReservationInfo_XML/0060

2. We still need a link to the overview tab redesign.

**Comment by mpawlowski85** [comment]
@mpawlowski85 to get the correct VISION names for the fields, so that they can be taken from the API

**Comment by mpawlowski85** [comment]
The FR Amount in USD is <OVERALL_AMOUNT> (you will need this for the FR table in the PD Overview tab)
The Actual Amount comes from the VISION FI module. We have to ask Uma how we can bring this in. 
@anusenan we need to speak to Uma about this.

**Comment by mpawlowski85** [comment]
This was already implemented. #699 is connected to it, but this is a duplication.  closing the issue
