### ISSUE TITLE
Local Currency Amnesia

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#371]
eTools does not want to remember the local currency. 
Workspace: Philippines
steps: 
1. Insert a new PD, including local currency 
2. Hit save
3. Go to another page or do a ctrl+R
4. Go to the initial PD 

result: the local currency is blank 

the network console shows: 

planned_budget:
[{id: 5, partner_contribution: "44.00", unicef_cash: "53.00", in_kind_amount: "0.00",…}]
{id: 5, partner_contribution: "44.00", unicef_cash: "53.00", in_kind_amount: "0.00",…}
**currency:88**
id:5

**Comment by robertavram** [comment]
@adi130987 this is of high importance / priority.. please set at top of the list

**Comment by adi130987** [comment]
Already fixed today :)

**Comment by adi130987** [comment]
connects unicef/etools-issues#358

**Comment by roxanavlad** [comment]
@adi130987 , this issue is fixed
tested on dev
- the currency is saved when adding a new PD and when editing an existing PD

**Comment by adi130987** [comment]
@mpawlowski85 I think the staging(etools-staging.unicef.org) was not updated properly, it doesn't have the latest changes. I think is still the version of last week.

**Comment by mpawlowski85** [comment]
@adi130987 thanks for the info - it was labeled as in staging, so I tried. I will try again later today.

**Comment by adi130987** [comment]
Something happened with the automatic deploy. I sent a message to the team to look into this issue.

**Comment by roxanavlad** [comment]
@adi130987 , @mpawlowski85 , i tested this bug on staging and it seems to be fixed

**Comment by mpawlowski85** [comment]
@roxanavlad no worries - I was too quick to test in staging - the code was not deployed to staging by the time i tested. I tested it again after deployment and it worked. M.
