### ISSUE TITLE
Change Status Indicator icon

### ISSUE THREAD

**Issue by evrimm** [unicef/etools-issues#378]
Current behavior: eTools indicates the current status of a trip by changing the indicator icon in the status bar: the step number background becomes blue and the step number is bolded.

Expected behavior: Based on user feedback, the current status indicator icon should look the same  as the past statuses, specifically the background is green and checkmark is displayed.

Please note that the only time when a status indicator icon has a blue background is when the user is about to create a new trip, agreement, etc. but hasn't saved yet even once. 

Please see the guides below.

**Comment by evrimm** [comment]
Current Status indicator pattern:
![current_statuses](https://cloud.githubusercontent.com/assets/1585349/26206725/97448116-3bb3-11e7-9c85-9a14f9bbf29d.jpg)
Proposed Status indicator pattern:
![proposed_status_indicator](https://cloud.githubusercontent.com/assets/1585349/26206726/974c44dc-3bb3-11e7-9e31-14c2d579eede.jpg)

**Comment by janpanchalingam1** [comment]
As per October 24 meeting, this is an enhancement due to the senior management decisions made on the trip module and am marking as invalid.
