### ISSUE TITLE
Show Hidden button Slide not working

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#38]
In Partners list view, when u drag/slide the button to ON the list is not showing the deleted partner. But if you click to ON its listing the deleted partners.

**Comment by daniel-tabarcea** [comment]
It seems to work ok now, can someone please check and confirm?

**Comment by anusenan** [comment]
@mpawlowski85 please check and confirm

**Comment by mpawlowski85** [comment]
@anusenan I checked in staging and prod and the hidden partnersh show up when i toggle the "Show Hidden" button.

**Comment by anusenan** [comment]
closing the issue since its working fine.
