### ISSUE TITLE
IE: PD Output display is strange after saving PD data

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#380]
In IE Only: The PD Output display is off after saving PD data
Workspace: Jordan
Link: https://etools-staging.unicef.org/pmp/interventions/76/details

Steps: 
1. Add a new PD
2. Insert all data in PArtnershi Info, PD or SSFA Details. 
3. Insert 1 CP Output, 1 CP Indicator, 1 PD Output and One indicator 
4. Hit Save to save the intervention data 

Result: the indicator is now editable from the main screen (see screenshot)

**Comment by mpawlowski85** [comment]
![image](https://cloud.githubusercontent.com/assets/26120371/26257166/95c6ceea-3c8d-11e7-8ad0-3ce2a24f04c5.png)

**Comment by adi130987** [comment]
@mpawlowski85 just tested this on dev and staging and I can not reproduce it. From the screenshot it looks like there was a javascript error and the `PD or SSFA ToR Output` was not rendered. Could you provide more details on this, maybe a screenshot with the IE console output?

**Comment by adi130987** [comment]
@mpawlowski85 I managed to reproduce this, but I'm not sure why this happens yet. There are no console errors and it's the same issue as #381.

connects and closes unicef/etools-issues#381

**Comment by adi130987** [comment]
@mpawlowski85 can you confirm this is still an issue. PD pages had some changes this week. I tested today(on dev) this issue and I can not reproduce it.

**Comment by mpawlowski85** [comment]
It seem like it works now :-)
