### ISSUE TITLE
IE: No ability to add amendments to SSFA TOR

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#381]
In IE Only
Workspace: Jordan
Steps: 
1. Add a new SSFA TOR that, ensuring that all fieds that are needed for active status are filled in 
•	Start date: has to be at least yesterday
•	End date: Has to be at least tomorrow
•	Title has to be added
•	Partner Focal Point: selected
•	UNICEF Focal point: selected
•	UNICEF Office has to be added
•	Population Focus: Filled in
•	Local currency has to be added
•	Year has to be selected
•	At least 1 Planned budget item has to be filled in and:
-	Unicef Cash has to be more than 0 In USD
-	CSO contribution in both currencies has to be more than 0
•	Sector/Locations must be defined
•	Signed by UNICEF – Signatory and Date (Before starting date)
•	Signed by Partner – Signatory and Date (Before starting date)

2. Hit Save. 

result: no ability to add amendment (in IE only) see screenshot.

**Comment by mpawlowski85** [comment]
![image](https://cloud.githubusercontent.com/assets/26120371/26257370/5b231c7a-3c8e-11e7-941d-2f02471fe5a6.png)

**Comment by adi130987** [comment]
@mpawlowski85 can you confirm this is still an issue. PD pages had some changes this week. I tested today(on dev) this issue and I can not reproduce it.

**Comment by mpawlowski85** [comment]
@adi130987 tested in dev and it seems to be fixed. Can be moved to staging for further testing.
