### ISSUE TITLE
SXB Workspace: 500 Error in PROD

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#382]
I am getting a 500 Error when trying to open: 
https://etools.unicef.org/pmp/agreements/15/details
in  SXB. 

The problem is with a character in wither one of the fields or uploaded file name. 

Console Dump (from Dev, but the same issue happend in PROD)
Request URL:https://etools-dev.unicef.org/api/v2/agreements/15/
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:40.68.121.144:443
Referrer Policy:no-referrer-when-downgrade

Response: UnicodeEncodeError at /api/v2/agreements/15/
'ascii' codec can't encode character u'\u064d' in position 69: ordinal not in range(128)

**Comment by mpawlowski85** [comment]
The link to the sentry Error is as follows: 
https://sentry.io/unicef-jk/etools-prod/issues/233215041/

**Comment by robertavram** [comment]
problem solved today. it was a data issue fluke .. some file path was incorrect
