### ISSUE TITLE
Admin Panel Set Up Problems

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#389]
Mac reported that there were several instances where he is sure that a work space was set up with Sectors and other data, but the sectors data were wiped out. 

The latest example is Burkina Faso (PROD): 
- Mac set up the Sectors/Sections/Offices in Burkina Faso before the Budapest workshop (around 22nd of March) 
- When users wanted to enter the data today (24 May), no Sector/Office data were available in PMP. The only section that was left was "PRIME". 
Can we please see what has happened and how we can avoid this?

**Comment by kasfaw** [comment]
@mpawlowski85 unable to reproduce ... i will keep card in inbox to see if issue persists after the next prd push
