### ISSUE TITLE
Trip Activity Changes for Government Partners

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-issues#391]
On Trip Activity:

IF the selected Partner has a partner type = Government, then the following behaviours should be observed:
- Partnership field should always be optional and locked
- Results should be required IF Trip Type = Programmatic Visit OR Spot Check
- Results should be populated with all CP Outputs for the current country programme ( @robertavram to provide guidance on pulling from backend API)

**Comment by robertavram** [comment]
Results should be populated with all results from the current Active Country Programme/Programmes (the API will return this information), ghosting should be handled for Previous CPs

**Comment by ilcsik** [comment]
@lordfuoco I discussed the backend part for this with @robertavram :

1, Partnership field should always be optional and locked: This should be done only on the frontend.

2, Results should be required IF Trip Type = Programmatic Visit OR Spot Check: For this I have put in a validation on the backend in PR https://github.com/unicef/etools/pull/689

3, Results should be populated with all CP Outputs for the current country: This requires to change the Results endpoint used on the frontend from the static data one to the /api/v2/reports/results/ which filters for current CP already and have ghosting data so no need for backend work. @robertavram  will introduce some name normalization later.

**Comment by lordfuoco** [comment]
@ilcsik @robertavram closing the last tests for this task I noticed that for some combination of partner -partnerships results is not populated ( I do not have a list of results ) So I made the result filed required ONLY if that partnership has a list of associated results. I think this should be done in the backend as well.

Should we take a look at it ?

**Comment by robertavram** [comment]
@lordfuoco I think that if there are no results on the partnership .. no results need to be displayed... there should always be results on partnerships... if there aren';t that means the partnership was not set up correctly and that means no results are populated.. (there are none to verify)... check with @janpanchalingam1 if the requirement is for results to be optional in this case...

**Comment by janpanchalingam1** [comment]
Results are optional

**Comment by lordfuoco** [comment]
@robertavram @janpanchalingam1 perfect is the behaviour that we implemented in the code right now. @torbent

**Comment by janpanchalingam1** [comment]
Pass in Trips and PMP
