### ISSUE TITLE
Expense and Cost Summary details disappearing after save and submit

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-issues#392]
If 4 or more expense types are entered into a trip, the expenses and cost summary detail disappear once the trip is submitted for approval

Steps to reproduce:
1. complete a TA trip with all fields filled out
2. enter 4 or more rows in Expenses section
3. Save and Submit
4. As supervisor and travel, view the expenses and cost assignment sections...they will show to be empty

**Comment by lordfuoco** [comment]
@kasfaw @torbent this is fixed along with 394 essentially being the same bug moving this to staging as well

**Comment by janpanchalingam1** [comment]
Pass
