### ISSUE TITLE
Unable to transition from Planned to Submitted

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#394]
Browser: Chrome and IE
Workspace: Sierra Leone and Kyrgyzstan 
Link: https://etools-staging.unicef.org/t2f/edit-travel/1140 and https://etools-staging.unicef.org/t2f/edit-travel/1145

1) Create a TA trip in Sierra Leone workspace
2) Saved Trip
3) Unable to Submit Trip to Supervisor and transition from Planned to Submitted

**Comment by janpanchalingam1** [comment]
![image](https://cloud.githubusercontent.com/assets/26144740/26496629/56bc83de-41f6-11e7-8098-65c82dcc8699.png)

**Comment by aldohunicef** [comment]
![image](https://cloud.githubusercontent.com/assets/26142645/26501255/11585d16-4207-11e7-916d-6e7c1e5d55eb.png)

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/26501481/c60647c8-4207-11e7-9770-1822cd94d51d.png)


This screenshot shows that user is not able to submit a trip even when all fields including expenses is filled out.  However the response field shows that expenses cannot be null. 
Details: 
Sierra Leone
Trip created on behalf of user. 
Staging

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/26501648/31f8e418-4208-11e7-82b2-3ec8eae9fd35.png)

Here is the same scenario as in staging recreated in Dev. 
User raised trip for herself and is unable to submit it because of the same error
Sierra Leone
Dev

**Comment by anusenan** [comment]
This time while creating the trip no expense was entered and I was able to submit the trip!! 

![image](https://cloud.githubusercontent.com/assets/25492170/26501814/a6f45bda-4208-11e7-8450-6279d74a6156.png)

Details: 
Sierra Leone
Raised for self
Staging

**Comment by janpanchalingam1** [comment]
Pass
