### ISSUE TITLE
PD/SSFA Review and sign changes

### ISSUE THREAD

**Issue by adi130987** [unicef/etools-issues#396]
* add checkbox 'Submitted to PRC?'
* Show PRC fields if checkbox is checked
* Add new upload field
* Update UI

**Comment by evrimm** [comment]
@adi130987 "Days from Submission to Signed" and "Days from Review to Signed" should only  be displayed when the PD/SSFA is signed.(there is an attachment)

**Comment by adi130987** [comment]
@evrim there are big differences between https://projects.invisionapp.com/share/34BI6IINF#/screens/232824150 and https://projects.invisionapp.com/share/34BI6IINF#/screens/231327327 for PRC fields place and also fields state.

The fields must be in the same place no matter if are readonly(locked) or editable, otherwise the frontend functionality will be complicated, longer time to implement  and confusing for the user. In the first invision page the dash underline of the fields is specific to disabled state and not readonly state(locked state).

**Comment by robertavram** [comment]
@adi130987 please go ahead with no 1, since it's the fastest solution. If the design will need to be changed, we'll address that as part of a cleanup sprint. I think getting it to work right is the first priority.

**Comment by adi130987** [comment]
@robertavram should I make the `Submitted to PRC?` checkbox locked/readonly after the agreement is saved and  PRC fields were entered? @evrimm?

**Comment by evrimm** [comment]
@adi130987 Good point. Please make it locked.
