### ISSUE TITLE
Start/End Date overwrite

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-issues#400]
IF Itinerary section is populated, THEN On Save, overwrite Start Date with the earliest departure date on the itinerary and End Date with the latest  arrival date

Start/End Date should still be available for manual entry, but they should always be overwritten on save IF an Itinerary is entered

**Comment by torbent** [comment]
@kasfaw correct me if I'm wrong, but we previously did have a similar implementation that was rejected by the initial user group?

If we implement this as you describe here will mean that whatever any of the users write in the start/end date will be overwritten by any available itinerary data. 
Say you're planning a trip from 10-20 July, enter them manually save and leave it. Later you set the a middle leg of the travel to July 13-14 and save. Now Start end date will change from 10-20 July to 13-14 July. No matter how you change the Start/end date after it will always change back to 13-14 and save it as such. 

If this is accepted behaviour, please confirm it, if not, we could look into raising an "data overwritten" warnings, or set a check that determines if it's a manual input, and not override manually inputted start/end dates.

**Comment by ilcsik** [comment]
@kasfaw so as discussed we will override trip start and end date with earliest itinerary departure date and the latest arrival date respectively if present, regardless of any other state (TA vs non-TA, save only or submit, etc).

**Comment by janpanchalingam1** [comment]
Pass
