### ISSUE TITLE
FFP Unable to change currency in expenses

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#404]
Browser: Chrome and IE
Workspace: Sierra Leone

1) Traveller submits a trip with a traveller expense and travel agency expense
2) FFP unable to edit currency for travel agency expense

**Comment by janpanchalingam1** [comment]
![image](https://cloud.githubusercontent.com/assets/26144740/26732841/00d6b660-4787-11e7-81cd-7468fdf74fdf.png)

**Comment by torbent** [comment]
![Screenshot 2017-06-08 14.37.24.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58ca6974c9b0d72000667588/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36416713e795ce37a24cbb07ff1102f43434d0cfd1f0c0019a5b3dc69b4bc2e728c560ae9d86b5676c33813afb88a1cad1da860c910dfe3efce5ecafa382db58c8b4e6a18074c8cac5a3df4984bc90afe1db04e54b65e.png)

**Comment by torbent** [comment]
We traced this behaviour back to #84 where it was introduced with the rest of the fixes there, but still lack the reason for adding the block. If there was no business requirement for this, we can remove it as you propose.
