### ISSUE TITLE
UNICEF Focal Points List overlapps (ALM 133)

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#405]
UNICEF Focal Points List box search field is overlapped with eTools banner on the top 

Browser: IE and Chrome
Workspace: Jordan and Philipines 
Please find attached Screenshot

**Comment by mpawlowski85** [comment]
![alm_snapshot](https://cloud.githubusercontent.com/assets/26120371/26740344/2425d206-47a3-11e7-849f-3f701ee7719a.jpg)

**Comment by acory** [comment]
Duplicate of #570

**Comment by ntrncic** [comment]
moving to closed as it's a duplicate
