### ISSUE TITLE
CP Result structures should not be filtered by WBS Marker in Palestine

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#408]
In Palestine Country Workspace, Only one CP is set up and it is not a primary CP (the WBS is xxxx/PC/xx rather than xxx/A0/xx) 
Currently, the "CP Output" drop-down only displays results that are associated with the primary. 
 The filtering should be switched of for all countries f to allow for data entry.

**Comment by mpawlowski85** [comment]
@robertavram can you please have a look if there are any consequences

**Comment by mpawlowski85** [comment]
The issue was de-prioritized based. Palestine currently has 20 PDs entered in eTools and the data entry can continue (assuming the CP and PD outputs are omitted).

**Comment by mpawlowski85** [comment]
@ShrinivasPuranik  - this issue needs further discussion to discover available options.

**Comment by ShrinivasPuranik** [comment]
Possibly re engineering required. Implies considerable development.  Similar scenario for other countries (beyond Palestine)  ?

**Comment by ShrinivasPuranik** [comment]
Front end changes in trips to be validated (where the filtering happens ?) Need to check code. Split trips and PMP.
Front end agreement (front end filter) to be changed for Palestine

**Comment by mpawlowski85** [comment]
duplicate of #733
