### ISSUE TITLE
Change Status Indicator Icon

### ISSUE THREAD

**Issue by evrimm** [unicef/etools-issues#418]
Current behavior: eTools indicates the current status of an agreement or intervention by changing the indicator icon in the status bar: the step number background becomes blue and the step number is bolded.

Expected behavior: Based on user feedback, the current status indicator icon should look the same  as the past statuses, specifically the background is green and checkmark is displayed. (Except when the status is Suspended or Terminated)

Please note that the only time when a status indicator icon has a blue background is when the user is about to create a new trip, agreement, etc. but hasn't saved yet even once. 

Please see the guides below.

Current behavior:
![08_1-](https://user-images.githubusercontent.com/1585349/26847655-df497986-4acb-11e7-8a8e-866204113bba.jpg)

Expected behavior for Agreements (with updated status titles) - same behavior should apply for PD/SSFA:
![agreements_new_status](https://user-images.githubusercontent.com/1585349/26851949-8ab54c42-4ada-11e7-9604-c1dbfca1515e.jpg)

**Comment by evrimm** [comment]
@evrimm testing email notifications

**Comment by aldohunicef** [comment]
@evrimm ERWIN TEST

**Comment by evrimm** [comment]
Closed by #398
