### ISSUE TITLE
Update status of migrated trips

### ISSUE THREAD

**Issue by ewheeler** [unicef/etools-issues#431]
1)      The status update is required for two countries – Sierra Leone and Lebanon
2)      All trips created before 6th March- are to be updated to status ‘Complete’ irrespective of their current status
3)      900+ trips in LCO and 200 odd trips in SL

**Comment by kasfaw** [comment]
@janpanchalingam1 we can always move to completed but need the following:
- which workspaces
- which statuses should be moved to completed
- trips created from what date to what date

**Comment by ewheeler** [comment]
From slavi:

<img width="606" alt="screen shot 2017-06-15 at 13 22 43" src="https://user-images.githubusercontent.com/15692/27193669-c172771a-51cd-11e7-85a6-45a9b0d0e0eb.png">

**Comment by ShrinivasPuranik** [comment]
To be followed up during week of Aug 1. Reprioritized after remediation exercise (redesign of PMP). Engineering resource contention.

**Comment by robertavram** [comment]
@janpanchalingam1 @aldohunicef please update the card with our findings...

**Comment by aldohunicef** [comment]
There are 2 validations blocking travellers to create a new trip. 1) If 1 trip is open more than 15 days, then they will not be able to create a new trip. 2) If they have 3 trips in status 'send for payment', 'certification submitted', 'certification approved', 'certification rejected' then they will not be able to create a new trip. After investigating with Rob, we moved a user's trips to completed, users are able to create a new trip. Although, when testing with a user, trips created prior to March 6, cannot be completed by the user as they are unable to progress through the status's:

As seen in the screenshot, a traveller has had their trip approved. I am a FFP, and am unable to send for payment:

Browser: Chrome
Environment: Production
Workspace: Kenya
Link: https://etools.unicef.org/t2f/edit-travel/217
![image](https://user-images.githubusercontent.com/26142645/28084127-a80039d4-6645-11e7-8947-035653518eff.png)

![image](https://user-images.githubusercontent.com/26142645/28084103-99c4f954-6645-11e7-811d-111857a123b5.png)

**Comment by robertavram** [comment]
@aldohunicef @janpanchalingam1 , given what we discovered would you like us to go ahead with migrating those trips to completed in production?

**Comment by janpanchalingam1** [comment]
@robertavram @aldohunicef yes, this was requested by the COs via the RSS's and Wes and would be easier than getting users to go through eTools and complete migrated trips given the uneditable report field and the inability to proceed through status's because of the 400 errors.

**Comment by janpanchalingam1** [comment]
As per prioritization meeting - migrated trips prior to March 6 to be system closed. All trips after March 6, the Roll-Out/RSS team will work on manually closing those trips.

**Comment by ShrinivasPuranik** [comment]
1. Migrated trips < Mar 6, in various statuses, need to be forcibly closed
2. Check trips after Mar 6, if they can be manually closed (if so then RSS can close), Check with validations on
3. Completeness of list: is the list complete ?

**Comment by janpanchalingam1** [comment]
Update from MENA - trips from Jordan should not be marked as completed and should be removed from this list

**Comment by robertavram** [comment]
After migrating in staging.. awaiting official confirmation that this is a go-ahead in production.
Do we schedule a time?
Can we get the final list?
@janpanchalingam1

**Comment by janpanchalingam1** [comment]
@robertavram Update from Jordan - should not be marked as completed and should be removed from this list
Update from Sierrla Leone and Liberia - proceed as requested
Update from Lebanon - proceed as requested
Update from Kenya - proceed as requested

**Comment by robertavram** [comment]
@janpanchalingam1 thanks.. will do.

**Comment by robertavram** [comment]
@janpanchalingam1 DONE
