### ISSUE TITLE
Update to HACT Dashboard Related to Gov't in Simple chnages

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#436]
Updates to HACT Dashboard:
this is the excerpt from card #342 :

12.	All govt PRG2 vendors show in Implementing Partner column (as all have dummy intervention associated with them as per para 5. PRG2 govt vendors where there is no cash transfer in the current programme cycle would be filtered out.

**Comment by mpawlowski85** [comment]
In Jordan, I found 2 Govt IP organisations that received Cash transfers in the current country programme cycle but are not in the HACT Dashboard. These are: 

2500226969	SYRIAN REFUGEES CAMP DEPARTMENT
2500228008	WATER AUTHORITY OF JORDAN

The full details of the analysis are attached below.

**Comment by mpawlowski85** [comment]
[Implementing Partners HACT Report.xlsx](https://github.com/unicef/etools-issues/files/1085271/Implementing.Partners.HACT.Report.xlsx)

**Comment by robertavram** [comment]
2500226969	SYRIAN REFUGEES CAMP DEPARTMENT
2500228008	WATER AUTHORITY OF JORDAN
these seem to be CSOs in eTools... maybe there is an issue with the synchornizer

**Comment by mpawlowski85** [comment]
Thanks, Rob - So I assume that you guys will coordinate this with the InSight team on that. 
Marking @anusenan FYI

**Comment by anusenan** [comment]
@mpawlowski85  Will talk to Uma today about this. This is sue is related to underlying data. Card 436# itself is working and passed right? Should it be marked as failed?

**Comment by mpawlowski85** [comment]
Thanks @anusenan 
As agreed, I created a new card #483 
You can refer to further details on that card when you talk to Uma.

**Comment by anusenan** [comment]
@mpawlowski85  -  is this working now? Are u able to view the partner details on the HACT dashboard?

**Comment by mpawlowski85** [comment]
@anusenan - yes I can! thanks.
