### ISSUE TITLE
Deactivated partner contacts show up in all drop-downs

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#438]
Workspace: All
browser: Chrome, IE

Steps to reproduce: 
1. Add a new partner contact (all fields) 
2. Un-check the "Active?" tick box
3. Add a new Agreement with the partner for which the partner contact you just added 
4. Check the "Signed by Partner" Dropdown
Result: there deactivated partner contact is still listed. 

The desired result is that there deactivated partner contact is not listed on the drop-downs

**Comment by janpanchalingam1** [comment]
Closing card as it is replicated in card 581
