### ISSUE TITLE
Default TA required to be unchecked and hide checkboxes

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#441]
Default all trips to be unchecked for 'TA required' and hide check boxes for TA required and International Trip

**Comment by lordfuoco** [comment]
This means that the whole worflow of TA required is going to be disabled ?

**Comment by janpanchalingam1** [comment]
@lordfuoco @simon-the-sloth @ntrncic can we push this to staging tomorrow please? We have not finished testing but will be done by the end of the day EST

**Comment by lordfuoco** [comment]
@janpanchalingam1 no problem we will merge tomorrow afternoon so

**Comment by janpanchalingam1** [comment]
@lordfuoco thank you!
