### ISSUE TITLE
Create 'Developer Guidelines' document

### ISSUE THREAD

**Issue by vkurup** [unicef/etools-issues#448]
This will be very 'barebones' to start, but will be updated over time as we identify best practices to follow.

Acceptance criteria:
* Add infrastructure to be able to generate docs (sphinx)
* Add a Developer Guidelines stub document
* Content in the initial guidelines document is agreeable to UNICEF

**Comment by ewheeler** [comment]
see also https://github.com/unicef/etools-issues/issues/169

**Comment by vkurup** [comment]
Thanks for that pointer @ewheeler! Will definitely make a point to address those issues.
