### ISSUE TITLE
500 Error in PROD after adding Core Values Assessment

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#457]
This issue only happens to a single user so far. 
Workspace: Burkina Faso
Record: https://etools.unicef.org/pmp/partners/63/details

Steps: 
1. Go to the workspace/record above
2. Try to upload a file to the core values assessment field. 
3. Result: 500 Error

Please note that I am unable to reproduce this error. However, when I got on a call with the user (Issmail), he showed me that the error can be reliably reproduced by him, despite refreshing and cache clearing. 
A dumo from the console is available below.

**Comment by mpawlowski85** [comment]
1.	Request URL:
https://etools.unicef.org/api/v2/partners/63/
2.	Request Method:
PATCH
3.	Status Code:
500 Internal Server Error
4.	Remote Address:
40.68.231.88:443
5.	Referrer Policy:
no-referrer-when-downgrade
2.	Response Headersview source
1.	Content-Length:
15912
2.	Content-Type:
text/html; charset=utf-8
3.	Date:
Thu, 15 Jun 2017 12:39:44 GMT
4.	Server:
gunicorn/19.6.0
5.	Vary:
Cookie
6.	X-Frame-Options:
SAMEORIGIN
3.	Request Headersview source
1.	accept:
application/json
2.	Accept-Encoding:
gzip, deflate, sdch, br
3.	Accept-Language:
en-GB,en;q=0.8,en-US;q=0.6,nl;q=0.4,fr;q=0.2,ar;q=0.2,id;q=0.2
4.	Connection:
keep-alive
5.	Content-Length:
82728
6.	Content-Type:
multipart/form-data; boundary=----WebKitFormBoundaryUjVKJCIGfsv0Ht52
7.	Cookie:
__uvt=; __utmz=51236845.1492074741.4.3.utmccn=(referral)|utmcsr=google.sn|utmcct=/|utmcmd=referral; __unam=1c83e6d-15b8b6b5d95-70ae7b9d-3; __utma=51236845.2022956583.1488884773.1493974946.1494407915.6; sessionid=pdp9esn8blf6bzxxrk66pq5l77oqaxiu; csrftoken=SkscW0dTbRmLGqSAfXMINzXQlZsqLg8m; uvts=5jtlZ3JxS4CRnyTb
8.	Host:
etools.unicef.org
9.	Origin:
https://etools.unicef.org
10.	Referer:
https://etools.unicef.org/pmp/partners/63/details
11.	User-Agent:
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
12.	x-csrftoken:
SkscW0dTbRmLGqSAfXMINzXQlZsqLg8m
4.	Request Payload
1.	------WebKitFormBoundaryUjVKJCIGfsv0Ht52 Content-Disposition: form-data; name="core_values_assessment"; filename="CNAEJTB-2500218372-PCA 2016-Pro-Déclaration.pdf" Content-Type: application/pdf ------WebKitFormBoundaryUjVKJCIGfsv0Ht52--

**Comment by robertavram** [comment]
I have a feeling it must have had something to do with the name containing special characters... this should have been fixed.. can you please confirm.. the fix should already be. in production

**Comment by robertavram** [comment]
@mpawlowski85

**Comment by mpawlowski85** [comment]
Issmail confirms that the issue is fixed and can be closed.
