### ISSUE TITLE
Dates dissappearing on Save in Production

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#459]
Browser: Chrome and IE
Environment: Production
Workspace: Sierra Leone
Links: 
https://etools.unicef.org/t2f/edit-travel/1221 
https://etools.unicef.org/t2f/edit-travel/1222
https://etools.unicef.org/t2f/edit-travel/1220

Steps:
1) Users are saving non-TA as planned
2) Dates disappearing in production in Sierra Leone Workspace

Unable to recreate this in staging or in UAT production environment but is an issue in production workspace.

**Comment by janpanchalingam1** [comment]
![image](https://user-images.githubusercontent.com/26144740/27195059-32410268-51d3-11e7-8d30-1d14cc55943d.png)
![image](https://user-images.githubusercontent.com/26144740/27195094-56ef719e-51d3-11e7-8054-c9f1cc4896b1.png)

**Comment by simon-the-sloth** [comment]
I did some investigation and testing on it but was not able to reproduce this. @janpanchalingam1 Can you reproduce it either on your dev or on your staging server? If yes, then please let me know the procedure.
