### ISSUE TITLE
Activate all currently deactivated CO workspaces

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#472]
Requirement from Rollout team.

**Comment by anusenan** [comment]
As discussed in the prioritization meeting with @kasfaw -  Rollout team will have to manually map the users before engg team activates the workspace.

**Comment by wfurrow** [comment]
Roll-out requires all currently deactivated workspaces to be activated ASAP.  The mapping of users to these workspaces is a separate item that the roll-out team will manage until waffle 434 has been completed.

**Comment by ewheeler** [comment]
@wfurrow user mapping needs to happen before activation as discussed tuesday and noted above

**Comment by ewheeler** [comment]
discussed with @wfurrow and now we're all on the same page.

we'll activate all tomorrow or monday and will let you know once that happens so yall can begin mapping the select users that will begin data entry in some COs ahead of the upcoming bulk user mapping script

**Comment by robertavram** [comment]
COs activated
