### ISSUE TITLE
Unable to import carto db tables into eTools

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#487]
Rollout created Location Types and Carto DB Tables for the Malawi CO workspace in eTools (production), and when they try to import the three Carto DB Tables (Region, District and Traditional Authority) the page loads but none of the Locations are imported from Carto (Locations page is empty). In addition, they do not get an error message after they try to import the tables.

Tested and confirmed in staging and prod

**Comment by janpanchalingam1** [comment]
Carto DB Tables page showing the three tables
![image](https://user-images.githubusercontent.com/26144740/27441363-4d1e74ea-573b-11e7-90f4-b8f0f74bd822.png)

Locations page – there are no locations after they try to import the tables
![image](https://user-images.githubusercontent.com/26144740/27441374-56323562-573b-11e7-8a4a-583afe12aa31.png)

**Comment by kasfaw** [comment]
Kidus to work with Marin on debugging prior to prioritization

**Comment by marindikanovic** [comment]
Spoke to Kidus who mentioned that syncing has been down since 13 June. Here are the links: 
1. https://etools.unicef.org/admin/djcelery/workerstate/
2. https://etools-staging.unicef.org/admin/djcelery/workerstate/
3. https://etools.unicef.org/admin/djcelery/workerstate/2/change/

Thanks,
Marin

**Comment by marindikanovic** [comment]
The Location for Malawi have now been imported into eTools (both Staging and Production). Looks like the fixing the syncing helped. Thanks! Marin
