### ISSUE TITLE
Failed/Forbidden Error while trying to download attachments

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#511]
When a user tries to download an attachment, there is an error that says "Failed/Forbidden" Chrome Error. 
If the user does a refresh, then they are able to download the file. 

Examples of the files where the error occured in Syria Workspace:

https://etools.unicef.org/pmp/interventions/106/attachments
https://etools.unicef.org/pmp/interventions/113/attachments
https://etools.unicef.org/pmp/interventions/149/attachments
https://etools.unicef.org/pmp/interventions/114/details
https://etools.unicef.org/pmp/interventions/62/attachments

**Comment by janpanchalingam1** [comment]
Tested on August 8 in staging, continued issue

**Comment by mpawlowski85** [comment]
Closing the issue - has to do with the access authentication - the link to the blob database link expires after 10 min and a refresh. 
This should be added to the user voice @andreapetkovic

**Comment by MLisDreaming** [comment]
Is there a way to allow for a longer download? Because right now I have a 2 hour download. You found the cause. Not a solution.
