### ISSUE TITLE
Misspelling in PD/SSFA list

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#52]

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23717042/45c8adac-0400-11e7-8fe3-0e0fcd4e337c.png)

**Comment by ewheeler** [comment]
@anusenan same here.. looks like it has been assigned after closing. pls add label as 'invalid', 'wontfix' or 'done' if any of those apply
