### ISSUE TITLE
IE 11 issues

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/etools-issues#520]
Fix ie11 issues with the redesign.
The known issues are: 
 - the required flags don't look ok
 - the "Rows per page"  dropdown doesn't display the entire number on the first load 
 - on list pages date filters don't show the selected date 
 - toast messages may not show

**Comment by roxanavlad** [comment]
test result: pass
tested on IE 11, demo environment

**Comment by mpawlowski85** [comment]
no steps to reproduce
@daniel-tabarcea please close the issue if no longer needed, or add steps to reproduce (especially on the toast message issue).

**Comment by mpawlowski85** [comment]
No Steps to reproduce - closing the issue until an issue is reported.
