### ISSUE TITLE
PCA template - item id sent instead of item label

### ISSUE THREAD

**Issue by acory** [unicef/etools-issues#536]
1. After choosing a template the id (1,2 etc) is sent as a parameter to generate the template instead of the  string naming(english , french etc)
2. Reset dropdown selection after dialog closes

**Comment by roxanavlad** [comment]
test result: pass
tested on dev environment on Google Chrome and IE 11

**Comment by mpawlowski85** [comment]
no steps to reproduce. 
@acory please close if no longer an issue.
