### ISSUE TITLE
IE11 pmp-redesign issues

### ISSUE THREAD

**Issue by adi130987** [unicef/etools-issues#539]
Check PMP-Redesign changes on IE11 and fix found issues:

* lists filters container are extendind too much to the right - layout breaker
* console errors related to FR Numbers consistency behavior

**Comment by roxanavlad** [comment]
@adi130987 
test result: pass
Tested on demo environment on IE 11 and Google Chrome

**Comment by mpawlowski85** [comment]
no steps to reproduce. 
@adi130987 please close if no longer an issue

**Comment by mpawlowski85** [comment]
No steps to reproduce - closing the issue.
