### ISSUE TITLE
Fr validations tooltip display issues

### ISSUE THREAD

**Issue by acory** [unicef/etools-issues#553]
1. False warning tooltip displayed on intervention list for Unicef cash when there is no FR added
2. On intervention details, text is not red colored when tooltip is visible
3. After editing an intervention so that it has validation inconsistencies with FR on dates or amount  and then going to the intervention list , the warning tooltips are shown only after refresh here.
4.  After updating planned budget /unicef cash with a number with decimals other than 0, the intervention-list is updated with the new unicef cash amount but without the decimal part of the number

**Comment by roxanavlad** [comment]
@acory , this done on demo

**Comment by mpawlowski85** [comment]
No steps to reproduce the issues 
@acory please close the card if the issues were resolved.
