### ISSUE TITLE
Adjust Column Width of Agreements list to show Start and End Dates better

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#56]

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23717201/d2a87590-0400-11e7-9592-b3fdde05a2a9.png)

**Comment by ewheeler** [comment]
@anusenan whats up with this one? looks like it has been assigned after closing. was this intentional? lets label as 'invalid', 'wontfix' or 'done' if any of those apply

**Comment by anusenan** [comment]
@ewheeler majority of issues in waffle are recreated from Trello boards. Hence all completed issues in Trello are updated here in Closed and the developer who worked on it was marked in case there are further queries or if historical info is required.

**Comment by ewheeler** [comment]
@anusenan thx!
