### ISSUE TITLE
No ability to bulk upload latest DSA Areashttps://github.com/unicef/etools-issues/issues/218

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#58]
We need to be able to upload latest DSA areas from the Admin page based on the format below:
https://docs.google.com/spreadsheets/d/1cDvH47OE08z4ken_4VYua6DxHi__Grw3siL_xaUKpDs/edit#gid=590900992

Several observations and expected behaviors:
- date format in DSA excel table is dd/mm/yy - the upload script should factor far this as it is not the case at the moment
- DSA areas have unique ids in the DSA excel table that should be used to check for updates 
- the Finalization Date should be used to determine if a DSA area has been added or updated where IF Finalization_Date(Old) < Finalization_Date(New) THEN the DSA Area should be updated
- Old DSA rates areas should not be deleted
- If a DSA Area(new) is removed, then DSA Area(old) should be hidden

**Comment by torbent** [comment]
@anusenan @kasfaw  This will be tied into a larger re-factor task that were discussed in workshop where the following is also added:
- Normalise DSA rates to handle historical data.
- Add “custom”  and  “deprecated” properties to the DSA, update filters to account for this.
- Fetching DSA rates should always show the latest by finalisation date.
 - Ability to upload, process and update latest DSA rates from the format that is pre-processed and provided in internally circulated spreadsheet format.

**Comment by torbent** [comment]
relates to #218

**Comment by janpanchalingam1** [comment]
@torbent is this in the admin?

**Comment by janpanchalingam1** [comment]
Do not have the ability to test this in admin
![image](https://cloud.githubusercontent.com/assets/26144740/25621698/22a571d4-2f20-11e7-85c0-c4ca730ce6b4.png)
![image](https://cloud.githubusercontent.com/assets/26144740/25621709/2c3ad6b2-2f20-11e7-8e57-5f4e60037b9b.png)

**Comment by simon-the-sloth** [comment]
@janpanchalingam1 A new entry can be added via the admin. If you want to test bulk upload, it has to be done via a command line script. @robertavram can help you with that.
Rob: Command to use: `./manage.py update_dsa_regions <input_file_path>` The input file has to be in the exact same format as seen here: https://docs.google.com/spreadsheets/d/1cDvH47OE08z4ken_4VYua6DxHi__Grw3siL_xaUKpDs/edit#gid=590900992

**Comment by anusenan** [comment]
closes #218

**Comment by torbent** [comment]
@anusenan regarding this. If you would like this to become a admin functionality, we need to introduce some extra infrastructure to manage the load in the background. It would add approx 2-3 days to this task. Let us know if you want that addition, else this can be moved to complete.

**Comment by janpanchalingam1** [comment]
@torbent we require an ability to upload the file ourselves not through a command line script

**Comment by kasfaw** [comment]
@torbent @ntrncic my understanding from our call yesterday was that the bottleneck is the formating on the CSV we are uploading. Do let us know the fomat (UTF-8?) and the app to use to generate the csv file (excel vs gsheets)

Looking forward to test this once ready

**Comment by torbent** [comment]
@kasfaw  this is now a encoding+file construction issue that boils down to what the user uploading the csv have of default charsets.... We suggest to export via gSheets on a US lang of windows og Mac, and upload like that. This approach should produce a UTF8 file w. LF line-endings and have not failed us so far.
@ntrncic @robertavram either this should be pushed back with comments on what charsets and exports to support, or this should be approved.

**Comment by kasfaw** [comment]
@torbent @ntrncic Here is the format we will use moving forward. UTF8 and generated from Google Sheets

**Comment by ilcsik** [comment]
Azure compatibility is resolved, tested by @ntrncic  (due to secret credentials) successfully.
There's an open question in the PR regarding speed optimisation vs simplicity, but that does not affect functionality.

**Comment by janpanchalingam1** [comment]
@ntrncic has this been updated? Just checking it and it doesn't seem to be updated:

The Google Sheets:
![image](https://user-images.githubusercontent.com/26144740/27301730-50588546-5502-11e7-8996-0ba5293f9671.png)

And in staging:
![image](https://user-images.githubusercontent.com/26144740/27301753-6341ce06-5502-11e7-9996-bd5f3e8ac655.png)

**Comment by janpanchalingam1** [comment]
De-prioritized as TA is being disabled temporarily
