### ISSUE TITLE
IE: Unable to add new agreement

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#586]
Browser: IE
Workspace: All

1) User clicks 'add agreement'
2) Page does not load. 
3) Refreshed twice, page does not load. See screenshot.

**Comment by janpanchalingam1** [comment]
![image](https://user-images.githubusercontent.com/26144740/29088413-fa65865e-7c46-11e7-9bcb-10e11e8964a5.png)

**Comment by acory** [comment]
Duplicate of  unicef/etools-issues#584
