### ISSUE TITLE
Cannot read property 'partnershipManager' of null

### ISSUE THREAD

**Issue by acory** [unicef/etools-issues#589]
Console error 'Cannot read property 'partnershipManager' of null' when refreshing Agreements list  on dev , country Turkey.
Doesn't reproduce every time, refresh Agreements list or navigate from PD list to Agreements list to reproduce

![error](https://user-images.githubusercontent.com/26309191/29115411-4191d762-7d00-11e7-8807-998ed5ac80b7.png)

**Comment by mpawlowski85** [comment]
Not tested - no steps to reproduce. 
@acory  Please close the issue if it is no longer a problem.
