### ISSUE TITLE
Fix docker machine console access

### ISSUE THREAD

**Issue by csabadenes** [unicef/etools-issues#592]
It's not possible at the moment to ssh into the pmp container. Runing fab ssh:pmp returns the error:
 starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory"

**Comment by csabadenes** [comment]
The Docker machine needs to be recreated  for this fix to work

**Comment by czue** [comment]
my bad. :disappointed:

**Comment by csabadenes** [comment]
This issue was solved, i am closing the card.
