### ISSUE TITLE
Unable to complete trip Post R3- KYR

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#603]
1.  User can't complete this trip in Kyrgyzstan  https://etools.unicef.org/t2f/edit-travel/171 PRD
2. Supervisor can't approve it, the button doesn't appear
3. Trip needs to be forced to "complete"

**Comment by ntrncic** [comment]
@aldohunicef  i've successfully completed the trip. the issue was the certification for TA required trip
