### ISSUE TITLE
SSFA Agreement editable fields

### ISSUE THREAD

**Issue by acory** [unicef/etools-issues#605]
Create new agreement
After save , the Partner dorpdown is editable and authorized officers is readonly.
Problem: I can change the Partner and as a result Authorized Officers are reset and selected becomes blank and I can't select new authorized officers.

*Permission matrix related

**Comment by mpawlowski85** [comment]
@acory this is invalid -  the SSFA agreement should inherit the signed status from the intervention. At the moment it does not work. Once the status issue is addressed, we can see if the fields are editable in signed status. 
I am closing this issue for now.
