### ISSUE TITLE
Madeleine Decker (UNICEF USER/Consultant)

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#607]
Vendor number: 1900836918
eTools PRD and STG is not displaying Madeleine Decker, an active UNICEF Consultant 

She should be mapped to Guinea Country Workspace where she works but she is not appearing in any country in eTools. 
in VISION she is active.

**Comment by aldohunicef** [comment]
![as](https://user-images.githubusercontent.com/26142645/29433633-fee630a6-836d-11e7-8685-2f24f3d663df.png)

**Comment by marindikanovic** [comment]
Please note that a second user cannot be found: Manan Kotak (mkotak@unicef.org)

**Comment by marindikanovic** [comment]
Third user cannot be found: Alice Yasmeen Abdallah (ayabdallah@unicef.org)

**Comment by ntrncic** [comment]
please ask these users to try and login to etools

**Comment by marindikanovic** [comment]
Thanks Nik, Marcin mentioned that so that's what I have been doing with all staff that do not appear in eTools.

Marin

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aldohunicef** [comment]
Madeline Decker was able to log in. 
Still waiting to hear back from the other users.
