### ISSUE TITLE
1) Viewing a previously created TA on Report tab

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#61]
1. When as a traveler I select "add a new trip" the system properly directs me to Edit Trip - Details tab.
2. Then I click on the "Reports" or on the "Attachment" to view.
3. Then I navigate away. 
4. When I subsequently click on "Add a new trip", eTools will direct me to the last tab clicked, "Reports" or "Attachments" and does not default to "Details".
5. The system should always default to the "Details" tab.

Tested in IE and Chrome for Sierra Leone.

**Comment by janpanchalingam1** [comment]
![image](https://cloud.githubusercontent.com/assets/26144740/25434806/c8d9b9bc-2a5b-11e7-8710-7c209d201173.png)

**Comment by janpanchalingam1** [comment]
Passed!
