### ISSUE TITLE
Cost summary should be static on TA creation

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#66]

**Comment by torbent** [comment]
@anusenan this is trivially solved when issue 58 is finished due to the architectural changes that was discussed in workshop on site.

**Comment by anusenan** [comment]
closes issue#58

**Comment by janpanchalingam1** [comment]
Clarification on issue from Kidus on April 18: This card is requesting that DSA rates in the Cost Summary should not be dynamically changing upon saves. It should be static based on approved amount.

**Comment by torbent** [comment]
@janpanchalingam1 @anusenan this is deprecated, and handled in #218
