### ISSUE TITLE
Fix PD overview sector labels

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/etools-issues#669]
![mitica avem o problema.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58c7fddfce9e102000f931b1/125516c66e82c728ace21e0d46e59d8e2a8182e98effba4ee452b0843b49257f2c09a2693cc7f33ab0487e021b4d44be44500d43f8f8dd2da4e239238d545fecd16c0d7c906c12adaa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4f3a18041b88f75c36a49b5985.png)

**Comment by roxanavlad** [comment]
@daniel-tabarcea , this not working on dev. might be a deployment issue

**Comment by roxanavlad** [comment]
@daniel-tabarcea , this works on dev

**Comment by mpawlowski85** [comment]
Failed
there is no longer any section labels in the overview. 
e.g. Jordan
https://etools-staging.unicef.org/pmp/interventions/72/overview

**Comment by daniel-tabarcea** [comment]
@ntrncic why has this failed? I need more info on this
