### ISSUE TITLE
Incomplete Error message is displayed while deleting the "PD output or SSFA result" ALM 220

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#675]
-Create a New PD and fill in the following fields: 
-Partner - Any with a current PCA in place
-Agreement - Select the Signed PCA
-Document Type - PD or SHPD
-Document Title - any
-Partner Focal Points - any
-UNICEF Office(s) - any
-UNICEF Focal Points
-Hit Save
-Contingency PD - Toggle in Off position
-CP Structure - Any
-Start Date - Today or in the past
-End Date - in the future
-Section/Cluster - at least 1
-Locations - at least 1
-CP Output, CP Indicator, PD Output, PD Indicator, Disaggregation - any values 
-Planned Budget card - fill in all available fields
-Planned Visits card - fill in all available fields
-Review and Signs - Signatures and Dates card - fill in all available fields, select "Submitted to PRC" and make sure to upload at least 1 attachment to every field.
FR - add FR where Start and End date and the FR amount is the same as in the PD Details tab (FR amount should equal to UNICEF Cash USD). 
-Hit Save
-In the Review and Sign Tab, select "+" in the Amendments tab
-A message appears on-screen: "All fields in the details tab will now be open for editing. Please change all necessary fields before hitting save"
-Select OK on prompt
-Go to details page
-Try deleting the PD output or SSFA result
-A message prompts "Are you sure you want to delete this item?"
-Click Yes
-An incomplete error message is displayed.

Screenshot attached.

![bug_220_richcontentimage_472690638](https://user-images.githubusercontent.com/26120371/30077180-06daf7bc-9249-11e7-9517-967bd09462b5.png)

**Comment by acory** [comment]
@mpawlowski85  I wasn't able to reproduce this. Can you please try again after the today's deploy ? If there are any console errors , especially on api calls pls attach the response details.

**Comment by mpawlowski85** [comment]
Cannot reproduce the issue. Closing for now until this can be reproduced.
