### ISSUE TITLE
Required fields do not appear as mandatory

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#685]
14.Change SSFA Status to Signed 

Browser:IE
Steps:
-In PD/SSFA Page
-Take a Draft SSFA
-Go to Review & Sign Tab
-Below fields does not appear mandatory until Upload file is clicked.
Signed By Partner Authorized Officer
Signed by partner Date
Signed by UNICEF
Signed by UNICEF Date

Screenshot attached

Before file upload:
![bug_208_before clicking upload file](https://user-images.githubusercontent.com/26120371/30119253-2da98fc0-92f3-11e7-9b59-4252aa1943c0.PNG)

After file upload: 
![bug_208_after clicking upload file](https://user-images.githubusercontent.com/26120371/30119349-686cd734-92f3-11e7-9ee8-1c22c2977e4b.PNG)

**Comment by adi130987** [comment]
@mpawlowski85 this is the PMP-Redesign specification. The fields you mention are not required by default, are required only if you select a signed document (all fields that are required for the intervention to change it's status to `signed` will become required)

**Comment by mpawlowski85** [comment]
thanks @adi130987 
I will close the issue for now. We might revisit this in Priority 2 and 3
