### ISSUE TITLE
Partners: Vendor 2500227395 is showing Type = "CSO / National" on the List when it is actually a UN Agency. ALM 201

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#687]
Browser: Chrome
Workspace: Jordan

1. Turn on "Show Hidden" toggle.
2. Filter Partners by CSO Type = "National".
3. Vendor 2500227395 is displayed with Type = "CSO / National". However, when you click on the Partner to view the details, Partner Type will show "UN Agency/National"

Partners List:
![bug_201_richcontentimage_84843668_1](https://user-images.githubusercontent.com/26120371/30126643-9465c1e0-930a-11e7-89d0-3507cb42bff3.PNG)

Partner Details:
![bug_201_richcontentimage_974587068_1](https://user-images.githubusercontent.com/26120371/30126680-b972168c-930a-11e7-8257-145a20808d77.PNG)

**Comment by adi130987** [comment]
The specs for that details page field was to show `partner type` / `cso type` (is cso type is set).

**Comment by daniel-tabarcea** [comment]
The list shows CSO Type and the Parnters Details tab shows Partner Type, they're different parameters and that's why you're not seeing the same thing

@robertavram @evrimm  should this be different?

**Comment by adi130987** [comment]
@daniel-tabarcea wants to say that on the list data we receive partner type is CSO and on details page the partner type is UN Agency. For the same partner we have partner type different on list and detalis pages. It's a backend issue that needs to checked.

**Comment by evrimm** [comment]
@daniel-tabarcea @mpawlowski85 It looks like the record is set as "National" in VISION, which shouldn't be given it's a UN agency. It should be cleaned up in VISION.

**Comment by mpawlowski85** [comment]
Ok thanks @daniel-tabarcea 
I am marking this as invalid and closing it, as it is a data issue.
