### ISSUE TITLE
IE: While performing any activity in IE, the page gets blank out sometimes.

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#688]
This is a performance issue, while performing any activity in IE, the page gets blank out sometimes.Even after hitting refresh the page does not recover.User needs to logout and login again in this case.This issue is only with IE.Not related to any specific activity/step, happens anytime.Screenshot attached

![bug_195_ie blank out](https://user-images.githubusercontent.com/26120371/30127276-a9495bce-930c-11e7-9d62-cb74d0c008d5.PNG)

**Comment by adi130987** [comment]
@mpawlowski85 ... can you make a screenshot in IE console (F12 to show console) to see if there are errors?

The fact IE11 is an old browser and is far behind any other browser functionality, required by Polymer(used to create etools apps), it has to use additional scripts to make it work and this makes the app much slower(that Chrome for example). 

The browser is using more resources and in this case might be a memory issue.

**Comment by mpawlowski85** [comment]
So this happened again. Here is a sceenshot: 

![bug_195_ie blank out](https://user-images.githubusercontent.com/26120371/31457724-a735d25a-ae8b-11e7-8d46-3b55d188b49b.PNG)

**Comment by adi130987** [comment]
@mpawlowski85 we can not reproduce this bug. We tried last week with no results. We'll keep an eye on it.

**Comment by adi130987** [comment]
@mpawlowski85 I can not reproduce this issue. I think you can close this one.

**Comment by mpawlowski85** [comment]
@adi130987 I will close and re-open if ever reported by a user. thanks.
