### ISSUE TITLE
PD status remains "Active" even if FR is not present in the PD. ALM 232

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#697]
Browser: IE and Chrome 

1.Take a PD which is in signed status
2.Add an FR to it from the intervention not from the admin.
3.Hit SAVE
4.FR gets added, PD becomes active
5.Move to any other page
6.COme back to the PD to which the FR was added.
7.The FR does not display under the Fund Reservation Tab.
8.PD still remains Active.

Note: This issue is intermittent (does not seem to happen to all of the PDs). 

Example: 
1. CATHOLIC RELIEF SERVICES-USCCB
PD: PHI/PCA201748/PD201734 

2.OXFAM GREAT BRITAIN
PD: PHI/PCA201737/PD201731 

![bug_232_richcontentimage_1251955649](https://user-images.githubusercontent.com/26120371/30170229-85dfac46-93bc-11e7-82b5-61e2f4e869a8.png)

![bug_232_richcontentimage_677777577](https://user-images.githubusercontent.com/26120371/30170244-8ca07f9c-93bc-11e7-890f-be2bf51f1421.png)

**Comment by daniel-tabarcea** [comment]
I'm having trouble reproducing this issue, but since you said it was intermittent that's to be expected. 
I think this might be a back-end issue, because: 
1. status transition from 'signed' to 'active' is handled there, so clearly an fr number was present
2. i checked the API response for the records in the pictures and they don't include any FR number, witch from point 1 should have been present.

And is there a chance that the FR numbers assigned to these two PDs got deleted in the mean time?

**Comment by mpawlowski85** [comment]
@daniel-tabarcea 
It is unlikely the FRs would get deleted - the testers raised the PDs, added the FRs and were back to the page in a few minutes, so it is not likely that the FRs were deleted. 
@robertavram @ntrncic - can you please have a look at this one? 
M.

**Comment by mpawlowski85** [comment]
@ntrncic @daniel-tabarcea 
The issue is definitely reoccurring, as it now also happened during the UAT. Screenshots attached. 

In the below case - 2 FRs were added last Friday and the document transitioned to Active. 
Is it possible that the overnight tasks delete the FRs because of some reason? 

![image](https://user-images.githubusercontent.com/26120371/30276686-9914c386-96d3-11e7-869f-a023b14840b3.png)


![image](https://user-images.githubusercontent.com/26120371/30276691-a009995a-96d3-11e7-950e-7550eb4f02fe.png)

**Comment by robertavram** [comment]
@mpawlowski85 hmmm... this is very very interesting.. So... it really should never be intermittent.. now it works now it doesn't... however.. Is it possible that someone is saving this FR Header in the admin after they saved the Intervention in the frontend? (maybe to change the total amts or to test something else?)

**Comment by mpawlowski85** [comment]
Lets put this on hols I will instruct the QA team to referesh both admin and front end.

**Comment by mpawlowski85** [comment]
The issues is closed - this is a remnant of the testing method
