### ISSUE TITLE
When a Finance focal point or Supervisor creates a trip , selecting a Traveller as supervisor, Traveller is able to see the "Approve" button and able to approve the trip. Also email is sent to Traveller for approval.

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#71]

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23724940/af3ba26e-041c-11e7-86e5-4e51a50e6064.png)

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23724953/ba107d22-041c-11e7-97e1-3cd2bf0d44ad.png)

**Comment by kasfaw** [comment]
this is by design and works as expected.
