### ISSUE TITLE
IE- ajax error display in toast

### ISSUE THREAD

**Issue by acory** [unicef/etools-issues#744]
Env: dev

In IE , ajax requests errors are not parsed correctly and are displayed like this:

![ie_error](https://user-images.githubusercontent.com/26309191/30745341-61ffb23c-9fae-11e7-971e-00173e70ada8.png)

Expected:

![expected](https://user-images.githubusercontent.com/26309191/30745390-9141d9b2-9fae-11e7-85c8-35f49786279d.png)

**Comment by mpawlowski85** [comment]
I cannot reproduce the issue. This is now passed until reported again.
