### ISSUE TITLE
(UAT) UNICEF LOGO

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-issues#749]
UNICEF logo appears in the middle of the page for both PRP and PMP Remediation projects

**Comment by KKaselkar** [comment]
![capture1](https://user-images.githubusercontent.com/32198614/30818129-b036af00-a1e8-11e7-8735-3e8fccab6e15.PNG)

**Comment by adi130987** [comment]
@KKaselkar we need more details on this, for example used browser, steps to reproduce and the environment you tested on. Thanks.

**Comment by ewheeler** [comment]
@KKaselkar Removing priority for now.  priorities are added during our weekly prioritization meetings. if you find something you believe needs urgent attention, please escalate to Shrini and myself by email. Removing priority for now.

**Comment by ShrinivasPuranik** [comment]
Browser ?  Does it happen in Chrome?

**Comment by mpawlowski85** [comment]
cannot reproduce - the issue will be raised once reported by user
