### ISSUE TITLE
Jamaica synchronizer failing

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#750]
No options listed for CP Structure, Output and Indicators as the VISION sync is failing for Jamaica

**Comment by ntrncic** [comment]
The workspace was not setup with ResultTypes. There should be three types Outcome, Output and Activity. We have to add a fixture for this for new workspaces created. We have fixed it for Jamaica workspace.

**Comment by mpawlowski85** [comment]
CP Structure, Output and Indicators for Jamaica are now available. 

![image](https://user-images.githubusercontent.com/26120371/31183114-af09bff2-a8f3-11e7-9406-4b3a03da5b44.png)

passed in staging
