### ISSUE TITLE
Non existing users in eTools

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#751]
After the work-around users are still not able to log in. 
Users were requested to try to log in, they did but still the profile was not created in eTools. 

Shunsuke Nioshika
Dearbhla Egan 

Zambia, 
Siphiwe Mbambara

**Comment by ShrinivasPuranik** [comment]
attach error message, email addresses

**Comment by marindikanovic** [comment]
Here are the staff who get a blank page when they try to log in to PROD (after clicking the "staff" button on the home page:

Zodwa Mthethwa: zmthethwa@unicef.org 
Siphiwe Mbambara: smbambara@unicef.org 
Shunsuke Nishioka: snishioka@unicef.org
Dearbhla Egan: degan@unicef.org

**Comment by ShrinivasPuranik** [comment]
to be prioritized after PMP-Redesign

**Comment by ewheeler** [comment]
issue was resolved without any engineering action for:
Zodwa Mthethwa: zmthethwa@unicef.org
Siphiwe Mbambara: smbambara@unicef.org
