### ISSUE TITLE
Remove Arabic option for agreement export

### ISSUE THREAD

**Issue by ntrncic** [unicef/etools-issues#754]

**Comment by daniel-tabarcea** [comment]
Are you referring to the Arabic option in the Generate PCA dialog or is it something else?

**Comment by ntrncic** [comment]
Yes that's exactly it

**Comment by roxanavlad** [comment]
@ntrncic @daniel-tabarcea 
this is working on dev

**Comment by mpawlowski85** [comment]
passed in staging
