### ISSUE TITLE
(UAT) Partnership Dashboard

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-issues#756]
Partnership Dashboard not loading the data, keeps loading but doesn’t display any data. Need browser refresh.

**Comment by aldohunicef** [comment]
![image](https://user-images.githubusercontent.com/26142645/30929234-e4dbc778-a38b-11e7-8da8-e7ab3cb832ec.png)

**Comment by ewheeler** [comment]
@KKaselkar Removing priority for now.  priorities are added during our weekly prioritization meetings. if you find something you believe needs urgent attention, please escalate to Shrini and myself by email. Removing priority for now.

**Comment by ewheeler** [comment]
this is only happening in UAT as far as i can tell

**Comment by KKaselkar** [comment]
It loads the data now, looks like its working today.
