### ISSUE TITLE
Exports not aligned to specifications document

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#76]
review this: https://docs.google.com/spreadsheets/d/1E4qOdZWxtPPCxf3WIH7e8AqKu8-A8hpQr6iDj-uakeo/edit#gid=144405922

**Comment by janpanchalingam1** [comment]
Travel Admin Export - passed testing; export shows fields as defined by specification document 
Travel Activity Export - failed testing; export shows additional data and is not as per the specification document (for example: column "Purpose" and "Supervisor" is not included in the specification)
Finance Export - failed testing; does not download
Invoice Export - passed testing
Traveller misspelled - correct from Traveler to Traveller

**Comment by janpanchalingam1** [comment]
![76 export](https://cloud.githubusercontent.com/assets/26144740/24832212/9e8ec08a-1c78-11e7-982f-824a83df2f91.png)

**Comment by simon-the-sloth** [comment]
I have some questions regarding to activity export: One action point can be connected to multiple trip. Should we include the activity N times if it's connected to N travel or only once? If only once, what should be in the reference number/traveler/office/section/status/secondary traveler columns? Values of the first travel or some aggregation?

**Comment by janpanchalingam1** [comment]
@simon-the-sloth please connect the activity to the N travel, not only once

**Comment by janpanchalingam1** [comment]
Travel Admin Export - passed testing
Finance Export - failed testing; does not download
Travel Activity Export - passed testing
Invoice Export - passed testing

**Comment by simon-the-sloth** [comment]
@janpanchalingam1 There is some data integrity issue. One entity in the database has amount but not currency. How should we deal with this kind of errors? Ignore the row or raise some errors in the csv?

**Comment by janpanchalingam1** [comment]
@simon-the-sloth which entity is this? If possible could we have 1 column for amount and 1 for currency or will this not work?

**Comment by simon-the-sloth** [comment]
@janpanchalingam1  I cannot tell the exact entity, I should debug it, but to do I would need the database dump on my machine.
You mean we should split the currency and amount into 2 columns in the exported csv?

**Comment by torbent** [comment]
@janpanchalingam1 we suspect a data integrity issue @simon-the-sloth is investigate this .

**Comment by kasfaw** [comment]
@torbent @simon-the-sloth my understanding from this comment is that the finance export is not downloading because some invoices have an empty currency column. If that is correct lets do the following:

- UNICEF: we will attempt downloading an invoice list with a clean set of invoices
- Puli: thoroughly test that invoice creation does not create an invoice with required fields like currency missing

**Comment by simon-the-sloth** [comment]
@kasfaw Okay, will do

**Comment by janpanchalingam1** [comment]
Invoice Export - Pass
Travel Activity Export - Pass
Travel Admin Export - Pass
Finance Export - Does not download, fail.

**Comment by janpanchalingam1** [comment]
Finance Export - continues to not download, fail.

**Comment by torbent** [comment]
@janpanchalingam1 @ntrncic @robertavram can we have a weekly DB dump, this tested in DEV and it works there... this is likely a data integrity issue. We need a fresh DB dump to understand this now.

**Comment by janpanchalingam1** [comment]
Passed for all exports
