### ISSUE TITLE
(UAT) - FR Error Message / Icon

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-issues#761]
PD/ SSFA with draft status must not show FR missing error message/icon (red exclamation mark). Error disappears overnight but remain visible for a day of creation.

**Comment by KKaselkar** [comment]
![untitled](https://user-images.githubusercontent.com/32198614/30932802-98cce320-a396-11e7-9133-97fee8745adc.png)

**Comment by ewheeler** [comment]
Please provide details necessary to reproduce

**Comment by KKaselkar** [comment]
Steps to reproduce the error :
1) Add new PD/SSFA and fill all mandatory fields for draft 
2) Save
3) In PD/SSFA list the dates will show the error
we reproduce this error several times but its intermittent.

**Comment by ewheeler** [comment]
@KKaselkar thanks

looks like there is a bug in the [`validateFrsVsInterventionDates` behavior](https://github.com/unicef/etools-partnership-management/blob/staging/pmp/app-elements/interventions/behaviors/fr-numbers-consistency-behavior.html#L76)

probably just need to add a check to return `true` when `intervDateStr` is falsy (just like the check that is used for presence of `frsDateStr`)

.. and maybe also use strict equality (`!===`) when both are truthy  to compare `intervDateStr` and `frsDateStr`

**Comment by daniel-tabarcea** [comment]
@ewheeler I've fixed it so that if the PD has no start and end dates, the error won't show. However if the PD is in draft and has the dates set it will show the error. Is this ok or do you want to hide the error altogether for draft PDs?

**Comment by ewheeler** [comment]
awesome, thanks @daniel-tabarcea 
yes, lets hide altogether for draft status

**Comment by roxanavlad** [comment]
@KKaselkar , @daniel-tabarcea  this looks to be fixed

**Comment by mpawlowski85** [comment]
passed in staging
