### ISSUE TITLE
(UAT) Error message need to be corrected, add “SSFA” after PD

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-issues#763]
Error message need to be corrected, add “SSFA” after PD

**Comment by KKaselkar** [comment]
![untitled](https://user-images.githubusercontent.com/32198614/30933640-1e70cf94-a399-11e7-8771-3a795ed858d1.png)

**Comment by ewheeler** [comment]
Not enough info to reproduce. 
Please provide more detail . This screenshot is too low res to tell anything

**Comment by adi130987** [comment]
This is the message that shows up on save if you selected a `Signed PD/SSFA` and you did not enter all required fields data. We will fix the warning message.

@daniel-tabarcea can you please replace `PD` with `PD/SSFA` in this message:
`Status of the PD will change to signed once all required fields are completed (check DETAILS and REVIEW & SIGN tabs).`? Thanks.

**Comment by mpawlowski85** [comment]
the screen now displays the correct message
![image](https://user-images.githubusercontent.com/26120371/31182881-0aebec24-a8f3-11e7-873c-2a4cf90cb05f.png)

passed in staging
