### ISSUE TITLE
(UAT) Agreement status doesnt change to Ended - PCA

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-issues#768]
PCA is passed dated but still the status shows signed instead of ended. This PCA doesn’t show in CP structure, but it shows in the agreement dropdown.

**Comment by KKaselkar** [comment]
![untitled](https://user-images.githubusercontent.com/32198614/30934286-1f7a4b98-a39b-11e7-978c-02db1a82e24f.png)
![paint1](https://user-images.githubusercontent.com/32198614/30934287-1f8a9fd4-a39b-11e7-905e-fa0df0b3c143.png)

**Comment by mpawlowski85** [comment]
I tried to reproduce like this: 
1. Set up a PCA. 
2. Go to Admin Panel and change the CP end Date to yesterday. Hit Save
3. Do a hard refresh of the data

The end date of the PCA changes, but the status remains as Signed. 
@ntrncic do we need to run a task to change the status?

**Comment by mpawlowski85** [comment]
Once the [.]agreement_status_automatic_transition task is run, then the status changes, which is an expected behaviour. 
closing the issue
