### ISSUE TITLE
(UAT) HACT Dashboard

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-issues#785]
We don't know the logic behind displaying the values in the highlighted column. All the values must show 0 or they don't show 0 then what value is displayed here?
Either you can remove the column or show correct data / values in this column.

**Comment by KKaselkar** [comment]
![30934656-3fd9a9c8-a39c-11e7-8ec2-42ab64fd76f9.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c925e34d3dcd001231c900/125516c66e82c728ace21e0d46bbc4c370d6d5fcd9a4ec45a004f1cd2a1e6a727a5da06621d4e67ff21a7e025d424aae100a5940aaad8e2df0bf2e6c981c49b28b380c30d43703a9b0d018bb00ee26891b80e5bb8218c1e83c77efddde4c3f0c190acbae0361ffc412820db459eb5f54a3193766e670317c4e9c18762f626034e6.png)

**Comment by mpawlowski85** [comment]
@janpanchalingam1 do you have any wisdom?

**Comment by mpawlowski85** [comment]
@janpanchalingam1 planning on taking it out. This card is now closed.
