### ISSUE TITLE
[PROD] Partner missing

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#787]
Partner organization disappeared from Syria Cross Border Workspace 

The partner is: PHYSICIANS ACROSS CONTINENTS.

**Comment by aldohunicef** [comment]
Comment from Nik.: The whole address for the city is entered in VISION. There is a character limit in Etools, and this is why it’s not synced properly.

**Comment by mpawlowski85** [comment]
Fixed and tested by @aldohunicef
