### ISSUE TITLE
Fix data refresh redirect

### ISSUE THREAD

**Issue by daniel-tabarcea** [unicef/etools-issues#793]
Go to the data refresh dialog 
Select Partners
Hit refresh data

Expected: data is refreshed, users is redirected to the partners list with new data
Result: partners list has no records

**Comment by mpawlowski85** [comment]
closes #802

**Comment by roxanavlad** [comment]
test result: pass
tested on dev in Google Chrome and IE 11

**Comment by mpawlowski85** [comment]
passed in staging
