### ISSUE TITLE
Results from past CP not showing up

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#8]
so... if you open a record..

[7:08]  
that was done in the previous country programme

[7:08]  
like an old intervention

[7:09]  
the list of results that were associated with it wi;; show up as blank or missing

[7:09]  
and that's not because they're missing

[7:09]  
but because the data we have on the front end to associate with the ids on the record does not include Results from previous country programmes

**Comment by robertavram** [comment]
Backend ties in to issue of Outputs filtered by CP -> for PD/SSFA TOR

For the rest, @ntrncic @adi130987 we migth need to find a solution for dropdown to call a different endpoint to get output by ID and add that as a property on the EMSM

**Comment by adi130987** [comment]
We need a new endpoint to get cp_output by id

**Comment by adi130987** [comment]
@ntrncic @robertavram do we have an endpoint for this?

**Comment by ntrncic** [comment]
@adi130987 just added in a new branch on backed "filter_cp_outputs". you can filter any output by the following filters at endpoint /api/v2/reports/results/?
result_type=Output 
country_programme=3
result_id=199
year=2017

**Comment by anusenan** [comment]
@robertavram @ntrncic - need to come up with how to test this -

**Comment by mpawlowski85** [comment]
It seems that only some legacy data might be affected. 
We can come back to it if there is an issue raised by a user.
