### ISSUE TITLE
Change Error Message when Suspending an SSFA ALM 288

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#800]
The Error message when suspending an intervention says: 
![image](https://user-images.githubusercontent.com/26120371/31194991-d0f7ff0c-a916-11e7-9d8a-b99eae7829bc.png)

The PD should be changed to "PD/SSFA" to account for the possibility to suspend an SSFA.

**Comment by roxanavlad** [comment]
@daniel-tabarcea 
test result: pass - confirmation message was updated

**Comment by mpawlowski85** [comment]
Passed in staging
