### ISSUE TITLE
All data disappears on hard refresh ALM 285

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#802]
1.Open any page (Partners or Agreements or PD/SSFA in ETools).
2.Select Refresh Data for any single one Page, Either Partners Data or PD/SSFA Data or Agreements Data
Result: All data disappears with a message that "Data is refreshed successfully."

Step 1: 
![image](https://user-images.githubusercontent.com/26120371/31231727-b00554b2-a9b5-11e7-9b93-e7ca35202891.png)

Result: 
![image](https://user-images.githubusercontent.com/26120371/31231716-a2bd85d6-a9b5-11e7-8137-16cc01b54edb.png)

**Comment by adi130987** [comment]
duplicate for #793.
@mpawlowski85 the fix is already merged in dev.

**Comment by mpawlowski85** [comment]
as #793 has fixed the issue, this card is closed.
