### ISSUE TITLE
Search Bar disappears for the CP Output field ALM 284

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#803]
Display issue, In a PD under PD output Tab, sometimes Search button is hidden for CP output field, user needs to adjust the scroll bar inorder to view the search button.
This issue is happening even for the big screen monitors.

![bug_284_new pd _ cp output list box search box hiding behind the banner](https://user-images.githubusercontent.com/26120371/31234919-205b6cf8-a9be-11e7-9e43-1320d413b10d.png)

**Comment by adi130987** [comment]
@mpawlowski85 it seems the header covers the search field. We will take a look, we had a fix for this a while ago.

**Comment by mpawlowski85** [comment]
Seems to be fixed in staging. movig to accepted.
