### ISSUE TITLE
Dropdown(multi) related console log error

### ISSUE THREAD

**Issue by adi130987** [unicef/etools-issues#808]
There is an error on partners page the makes the page unusable.

**Comment by adi130987** [comment]
![partner details console error.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58c6b01a3ac2041a00a63991/125516c66e82c728ace21e0d46f89588378c86bbcfedba57a554fc876945287d3a0baf2e3080f13ab050394d4d1f0cf31b0d0c00eef39b2eaee43b748b080def85680c73ce6910acb9d017e950b921995397f4edd4189fb5646fb2c99d452c1f021288fa5d32a29e4cc859f149e94b47e9.jpg)

**Comment by roxanavlad** [comment]
@adi130987 
fixed; tested on dev environment on Google Chrome and IE11

**Comment by mpawlowski85** [comment]
I cannot reproduce the issue. Marking this as accepted, and we can revisit if/when the issue is reported again.
