### ISSUE TITLE
The Submitted to PRC tickbox is automatically un-ticked on save ALM 300

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#819]
Steps to reproduce: 
-Create a Draft PD.
-Fill all the required fields.
-Go to Review & Sign Tab.
-Click/Check on the Submitted to PRC checkbox.
-Don't update the "Submission Date to PRC" and "Review Date by PRC".
-Only upload PRC review document.
-Hit SAVE.

Result: 
-The "Submitted to PRC" checkbox gets unchecked.
-"Submission Date to PRC", "Review Date by PRC" and attachment fields get hidden.

Expected: 
- The box remains checked on save.

**Comment by mpawlowski85** [comment]
@adi130987 @daniel-tabarcea is this a front end issue?

**Comment by ewheeler** [comment]
possibly related to https://github.com/unicef/etools-issues/issues/693

**Comment by adi130987** [comment]
Yes @ewheeler, it's related to #693.
@mpawlowski85 the `Submitted to PRC` is a computed field on BE and it's returned `true`(`checked`) if there is a `Submission Date to PRC`. We need to improve this condition, maybe check all 3 PRC fields before setting this flag. @robertavram @csabadenes ?
