### ISSUE TITLE
Clean up Lists on Admin Publics section

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#83]

**Comment by torbent** [comment]
@anusenan is this still relevant? We did some updates to the admin since. If relevant still, please specify task

**Comment by kasfaw** [comment]
@torbent @ilcsik this looks good. minor edit:
for /admin/t2f/invoiceitem/ can the Invoice column refer to the invoice reference number instead of "Invoice Object"?

**Comment by ilcsik** [comment]
This is already fixed.

**Comment by janpanchalingam1** [comment]
Pass
