### ISSUE TITLE
Add 'Monitoring Visit' to Trip Type dropdown

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#839]
Please add 'Monitoring Visit (non HACT)' to 'Trip Type' dropdown in Trip Management Module.

**Comment by asuley** [comment]
There have been numerous requests to add different trip types and we have consistently told users that additional trips types would not be added until the field monitoring module is put in place. @janpanchalingam1  can you give me more context as to why this is being put in Waffle now.

**Comment by janpanchalingam1** [comment]
@asuley this was a request from Issmail last week that I had discussed with Slavi. The reasoning from Issmail was "The DepRep here is requesting to add another type of trips called “monitoring visits” but not HACT related. He said that monitoring visits are not always PMVs (and thus HACT-related). Some monitoring visits can be for instance just regular visits to monitoring the implementation of recommendations or actions identified during an earlier PMV."
