### ISSUE TITLE
After submit for approval, all trip fields disappear

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#856]
Trip#2017/134 in Kyrg
Traveler sent trip for approval and after that all fields became blank. https://etools.unicef.org/t2f/edit-travel/193
Trip can't be completed, approved, canceled.

**Comment by aldohunicef** [comment]
![image](https://user-images.githubusercontent.com/26142645/31906859-34cd0e62-b800-11e7-8469-082035bd2b60.png)

**Comment by aldohunicef** [comment]
![untitledj](https://user-images.githubusercontent.com/26142645/31906883-43f0110a-b800-11e7-8f0c-fea7f7072553.png)

**Comment by ShrinivasPuranik** [comment]
Work with field office to reproduce issue.
