### ISSUE TITLE
Trips not modifiable once approved

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#857]
Pending, specifications and BO. approval 

While this made sense when we wanted to create TAs in eTools, it is currently not practical. From staff and senior management here, I was told that the details of a trip, such as dates and activities can change even after the travel plan has been approved (we're not talking about Vision here). However, currently travelers cannot change an approved trip in eTools due to permission restrictions (I for instance can). The only way to change the planned trip is by cancelling, duplicating, changing and resubmitting it for approval. This is not efficient.

The request now is to allow travelers to change an approved trip, which as I mentioned is just a matter of permission setting.

**Comment by janpanchalingam1** [comment]
Ability of user to change a trip after an approval invalidates the whole approval process. For example if you can change your vacation after it has been approved by the supervisor the approval process is rendered useless.
