### ISSUE TITLE
Add type of trip

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#859]
Liberia users are requesting to add another type of trips called "monitoring visits" but not HACT related. He said that monitoring visits are not always PMVs (and thus HACT-related). Some monitoring visits can be for instance just regular visits to monitoring the implementation of recommendations or actions identified during an earlier PMV.

From Indonesia,  In Trip Management under Trip type should there be an option "Results Monitoring" or "Situation Monitoring" for trips that are not Programmatic Visits.

**Comment by janpanchalingam1** [comment]
There have been numerous requests to add different trip types and we have consistently told users that additional trips types would not be added until the field monitoring module is put in place.
