### ISSUE TITLE
Do not allow trip submission for approval for trips that have Start/End date similar to previous trips

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#86]

**Comment by kasfaw** [comment]
@torbent the logic for this should be:

IF action  = "submit for approval" OR "send for payment" OR "certify"
THEN check that (start_date_currenttrip >= end_date_othertrip) OR (end_date_currenttrip <= start_date_othertrip)
WHERE (traveller_currenttrip == traveller_othertrip) AND (status_othertrip != ("planned" OR "cancelled"))

If the dates overlap, then an error message should be sent with following: "You have an existing trip with overlapping dates. Please adjust your trip accordingly."

**Comment by anusenan** [comment]
Passed
