### ISSUE TITLE
Ability to submit for approval/ approve/ and reject trips NOT requiring TA

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#87]

**Comment by janpanchalingam1** [comment]
As per March 21 Budapest meeting:

1) International trips: the traveler can chose Y/N for supervisor approval
2) Non-TA trips: supervisor approval required (Status to change from [Submit for Approval] to [Submit]

**Comment by janpanchalingam1** [comment]
Related to Waffle 164
