### ISSUE TITLE
Supervisor can't see approve button

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#875]
For the trip 
https://etools.unicef.org/t2f/edit-travel/24183 in Lebanon
Supervisor is not able to see approve button

**Comment by aldohunicef** [comment]
![image](https://user-images.githubusercontent.com/26142645/32019783-489ab6cc-b99c-11e7-83a4-53d0aa438801.png)

**Comment by aldohunicef** [comment]
![image](https://user-images.githubusercontent.com/26142645/32019808-57a663dc-b99c-11e7-8e58-3de54aa98624.png)

**Comment by aldohunicef** [comment]
![sofa_aa](https://user-images.githubusercontent.com/26142645/32019843-6c5cc988-b99c-11e7-8214-a4ba3ecf32e1.jpg)

**Comment by ntrncic** [comment]
are you able to reproduce this?

**Comment by aldohunicef** [comment]
You can see  the error live: https://etools.unicef.org/t2f/edit-travel/24183 
The error keeps being reported. we can't reproduce on our own but the fact that keeps being reported shows some issues, right?

**Comment by janpanchalingam1** [comment]
Jan to test this in staging and assign to engineer

**Comment by janpanchalingam1** [comment]
Unable to replicate issue. Marked as invalid.
