### ISSUE TITLE
Missing "Complete" action for Trips that do not require a TA

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#88]
After the meeting conclusions:

1 Remove international travel specific actions
2 International travel and TA not required share the same set of actions ( save, cancel, complete )
3

Complete actions prerequisite: 
1 Trip status: Planned
2 Trip report filled with at least 1 char
3 Overview and Trip activities required field correctly filled ( validation runs ok on them)

**Comment by janpanchalingam1** [comment]
Fixed.
