### ISSUE TITLE
Trip Activities: Results dont filter based on partnership

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#89]

**Comment by janpanchalingam1** [comment]
@torbent the Results dropdown not populating for all country workspaces, is this a new issue or related to this card?
![trip management](https://cloud.githubusercontent.com/assets/26144740/24099011/b1542546-0d43-11e7-89dd-bab1fa30ce3f.png)

**Comment by aldohunicef** [comment]
Trips Module is not populating results from Partnerships.

**Comment by janpanchalingam1** [comment]
Fixed.
