### ISSUE TITLE
Ability to Add New Partner

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#9]
As discussed, prior - we will need to include ability to add a new partner for cases of contingency PCAs, etc. This will be a limited view which allows you to add a vendor number once created and syncs accordingly. I believe you guys already had started working on this before, but will need to implement prior to March 24.

**Comment by robertavram** [comment]
FE and BE... @anusenan add a FE of the same issue add to backlog...

@ntrncic BE separate api endpoint that takes in a number and returns a PartnerOrgDetailSerialized.... PartnerOrg gets retrieved from vision on call.. stored in the DB, (check out PCA generation endpoint for an example of retrieving a PO from vision).

@adi130987  or @daniel-tabarcea   add PartnerOrg button  button.. shoots a modal, prompts for a vendor number... submit the vendor number to the api, call returns .. treat as an edit of PO to update the list values... route to partner detail with route composed from returned ID

**Comment by robertavram** [comment]
this is backend at this point

**Comment by adi130987** [comment]
@robertavram, @ntrncic will there be a separate endpoint for this or just use the partners endpoint with POST?

**Comment by ntrncic** [comment]
@adi130987 separate endpoint

**Comment by adi130987** [comment]
is the endpoint ready?
