### ISSUE TITLE
Incorrect DSA: Same day travel over 9h, calculating DSA+(DSA*.4), Same day less than 8h calculating DSA*0.4

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#90]
Please refer and test against our DSA calculation table

**Comment by janpanchalingam1** [comment]
DSA not calculating correctly
![image](https://cloud.githubusercontent.com/assets/26144740/24973842/413413ae-1f8e-11e7-893d-3eff5e32cf03.png)

**Comment by torbent** [comment]
related to #59

**Comment by janpanchalingam1** [comment]
As it relates to the same issue in #59, removed this waffle as duplicate. To be addressed at #59.
