### ISSUE TITLE
Start & End Date on List not matching actual dates in Form

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#92]
Attached screenshots to show the misalignment.

The dates on the form are the accurate ones

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23755330/fe0ee432-04ad-11e7-9b4e-6c036f0a4edb.png)

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23755339/061f797a-04ae-11e7-9119-b9fd5cbbdca8.png)

**Comment by janpanchalingam1** [comment]
Fixed.
