### ISSUE TITLE
Remap Sections - Trip Management

### ISSUE THREAD

**Issue by marindikanovic** [unicef/etools-issues#922]
Pleas remap the Sections in Trip Management to reflect Sections in Partnership Management.

**Comment by marindikanovic** [comment]
FAILED - Sections that has been remapped show as "Missing Label" in the front end/drop down list of sections in eTools, but remapping appears correctly in Admin Panel.

**Comment by marindikanovic** [comment]
PASSED - the "missing label"  note has disappeared and all new Sections are displayed in Trip Management.

**Comment by domdinicola** [comment]
Great!!!
