### ISSUE TITLE
Major Invoice calculation issues

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#93]

**Comment by anusenan** [comment]
[Invoice_Workflow_8MAR2017_JP.pdf](https://github.com/unicef/etools-issues/files/831315/Invoice_Workflow_8MAR2017_JP.pdf)

**Comment by anusenan** [comment]
On first send for payment, invoices generated TWICE per vendor number
Static expenses (Train, Air, Terminal, Other) NOT showing vendor number of Traveler
On Certified action, with modifications made to the expense or DSA, new invoice NOT generated
Continuously sending for payment keeps creating new invoices WITHOUT any DELTA check
On Certified, executing Send for Payment does not check for delta

**Comment by kasfaw** [comment]
@tejfel @torbent we have also noticed that the invoice reference numbering is not incrementing uniquely by {Business area}/{Year}/{TA} ... instead it continues to increment irrespective of TA.

Expected Sequence: 0600/2017/100/01, 0600/2017/100/02, 0600/2017/100/03, 0600/2017/222/01, 0600/2017/515/01, 0600/2017/222/02, 0600/2017/100/04

Current Behaviour: 0600/2017/100/01, 0600/2017/100/02, 0600/2017/100/03, 0600/2017/222/04, 0600/2017/515/05, 0600/2017/222/06, 0600/2017/100/07

**Comment by janpanchalingam1** [comment]
![image](https://cloud.githubusercontent.com/assets/26144740/24162333/8deef7e8-0e3d-11e7-9ddd-50bbd0e2c5c5.png)

**Comment by kasfaw** [comment]
@simon-the-sloth summarizing our discussion yesterday and from above comments:
- Please follow workflow from above
- The expense type (train exp,air exp, terminal exp, other exp) should be summed together with DSA as part of the traveler's invoice
- Include Estimated Travel Cost exp as part of the Travel Agency cost total
- invoice reference numbering needs to be according to specifications
- On first send for payment, invoices generated TWICE per vendor number (havent reproduced for a while though, but need to build tests around this)
- On Certified action, with modifications made to the expense or DSA, new invoice NOT generated
- Continuously sending for payment keeps creating new invoices WITHOUT any DELTA check
- On Certified, executing Send for Payment does not check for delta

**Comment by kasfaw** [comment]
@simon-the-sloth please make sure that the threshold is calculated against the APPROVED total by the supervisor and not the old total. I point this out because we need to prevent an FFP from sending multiple payments that are below the threshold which (if summed up) would be above the threshold
