### ISSUE TITLE
Itinerary section expands once a user opens a saved trip

### ISSUE THREAD

**Issue by marindikanovic** [unicef/etools-issues#933]
When reopening a saved trip the "Itinerary" section expands and all the fields are visible. It should remain collapsed, just like it is when creating a new trip.

Here are the steps to recreate it:

1. Add new trip
2. Complete the "Overview" section and click Save (trip is in Planned status now)
3. Go back to the list of trips, and click on the new trip you just created
4. The "itinerary" section expands.

Thank you.

**Comment by janpanchalingam1** [comment]
This is now marked as optional which is a workaround.

**Comment by aldohunicef** [comment]
Discussed already. 5-Dec-2017. It did not passed to Backlog
