### ISSUE TITLE
Expense currency should be locked to local currency for non travel agencies even for FFP

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#94]

**Comment by anusenan** [comment]
Simon-->If expense type vendor number == user vendor number, then lock the currency.

**Comment by kasfaw** [comment]
@paragonHex as discussed, this should NOT be locked down to local currency but locked to the selected currency of the TA

**Comment by janpanchalingam1** [comment]
1) User entered an expense first as Afgani
2) User then continued to enter trip information
3) User is able to submit/approve/send for payment trip with different currencies in overview and expenses
![image](https://cloud.githubusercontent.com/assets/26144740/24965134/34877500-1f71-11e7-8793-d739355a434b.png)
![image](https://cloud.githubusercontent.com/assets/26144740/24965139/39ef57b0-1f71-11e7-9f2a-85b3789d5e36.png)
![image](https://cloud.githubusercontent.com/assets/26144740/24965187/5489a9d6-1f71-11e7-96de-450d656eff54.png)

**Comment by torbent** [comment]
@janpanchalingam1 this is out in etools dev, and this is pending staging release next thursday. If this urgently need to get out, we can cherrypick this feature.

**Comment by janpanchalingam1** [comment]
@torbent Nope, not urgent. Thanks for letting me know!

**Comment by zoltanandre** [comment]
@paragonHex 
- adding new expense row is locking the currency
- "default empty object ain't equal with new empty one which you get clicking the new expanse button" by paragonHex

**Comment by janpanchalingam1** [comment]
Passed.
