### ISSUE TITLE
Trip end date can be before start date

### ISSUE THREAD

**Issue by marindikanovic** [unicef/etools-issues#969]
The end date of the trip (e.g. 15 October) can be before the trip start date (e.g 1 November)

**Comment by marindikanovic** [comment]
![image](https://user-images.githubusercontent.com/29664134/33341996-86a45258-d44e-11e7-986f-626f8f2c9b95.png)

**Comment by janpanchalingam1** [comment]
No validation will be built. This is an enhancement.
