### ISSUE TITLE
Can't select today's date as the start date of the Action Point

### ISSUE THREAD

**Issue by marindikanovic** [unicef/etools-issues#970]
Uses are unable to select today's date as the due date of the action Point (earliest date can be tomorrow's date)

**Comment by marindikanovic** [comment]
![image](https://user-images.githubusercontent.com/29664134/33341969-756ca4b8-d44e-11e7-8903-75f2858b9018.png)

**Comment by janpanchalingam1** [comment]
This is an enhancement. The workaround would be a user creates an action point with due date of tomorrow and complete date of today.

**Comment by aldohunicef** [comment]
Discussed already in Prioritization, 5, dec, 2017.
