### ISSUE TITLE
In Action Points list when "SAVE AS OPEN" is clicked on the status bar, the status changes to "Ongoing" instead of "Open".

### ISSUE THREAD

**Issue by marindikanovic** [unicef/etools-issues#973]
Steps:

-Go to Action points list.
-Click on any action point assigned to you, status should be "open" or "cancelled".
-Update any field.
-Go to status bar, click "Save as open"

Result: The status changes to "ongoing". Ideally status should be updated as "Open".

**Comment by marindikanovic** [comment]
![image](https://user-images.githubusercontent.com/29664134/33339782-3e13aff8-d448-11e7-8c99-944345b4e43b.png)

**Comment by janpanchalingam1** [comment]
This will be re-addressed in the Action Point module development.
