### ISSUE TITLE
Changes to Partner resulting from the Auditor Portal (3.12)

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#988]
Once a micro assessment in the AP is in status “Final”, the micro assessment together with the attached file should automatically appear in the Partner record in PMP. The following fields must be populated with the data from the Auditor Portal: 
![image](https://user-images.githubusercontent.com/26120371/33501295-11892fee-d6aa-11e7-9c37-8cf45d3868bd.png)

Along with this, a change to the validation in PMP would have to take place. After a micro assessment is integrated from AP to PMP, the PMP should validate if Date of Assessment from VISION (field 1.2.3) is the same as the Date of Assessment (field 1.2.4.2) of the record that is marked as “Basis for risk rating” (1.2.4.4) entered by the user. If the validation fails, then both dates should display in red, so that the user is prompted to change the basis of risk raring to the correct record.

**Comment by janpanchalingam1** [comment]
Marked as invalid due to waffle 1029 specifications
